# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: planning_stub.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'planning_stub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13planning_stub.proto\x12\nplanner.pb\"\x0f\n\rAssistRequest\"\x89\x01\n\x14\x41ssistRequestSession\x12\x11\n\tis_opened\x18\x01 \x01(\x08\x12\x12\n\nis_updated\x18\x02 \x01(\x08\x12*\n\x07request\x18\x03 \x01(\x0b\x32\x19.planner.pb.AssistRequest\x12\x1e\n\x16incremental_request_id\x18\x04 \x01(\x03\"O\n\x0b\x41ssistDebug\x12@\n\x16\x61ssist_request_session\x18\x05 \x01(\x0b\x32 .planner.pb.AssistRequestSession\"G\n\x16\x42\x65haviorReasonersDebug\x12-\n\x0c\x61ssist_debug\x18\x0e \x01(\x0b\x32\x17.planner.pb.AssistDebug\"T\n\rPlanningDebug\x12\x43\n\x17\x62\x65havior_reasoner_debug\x18\x15 \x01(\x0b\x32\".planner.pb.BehaviorReasonersDebugb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'planning_stub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSISTREQUEST']._serialized_start=35
  _globals['_ASSISTREQUEST']._serialized_end=50
  _globals['_ASSISTREQUESTSESSION']._serialized_start=53
  _globals['_ASSISTREQUESTSESSION']._serialized_end=190
  _globals['_ASSISTDEBUG']._serialized_start=192
  _globals['_ASSISTDEBUG']._serialized_end=271
  _globals['_BEHAVIORREASONERSDEBUG']._serialized_start=273
  _globals['_BEHAVIORREASONERSDEBUG']._serialized_end=344
  _globals['_PLANNINGDEBUG']._serialized_start=346
  _globals['_PLANNINGDEBUG']._serialized_end=430
# @@protoc_insertion_point(module_scope)
