"""Frontend review source contracts; original assertions preserved."""
import unittest
from frontend_contract_fixtures import APP_ENTRY_JS, APP_JS, INDEX_HTML, JS_DIR, Path, STYLES_CSS


class FrontendReviewContractTest(unittest.TestCase):
    def test_model_review_ui_requires_a_run_and_keeps_shared_label_fields_hidden(self) -> None:
        review_form = (JS_DIR / "review-form.js").read_text(encoding="utf-8")
        history = (JS_DIR / "review-history.js").read_text(encoding="utf-8")
        self.assertIn("请先选择 Model Run；共享标签和 GT 请到 问题标注工作台修改。", APP_JS)
        self.assertIn('class="review-section issue-tag-section combined-case-label-card" ${combinedMode ? "" : "hidden"}', review_form)
        self.assertIn('class="review-expected-output-field" hidden', review_form)
        self.assertIn('delete payload.expected_output', review_form)
        self.assertIn('delete payload.is_excluded', review_form)
        self.assertIn('delete payload.tags', review_form)
        self.assertIn('effectiveReviewWorkflowMode(state.selectedCase)', review_form)
        self.assertIn('/combined-review', review_form)
        self.assertIn("未选 Run", review_form)
        self.assertIn("模型复核暂不可用", review_form)
        self.assertIn("选择 Run 后可填写判错原因、缺失信息和截图", review_form)
        self.assertIn("当前仍可提交上方 问题标注", review_form)
        self.assertIn('role="tooltip"', review_form)
        self.assertIn('class="model-review-readonly-note model-review-run-required" role="status"', review_form)
        self.assertIn(".model-review-run-required", STYLES_CSS)
        self.assertIn("!modelReview", history)
        self.assertIn('review_status_counts', (JS_DIR / "analysis.js").read_text(encoding="utf-8"))
        self.assertIn('model_review_status_counts', (JS_DIR / "analysis.js").read_text(encoding="utf-8"))

        self.assertIn("baselineLabelForScope(item.baseline_scope)", APP_JS)
        self.assertIn("...baselineRows", APP_JS)
        self.assertIn("baselineMediaReady", APP_JS)
        self.assertIn("function currentWorksetIssueCount", APP_JS)
        self.assertIn("currentWorksetIssueCount()", APP_JS)
        self.assertIn("inferred_baseline_ids", APP_JS)
        self.assertIn("data-multi-only", APP_JS)
        self.assertIn("onlyThis: true", APP_JS)
        self.assertIn(".multi-filter-only", STYLES_CSS)
        self.assertIn(".multi-filter.is-open .multi-filter-caret", STYLES_CSS)
        self.assertIn("function appendBaselineParams", APP_JS)
        self.assertIn('id="baselineFilter"', INDEX_HTML)
        self.assertIn('id="gtSyncButton"', INDEX_HTML)
        self.assertIn('id="gtSyncSourceTime"', INDEX_HTML)
        self.assertIn('id="gtSyncTooltip" role="tooltip"', INDEX_HTML)
        self.assertIn('aria-describedby="gtSyncTooltip"', INDEX_HTML)
        self.assertIn('"gt-sync.js"', APP_ENTRY_JS)
        self.assertIn("async function refreshAuthoritativeGt", APP_JS)
        self.assertIn('/api/gt-sync', APP_JS)
        self.assertIn('result.status === "running"', APP_JS)
        self.assertIn("GT 后台同步已开始", APP_JS)
        self.assertIn('class="ui-lang-zh">同步</span>', INDEX_HTML)
        self.assertIn(".gt-sync-control .gt-sync-button,", STYLES_CSS)
        self.assertIn("baselines: normalizeBaselineIds(state.selectedBaselineIds)", APP_JS)
        self.assertIn("Array.isArray(current.baselines)", APP_JS)
        self.assertIn('latestGtSyncTimestamp(visibleItems, "last_checked_at")', APP_JS)
        self.assertIn("function renderGtSyncTooltip", APP_JS)
        self.assertIn("本次结果", APP_JS)
        self.assertIn("Trail GT 更新", APP_JS)
        self.assertIn(".gt-sync-meta:hover ~ .gt-sync-tooltip", STYLES_CSS)
        self.assertIn("renderGtSyncStatus(data.gt_sync)", APP_JS)
        self.assertIn(".gt-sync-control", STYLES_CSS)
        self.assertIn("baselines", APP_JS)
        self.assertIn("/static/js/", APP_ENTRY_JS)
        self.assertIn("script.async = false", APP_ENTRY_JS)
        self.assertIn("app.js?v=manual-triage-561", INDEX_HTML)
        self.assertIn('"work-split.js"', APP_ENTRY_JS)
        self.assertIn('"review-assignments.js"', APP_ENTRY_JS)
        # Product logic must live in domain modules, not the entry loader.
        self.assertNotIn("async function bootstrap", APP_ENTRY_JS)
        self.assertNotIn("function withBase(path)", APP_ENTRY_JS)
        self.assertIn("async function bootstrap", APP_JS)
        self.assertIn("function withBase(path)", APP_JS)

    def test_reviewer_facets_merge_current_model_review_heads(self) -> None:
        runs_js = (JS_DIR / "runs.js").read_text(encoding="utf-8")
        self.assertIn("/api/model-review-facets", runs_js)
        self.assertIn("modelReviewFacets?.reviewers", runs_js)
        self.assertIn("model_review_count", runs_js)
        self.assertIn("modelVerifiedCount", runs_js)

    def test_gallery_card_does_not_nest_controls_under_button_role(self) -> None:
        self.assertIn('class="issue-card-open"', APP_JS)
        self.assertIn('data-open-issue="${escapeHtml(item.issue_id)}"', APP_JS)
        self.assertIn('querySelectorAll("[data-open-issue]")', APP_JS)
        self.assertNotIn(
            'data-issue-id="${escapeHtml(item.issue_id)}" role="button"',
            APP_JS,
        )

    def test_gallery_reviewer_metadata_shares_the_label_row(self) -> None:
        card_start = APP_JS.index("function issueCard(item, options = {})")
        card_end = APP_JS.index("\nfunction caseGallerySignature", card_start)
        card_body = APP_JS[card_start:card_end]
        labels_start = card_body.index('<div class="issue-card-labels">')
        labels_end = card_body.index('</div>', labels_start)
        labels_body = card_body[labels_start:labels_end]
        self.assertIn('class="issue-reviewer"', labels_body)
        self.assertNotIn('<div class="issue-reviewer">', card_body)
        self.assertNotIn('${actorKindZh}</span>', labels_body)
        self.assertIn('>${escapeHtml(item.annotation.author)}', labels_body)

    def test_dense_gallery_labels_do_not_split_or_overflow_the_card(self) -> None:
        card_start = APP_JS.index("function issueCard(item, options = {})")
        card_end = APP_JS.index("\nfunction caseGallerySignature", card_start)
        card_body = APP_JS[card_start:card_end]
        self.assertIn("grid-auto-rows: 1fr; align-items: stretch;", STYLES_CSS)
        self.assertIn(".issue-card-heading { min-width: 0; min-height: 19px;", STYLES_CSS)
        self.assertNotIn('class="issue-title"', card_body)
        self.assertNotIn("rawTitle", card_body)
        self.assertIn(".issue-card-labels {\n  min-width: 0; overflow: hidden;", STYLES_CSS)
        self.assertIn(
            ".issue-label-pair { flex: 0 0 auto; display: inline-flex;",
            STYLES_CSS,
        )
        self.assertIn(
            ".issue-label-pair > small { flex: 0 0 auto;",
            STYLES_CSS,
        )

    def test_gallery_heading_only_surfaces_actionable_review_flags(self) -> None:
        self.assertIn("function issueCardReviewFlag(annotation, comparisonStatus", APP_JS)
        self.assertIn('annotation?.is_excluded', APP_JS)
        self.assertNotIn('annotation?.review_status === "needs_gt_review"', APP_JS)
        self.assertIn('data-card-review-flag="excluded"', APP_JS)
        self.assertIn('data-card-review-flag="model_no_gt"', APP_JS)
        self.assertIn("应该排除", APP_JS)
        self.assertIn("GT 待复核", APP_JS)
        self.assertNotIn('labelBadge(annotation, t("gallery.pending_review"))', APP_JS)
        self.assertIn("review_status: item.annotation.review_status", APP_JS)
        self.assertIn("is_excluded: Boolean(item.annotation.is_excluded)", APP_JS)
        self.assertIn(".issue-card-flag-needs-gt", STYLES_CSS)
        self.assertIn(".issue-card-flag-excluded", STYLES_CSS)

    def test_analysis_run_scope_is_ellipsized_with_full_title(self) -> None:
        self.assertIn('$("#analysisReviewScope").title = `${reviewScope}${workSplitSuffix}`;', APP_JS)
        self.assertIn(
            ".analysis-stat-card > small {\n  min-width: 0; overflow: hidden; display: block;",
            STYLES_CSS,
        )
        self.assertIn("text-overflow: ellipsis; white-space: nowrap;", STYLES_CSS)

    def test_manual_triage_brand_links_to_review_home(self) -> None:
        self.assertIn('class="sidebar-copy sidebar-home"', INDEX_HTML)
        self.assertIn('data-page-target="review" data-app-path="/review"', INDEX_HTML)
        self.assertIn('aria-label="Manual Triage 首页"', INDEX_HTML)

    def test_review_filter_type_matches_analysis_filter_type(self) -> None:
        self.assertIn("function scheduleReviewFilterReload", APP_JS)
        self.assertNotIn("const scheduleReviewFilterReload", APP_JS)
        self.assertLess(
            APP_JS.index("function scheduleReviewFilterReload"),
            APP_JS.index("function bindEvents"),
        )
        self.assertIn(".review-filters label { min-width: 0; display: grid; gap: 3px; color: var(--faint); font-size: 11px; }", STYLES_CSS)
        self.assertIn('.review-filters input:not([type="checkbox"]), .review-filters select { min-width: 0; height: 32px; padding: 5px 29px 5px 7px; font-size: 12px; }', STYLES_CSS)
        self.assertIn("repeat(9, minmax(0, .58fr)) auto", STYLES_CSS)
        self.assertIn("filter-submit { height: 32px; padding: 5px 8px; white-space: nowrap; }", STYLES_CSS)
        self.assertIn(".analysis-filters label { min-width: 0; display: grid; gap: 3px; color: var(--faint); font-size: 11px; }", STYLES_CSS)
        self.assertIn('.analysis-filters input:not([type="checkbox"]), .analysis-filters select, .analysis-filters .ui-select-trigger { height: 34px; min-width: 0; padding: 5px 29px 5px 8px; font-size: 12px; }', STYLES_CSS)
        self.assertIn("repeat(9, minmax(90px, 1fr))", STYLES_CSS)
        self.assertIn(".analysis-model-label-filter { grid-column: 1; grid-row: 3; }", STYLES_CSS)
        self.assertIn(".analysis-exclusion-filter { grid-column: 1; grid-row: 2; }", STYLES_CSS)
        self.assertIn(".analysis-comment-state-filter { grid-column: 6; grid-row: 2; }", STYLES_CSS)
        self.assertIn(".analysis-comment-search-filter { grid-column: 7 / -1; grid-row: 2; }", STYLES_CSS)
        self.assertIn(".analysis-search-actions { min-width: 0; display: grid; grid-column: 2 / -1; grid-row: 3; grid-template-columns: minmax(280px, 620px) auto;", STYLES_CSS)
        self.assertIn('class="analysis-model-label-filter"', INDEX_HTML)
        self.assertIn('id="analysisCommentStateFilter"', INDEX_HTML)
        self.assertIn('id="analysisCommentSearchInput"', INDEX_HTML)
        self.assertIn('["comment_state", options.commentState === "all" ? "" : options.commentState]', APP_JS)
        self.assertIn('["comment_search", options.commentSearch || ""]', APP_JS)
        self.assertIn('["issue_ids", joinFilterList(options.issueIds)]', APP_JS)
        self.assertIn('issueIds: parseFilterList(params.get("issue_ids"))', APP_JS)
        self.assertIn('issueIds: parseIssueIdsInput($("#analysisIssueInput")?.value || "").ids', APP_JS)
        self.assertIn('url.searchParams.set("issue_ids", issueIds.join(","))', APP_JS)
        self.assertIn('$("#analysisIssueInput")?.addEventListener("input"', APP_JS)
        self.assertIn('.analysis-issue-input { width: 100%; min-width: 0; height: 34px;', STYLES_CSS)
        self.assertIn('.analysis-issue-input { height: 44px; min-height: 44px !important;', STYLES_CSS)
        self.assertIn('commentState: ["with", "without"].includes(params.get("comment_state"))', APP_JS)
        self.assertIn('commentSearch: params.get("comment_search") || ""', APP_JS)
        self.assertIn("function persistCurrentAnalysisRoute(overrides = {})", APP_JS)
        self.assertIn("persistCurrentAnalysisRoute({\n    ...analysisRequestOptions(),\n    page: 1,", APP_JS)
        self.assertIn("width: 15px; min-width: 15px; max-width: 15px; height: 15px; margin: 0; padding: 0;", STYLES_CSS)
        self.assertIn("display: grid; place-content: center; box-sizing: border-box;", STYLES_CSS)
        self.assertIn("flex: 1 1 0; min-width: 0; height: 26px; padding: 0 6px; border: 1px solid #344154;", STYLES_CSS)
        self.assertIn("height: 24px; padding: 0 8px; border: 1px solid rgba(34,211,238,.32);", STYLES_CSS)
        self.assertIn("min-height: 34px; border: 1px solid transparent;", STYLES_CSS)
        self.assertIn('id="analysisExclusionFilter"', INDEX_HTML)
        self.assertIn('id="reviewExclusionFilter"', INDEX_HTML)
        self.assertIn('id="reviewDiscussionFilter"', INDEX_HTML)
        self.assertIn("function selectedReviewDiscussionFilter", APP_JS)
        self.assertIn('params.set("comment_state", commentState)', APP_JS)
        self.assertIn('url.searchParams.set("comment_state", review.commentState)', APP_JS)
        self.assertIn('setMultiFilterValues($("#reviewDiscussionFilter"), [])', APP_JS)
        self.assertIn('data-placeholder="全部（含问题排除）"', INDEX_HTML)
        self.assertIn("function selectedAnalysisExclusionFilter", APP_JS)
        self.assertIn("function selectedReviewExclusionFilter", APP_JS)
        self.assertIn('params.set("exclusion", exclusion)', APP_JS)
        self.assertIn('exclusion: selectedAnalysisExclusionFilter()', APP_JS)
        self.assertIn('selectedReviewExclusionFilter()', APP_JS)
        self.assertIn(".analysis-exclusion-filter", STYLES_CSS)

    def test_tags_have_shared_scene_catalog_and_user_access_has_a_separate_admin_page(self) -> None:
        self.assertNotIn('id="manageReviewTagsButton"', INDEX_HTML)
        self.assertNotIn('id="tagManagerDialog"', INDEX_HTML)
        self.assertIn('/api/review-tags', APP_JS)
        self.assertIn('id="userManagementNavButton"', INDEX_HTML)
        self.assertIn('data-app-path="/users"', INDEX_HTML)
        self.assertIn('id="userManagementPage"', INDEX_HTML)
        self.assertIn("userManagementNav.hidden = !state.session.is_admin", APP_JS)
        self.assertIn('api("/api/access-users"', APP_JS)
        self.assertNotIn('id="addSceneTagButton"', APP_JS)
        self.assertIn(".access-panel { width: min(980px, 100%); max-width: 980px; margin-inline: auto;", STYLES_CSS)

    def test_review_panel_separates_issue_tags_and_model_error(self) -> None:
        self.assertIn("function renderReviewTagGroups", APP_JS)
        self.assertIn('class="review-section issue-tag-section combined-case-label-card"', APP_JS)
        self.assertIn('class="review-section model-error-section"', APP_JS)
        self.assertIn('class="review-tag-dropdown review-dropdown"', APP_JS)
        self.assertIn('data-tag-summary=', APP_JS)
        self.assertIn('data-tag-group=', APP_JS)
        self.assertIn('data-tag-dropdown-shortcut=', APP_JS)
        self.assertIn('const REVIEW_TAG_GROUP_SHORTCUTS = Object.freeze({', APP_JS)
        self.assertIn('q: "environment"', APP_JS)
        self.assertIn('w: "self_intent"', APP_JS)
        self.assertIn('a: "false_trigger"', APP_JS)
        self.assertIn('s: "true_trigger"', APP_JS)
        self.assertIn('z: "ra"', APP_JS)
        self.assertIn('x: "no_assist"', APP_JS)
        self.assertIn('function bindReviewKeyboardShortcuts()', APP_JS)
        self.assertIn("function handleReviewDropdownKeyboard(event)", APP_JS)
        self.assertIn("function reviewDropdownShortcutAllowed(target)", APP_JS)
        self.assertIn("reviewDropdownShortcutAllowed(target)", APP_JS)
        self.assertIn('const REVIEW_MISSING_EVIDENCE_SHORTCUT = "i";', APP_JS)
        self.assertIn("function openReviewMissingEvidenceShortcut()", APP_JS)
        self.assertIn("data-missing-evidence-dropdown", APP_JS)
        self.assertIn('summary aria-keyshortcuts="I"', APP_JS)
        self.assertIn('data-shortcut-search="i"', INDEX_HTML)
        self.assertIn('<kbd>I</kbd></span><strong>展开 / 收起缺失信息</strong>', INDEX_HTML)
        self.assertIn("切换已打开标签或缺失信息中的选项", INDEX_HTML)
        self.assertIn(".review-tag-dropdown[open] > summary .tag-group-shortcut", STYLES_CSS)
        self.assertIn('if (active?.closest(".review-dropdown")) active.blur();', APP_JS)
        self.assertIn("box-shadow: inset 0 0 0 1px rgba(34,211,238,.42);", STYLES_CSS)
        self.assertIn('event.key === "ArrowDown" || event.key === "ArrowUp"', APP_JS)
        self.assertIn("function submitReviewFromDropdown(event, target)", APP_JS)
        self.assertIn("function submitReviewFromKeyboard(event, target)", APP_JS)
        self.assertIn("if (submitReviewFromKeyboard(event, target)) return;", APP_JS)
        self.assertIn('event.key !== "Enter"', APP_JS)
        self.assertIn("event.shiftKey", APP_JS)
        self.assertIn("event.isComposing", APP_JS)
        self.assertIn('$("#annotationForm")?.requestSubmit($("#reviewSaveButton") || undefined)', APP_JS)
        self.assertIn('if (event.key === " " && currentIndex >= 0)', APP_JS)
        self.assertIn('data-review-dropdown-option-shortcut=', APP_JS)
        self.assertIn("function syncReviewDropdownShortcutHints(root = document)", APP_JS)
        self.assertIn('input[name="reviewTags"], input[name="missingEvidence"]', APP_JS)
        self.assertIn("function toggleOpenReviewDropdownOption(shortcut)", APP_JS)
        self.assertIn('"9", "0", "-", "="', APP_JS)
        self.assertIn("REVIEW_TAG_OPTION_SHORTCUTS.includes(shortcut)", APP_JS)
        self.assertIn('key === "[" || key === "]"', APP_JS)
        self.assertIn('class="review-control-shortcut review-nav-shortcut"', APP_JS)
        self.assertIn('.review-control-shortcut {', STYLES_CSS)
        self.assertIn("grid-template-columns: minmax(0, 1fr) auto auto", STYLES_CSS)
        self.assertIn("text-overflow: ellipsis; white-space: nowrap", STYLES_CSS)
        self.assertIn("min-width: 67px; display: inline-flex", STYLES_CSS)
        self.assertNotIn("review-section-kicker", APP_JS)
        self.assertNotIn("review-section-help", APP_JS)
        self.assertNotIn("review-scope-note", APP_JS)
        self.assertIn("function currentRunOutputMarkup", APP_JS)
        self.assertIn("当前 Run Reason", APP_JS)
        self.assertNotIn("完整 Config", APP_JS)
        self.assertNotIn("原始输出对象", APP_JS)
        self.assertIn('id="reviewExcludeInput"', APP_JS)
        self.assertIn('id="reviewExcludeInput" type="checkbox" aria-keyshortcuts="K"', APP_JS)
        self.assertIn('class="review-control-shortcut review-exclude-shortcut"', APP_JS)
        self.assertIn("function toggleReviewExcludeShortcut()", APP_JS)
        self.assertIn('key === "k"', APP_JS)
        self.assertIn('data-shortcut-search="k"', INDEX_HTML)
        self.assertIn(".review-exclude-shortcut {", STYLES_CSS)
        self.assertIn('class="ui-lang-zh">应该排除</strong>', APP_JS)
        self.assertIn('class="ui-lang-en">Exclude</strong>', APP_JS)
        self.assertNotIn('<strong>是否应该排除</strong>', APP_JS)
        self.assertNotIn('class="review-title"', APP_JS)
        self.assertIn("Issue 标签", APP_JS)
        self.assertIn("Issue tags", APP_JS)
        self.assertIn("模型结果 Review", APP_JS)
        self.assertIn("Model Result Review", APP_JS)
        self.assertNotIn("<h2>模型判错</h2>", APP_JS)
        self.assertIn('data-open-history="review"', APP_JS)
        self.assertNotIn('class="review-history-toggle"', APP_JS)
        self.assertIn(".review-section-heading h2 { color: var(--text); font-size: 16px; }", STYLES_CSS)
        self.assertIn("is_excluded: Boolean($(\"#reviewExcludeInput\")?.checked)", APP_JS)
        app_root = Path(__file__).resolve().parents[1].joinpath("app")
        main_py = "\n".join(
            p.read_text(encoding="utf-8")
            for p in [
                app_root / "runtime_catalogs.py",
                app_root / "http_support.py",
                app_root / "main.py",
            ]
        )
        self.assertIn('"section": "scene"', main_py)
        self.assertIn('"section": "egress"', main_py)
        self.assertIn('"section": "interaction_decision"', main_py)
        self.assertIn('"group": "environment"', main_py)
        self.assertIn('"group": "self_intent"', main_py)
        self.assertIn('"group": "false_trigger"', main_py)
        self.assertIn('"group": "true_trigger"', main_py)
        # Axis/group chrome uses message-catalog keys (I18n); domain option labels stay catalog Chinese.
        self.assertIn('t("tag.env")', APP_JS)
        self.assertIn('t("tag.ego_intent")', APP_JS)
        self.assertIn('t("tag.scene")', APP_JS)
        self.assertIn('t("tag.trigger")', APP_JS)
        self.assertIn('t("tag.false_trigger")', APP_JS)
        self.assertIn('t("tag.should_trigger")', APP_JS)
        self.assertIn('t("tag.correct_trigger")', APP_JS)
        self.assertIn('"tag.env": "环境"', APP_JS)
        self.assertIn('"tag.ego_intent": "自车意图"', APP_JS)
        self.assertIn('"tag.false_trigger": "误触发"', APP_JS)
        self.assertIn(
            ".review-tag-groups { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 5px;",
            STYLES_CSS,
        )
        self.assertIn(".review-tag-dropdown > summary", STYLES_CSS)
        self.assertIn('id="reviewTagCreateDialog"', INDEX_HTML)
        self.assertIn('id="reviewTagCreateForm"', INDEX_HTML)
        self.assertIn('id="reviewTagCreateMode"', INDEX_HTML)
        self.assertIn("function openReviewTagEditorDialog", APP_JS)
        self.assertIn('mode: "edit"', APP_JS)
        self.assertIn("openDialog(\"reviewTagCreateDialog\")", APP_JS)
        self.assertIn("class=\"tag-group-trailing\"", APP_JS)
        self.assertIn("class=\"tag-group-chevron\"", APP_JS)
        self.assertNotIn('window.prompt("场景标签标题"', APP_JS)
        self.assertIn('id="missingEvidenceCreateDialog"', INDEX_HTML)
        self.assertIn("function openMissingEvidenceEditorDialog", APP_JS)
        self.assertIn("left: -1px; right: -1px; z-index: 22", STYLES_CSS)
        self.assertIn("display: grid; grid-template-columns: minmax(0, 1fr); gap: 4px", STYLES_CSS)
        self.assertIn("width: 100%; min-width: 0; max-width: 100%; justify-content: flex-start", STYLES_CSS)
        self.assertNotIn("grid-template-columns: repeat(2, minmax(min-content, max-content))", STYLES_CSS)
        self.assertNotIn(".review-tag-dropdown .review-tag-options .tag-option:last-child:nth-child(odd)", STYLES_CSS)
        self.assertNotIn("width: max-content; min-width: calc(100% + 2px); max-width: min(320px, calc(100vw - 24px))", STYLES_CSS)
        self.assertNotIn(".review-tag-groups > .review-tag-dropdown:nth-child(2) .review-tag-options", STYLES_CSS)
        self.assertNotIn('class="custom-tag-create"', APP_JS)
        self.assertNotIn(".custom-tag-create { position: sticky;", STYLES_CSS)
        self.assertIn("overflow: hidden; text-overflow: ellipsis; white-space: nowrap;", STYLES_CSS)
        self.assertIn("text-overflow: ellipsis; white-space: nowrap;", STYLES_CSS)
        self.assertIn('textarea id="annotationNote" rows="2" aria-keyshortcuts="E Escape Enter Shift+Enter"', APP_JS)
        self.assertIn('class="review-reason-shortcuts"', APP_JS)
        self.assertIn('<kbd>E</kbd> 聚焦 · <kbd>⇧ Enter</kbd> 换行', APP_JS)
        self.assertIn('id="reviewSaveButton" type="submit" aria-keyshortcuts="Enter"', APP_JS)
        self.assertIn('class="review-save-shortcut" aria-hidden="true">Enter</kbd>', APP_JS)
        self.assertIn(".review-reason-shortcuts kbd {", STYLES_CSS)
        self.assertIn(".review-save-shortcut {", STYLES_CSS)
        self.assertIn("function bindReviewComposerShortcuts", APP_JS)
        self.assertIn('String(event.key || "").toLowerCase() !== "e"', APP_JS)
        self.assertIn("closeAllReviewDropdowns();\n    composer.focus", APP_JS)
        self.assertIn('event.key === "Enter" && !event.shiftKey && !state.savingAnnotation', APP_JS)
        self.assertIn('form.requestSubmit($("#reviewSaveButton") || undefined)', APP_JS)
        self.assertIn('$("#annotationNote")?.blur();', APP_JS)
        self.assertIn('data-shortcut-search="e escape"', INDEX_HTML)
        self.assertIn('data-shortcut-search="enter shift+enter"', INDEX_HTML)
        self.assertIn('id="reviewHistoryLaunchButton"', APP_JS)
        self.assertIn('<span class="ui-lang-zh">历史 · ${allAnnotations.length}</span>', APP_JS)
        self.assertIn('<span class="ui-lang-en">History · ${allAnnotations.length}</span>', APP_JS)
        self.assertIn('aria-keyshortcuts="J"', APP_JS)
        self.assertIn('id="modelHistoryLaunchButton"', APP_JS)
        self.assertIn('aria-keyshortcuts="M"', APP_JS)
        self.assertIn('id="reviewCommentsButton"', APP_JS)
        self.assertIn('<span class="ui-lang-zh">讨论</span><span class="ui-lang-en">Discussion</span>', APP_JS)
        self.assertNotIn("多人盲标进行中，评论将在解盲后恢复。", APP_JS)
        self.assertNotIn('if (state.selectedCase?.review_assignment?.blind_active) return;', APP_JS)
        self.assertIn('aria-keyshortcuts="D"', APP_JS)
        self.assertIn("function bindReviewDetailActionShortcuts", APP_JS)
        self.assertIn('if (key === "d")', APP_JS)
        self.assertIn("openCurrentReviewDiscussion(state.selectedCase)", APP_JS)
        self.assertIn('const kind = key === "j" ? "review" : key === "m" ? "model" : "";', APP_JS)
        self.assertIn('toggleHistoryDialog(kind, state.selectedCase)', APP_JS)
        self.assertIn("function toggleHistoryDialog(kind, caseData)", APP_JS)
        self.assertIn("const wasOpen = dropdown.open", APP_JS)
        self.assertNotIn("reviewBlindTaskStatus", APP_JS)
        self.assertNotIn('class="review-blind-task-banner"', APP_JS)
        self.assertNotIn(".review-blind-task-banner", STYLES_CSS)
        self.assertIn('String(annotation.author || "").trim().toLowerCase() === currentUser', APP_JS)
        self.assertIn('?include_media=false&model_run_id=', APP_JS)
        self.assertIn('data-shortcut-search="d"', INDEX_HTML)
        self.assertIn('data-shortcut-search="j m"', INDEX_HTML)
        self.assertIn("function reviewWorkSplitBinding", APP_JS)
        self.assertIn("work_split_id: reviewWorkSplitBinding(state.selectedCase)", APP_JS)
        self.assertIn("const workSplitId = reviewWorkSplitBinding(caseData)", APP_JS)
        self.assertNotIn('review_assignment?.mode === "blind"', APP_JS)
        self.assertIn('if (!assignment?.assigned) return "";', APP_JS)
        self.assertIn('assignment?.mode !== "blind" && assignment?.purpose !== "model_review"', APP_JS)
        self.assertIn('String(annotation.work_split_id || "").trim() === workSplitId', APP_JS)
        self.assertIn('data-copy-issue-id', APP_JS)
        self.assertIn("async function copyReviewIssueId", APP_JS)
        self.assertIn("navigator.clipboard?.writeText", APP_JS)
        self.assertIn("已复制 Issue ID", APP_JS)
        self.assertIn(".detail-copy-id-button", STYLES_CSS)
        self.assertIn(".model-error-section > .review-section-heading h2 { white-space: nowrap; }", STYLES_CSS)
        self.assertIn(".model-error-section > .review-section-heading {\n  flex-wrap: nowrap;", STYLES_CSS)
        self.assertIn("flex: 1 1 auto;\n  flex-wrap: nowrap;\n  margin-left: auto;", STYLES_CSS)
        self.assertIn(".model-error-section > .review-section-heading { align-items: flex-start; flex-wrap: wrap; }", STYLES_CSS)
        self.assertIn(".model-error-section .review-heading-actions .history-inline-button", STYLES_CSS)
        self.assertIn("min-height: 30px; padding: 5px 8px; gap: 4px; font-size: 11px", STYLES_CSS)
        self.assertIn(".detail-context-row { min-width: 0; display: flex; align-items: center; flex-wrap: nowrap; gap: 6px", STYLES_CSS)
        self.assertIn("flex: 1 1 auto; flex-wrap: nowrap; gap: 5px", STYLES_CSS)
        self.assertIn(".detail-context-actions { width: 100%; flex-basis: 100%; justify-content: flex-start; }", STYLES_CSS)
        self.assertIn("min-width: 132px; max-width: 148px", STYLES_CSS)
        self.assertIn(".review-reason textarea { min-height: 54px; height: 54px;", STYLES_CSS)
        self.assertIn(".review-section { display: grid; gap: 7px; padding: 0; border: 0", STYLES_CSS)
        self.assertIn('data-open-review-tag-creator', APP_JS)
        # All six managed Issue-tag axes render the ＋ create control.
        self.assertIn('class="tag-catalog-add-button"', APP_JS)
        self.assertIn("function reviewTagGroupLabel", APP_JS)
        self.assertIn('key === "false_trigger"', APP_JS)
        self.assertIn('key === "true_trigger"', APP_JS)
        self.assertIn('key === "ra"', APP_JS)
        self.assertIn('key === "no_assist"', APP_JS)
        self.assertIn("暂无标签，点 ＋ 添加", APP_JS)
        self.assertIn("REVIEW_TAG_MANAGED_GROUPS", main_py)
        self.assertIn('"false_trigger": "interaction_decision"', main_py)
        self.assertIn('"ra": "egress"', main_py)
        self.assertIn("tag-option-menu-toggle", APP_JS)
        self.assertIn("data-tag-menu-toggle", APP_JS)
        self.assertIn("function closeAllTagOptionMenus", APP_JS)
        self.assertIn("function positionTagOptionMenuPanel", APP_JS)
        self.assertIn("function resetTagOptionMenuPanel", APP_JS)
        self.assertIn("is-drop-up", APP_JS)
        self.assertIn("is-fixed-menu", APP_JS)
        self.assertIn(".tag-option-menu-panel.is-drop-up", STYLES_CSS)
        self.assertIn(".tag-option-menu-panel.is-fixed-menu", STYLES_CSS)
        self.assertIn('scheduleAnalysisFilterReload', APP_JS)
        self.assertNotIn('<button class="button button-primary" type="submit">应用</button>', INDEX_HTML)
        self.assertIn(".tag-catalog-add-button", STYLES_CSS)
        self.assertIn(".tag-option-menu-panel", STYLES_CSS)
        self.assertIn(".tag-option-with-menu", STYLES_CSS)
        self.assertIn('api("/api/review-tags"', APP_JS)
        self.assertIn('"key": "environment_other"', main_py)

    def test_review_dropdowns_close_when_focus_leaves_the_control(self) -> None:
        self.assertIn("function closeAllReviewDropdowns", APP_JS)
        self.assertIn("function positionReviewDropdownPanel", APP_JS)
        self.assertIn("function prepareReviewDropdownPanelForMeasure", APP_JS)
        self.assertIn("const desiredHeight = Math.min(naturalH, Math.floor(vh * 0.55), 420);", APP_JS)
        self.assertIn("spaceBelow < desiredHeight && spaceAbove > spaceBelow", APP_JS)
        self.assertIn("function prepareTagOptionMenuPanelForMeasure", APP_JS)
        self.assertIn("is-positioned", APP_JS)
        self.assertIn(":not(.is-positioned)", STYLES_CSS)
        # Place in the same tick as open — no rAF that paints absolute-down first.
        self.assertIn("prepareReviewDropdownPanelForMeasure(panel);\n      positionReviewDropdownPanel(dropdown);", APP_JS)
        self.assertIn("prepareTagOptionMenuPanelForMeasure(panel);\n        positionTagOptionMenuPanel(menu);", APP_JS)
        self.assertIn('summary?.addEventListener(\n      "pointerdown"', APP_JS)
        self.assertIn(".tag-option-menu-panel:not([hidden]):not(.is-positioned)", STYLES_CSS)

        self.assertIn("function resetReviewDropdownPanel", APP_JS)
        self.assertIn("is-fixed-dropdown", APP_JS)
        self.assertIn(".is-fixed-dropdown", STYLES_CSS)
        evidence_start = APP_JS.index('class="evidence-dropdown review-dropdown review-tag-dropdown"')
        evidence_end = APP_JS.index('id="missingEvidenceOptions"', evidence_start)
        evidence_header = APP_JS[evidence_start:evidence_end]
        self.assertIn('data-open-missing-evidence-creator', evidence_header)
        self.assertLess(
            evidence_header.index('data-open-missing-evidence-creator'),
            evidence_header.index('id="evidenceSummaryCount"'),
        )

        self.assertIn("function bindReviewDropdownDismiss", APP_JS)
        self.assertIn("reviewDropdownDismissBound", APP_JS)
        self.assertIn('target?.closest(".review-dropdown")', APP_JS)
        self.assertIn('if (event.key !== "Escape") return;', APP_JS)
        self.assertIn('if (active?.closest(".review-dropdown")) active.blur();', APP_JS)

    def test_review_save_updates_history_and_reconciles_filtered_queue(self) -> None:
        save_start = APP_JS.index("async function saveAnnotation(event)")
        save_end = APP_JS.index("\nfunction mediaFrames", save_start)
        save_body = APP_JS[save_start:save_end]
        self.assertIn("updateReviewHistory(state.selectedCase)", save_body)
        self.assertIn("await refreshReviewAfterSave(navigationContext)", save_body)
        self.assertNotIn("selectCase(", save_body)

    def test_review_catalog_creator_buttons_keep_the_compact_summary_order(self) -> None:
        evidence_start = APP_JS.index('class="evidence-dropdown review-dropdown review-tag-dropdown"')
        evidence_end = APP_JS.index('id="missingEvidenceOptions"', evidence_start)
        evidence_header = APP_JS[evidence_start:evidence_end]
        self.assertLess(
            evidence_header.index('data-open-missing-evidence-creator'),
            evidence_header.index("</summary>"),
        )
        self.assertIn(".review-tag-dropdown > summary .tag-catalog-add-button", STYLES_CSS)
        self.assertIn('target?.closest(".tag-catalog-add-button")', APP_JS)
        self.assertIn('if (target?.closest(".tag-catalog-add-button")) event.preventDefault();', APP_JS)

    def test_missing_evidence_creation_uses_shared_catalog_and_hint(self) -> None:
        self.assertIn('id="missingEvidenceCreateHint"', INDEX_HTML)
        self.assertIn('api("/api/missing-evidence"', APP_JS)
        self.assertNotIn("创建后所有用户、所有 Issue 都可见", APP_JS)
        self.assertIn("function missingEvidenceOptionMarkup", APP_JS)
        self.assertIn('data-edit-missing-evidence=', APP_JS)
        self.assertIn('data-delete-missing-evidence=', APP_JS)
        self.assertIn('data-open-missing-evidence-creator', APP_JS)
        self.assertIn("tag-option-with-menu evidence-tag-option", APP_JS)
        self.assertIn('method: "PUT"', APP_JS)
        self.assertIn('method: "DELETE"', APP_JS)
        self.assertIn("loadConfig()", APP_JS[APP_JS.index("async function refreshChangedData"):])
        self.assertIn(".evidence-option-deleted", STYLES_CSS)

    def test_review_mutations_acknowledge_server_revision_and_keep_form_dom(self) -> None:
        self.assertIn("function acknowledgeLocalChange(payload)", APP_JS)
        self.assertIn("acknowledgeLocalChange(result)", APP_JS)
        delete_start = APP_JS.index("async function deleteAnnotationVersion")
        delete_end = APP_JS.index("\nfunction renderReview", delete_start)
        delete_body = APP_JS[delete_start:delete_end]
        self.assertIn("syncReviewFormFromCase(caseData)", delete_body)
        self.assertNotIn("renderReview(caseData)", delete_body)

    def test_remote_review_change_does_not_repaint_static_review_pages(self) -> None:
        self.assertIn("function sharedChangeNeedsRefresh(topics)", APP_JS)
        self.assertIn('if (changed.has("review")) state.reviewQueueStale = true;', APP_JS)
        self.assertIn('state.activePage === "analysis"', APP_JS)
        self.assertIn("sharedChangeNeedsRefresh(data.topics)", APP_JS)
        self.assertIn('query.set("since_revision", String(state.changeRevision))', APP_JS)

    def test_review_history_exposes_explicit_delete_action(self) -> None:
        self.assertIn('data-delete-annotation="${escapeHtml(annotation.id)}"', APP_JS)
        self.assertIn('method: "DELETE"', APP_JS)
        self.assertIn("deleteAnnotationVersion(caseData", APP_JS)
        self.assertIn(".history-delete-button", STYLES_CSS)

    def test_review_gallery_exports_the_complete_current_filter(self) -> None:
        self.assertIn('id="exportFilteredIssuesButton"', INDEX_HTML)
        self.assertIn("导出当前筛选", INDEX_HTML)
        self.assertIn("function currentReviewGalleryExportParams", APP_JS)
        self.assertIn('gallery_scope: "true"', APP_JS)
        self.assertIn("payload.work_assignee = joinFilterList", APP_JS)
        self.assertIn("function downloadFilteredReviewIssues", APP_JS)
        self.assertIn('Export selection · ${total}', APP_JS)
        self.assertNotIn("data-export-current-issue", APP_JS)

    def test_adjacent_review_navigation_preserves_scroll_position(self) -> None:
        self.assertIn("const preserveScrollY = window.scrollY;", APP_JS)
        self.assertIn("preserveScrollY,", APP_JS)
        self.assertIn("preserveScroll: preservedScrollY !== null", APP_JS)
        self.assertIn('if (!preserveScroll && (target !== "review" || issue))', APP_JS)
        self.assertIn('window.scrollTo({ top: preservedScrollY, behavior: "auto" })', APP_JS)

    def test_reviewer_filter_survives_top_bar_and_collaboration_refresh(self) -> None:
        self.assertIn("function reviewerFilterSelection(page)", APP_JS)
        self.assertIn("function persistReviewerFilterRoute(page, values)", APP_JS)
        self.assertIn("function reviewerFilterSelections()", APP_JS)
        self.assertIn("function reviewerOptionsWithSelected(options, selected)", APP_JS)
        self.assertIn("Current filter", APP_JS)
        # Persist the active custom-filter selection before the asynchronous
        # facet reload so an Issue detail URL retains reviewer=jasperchen.
        self.assertIn('persistReviewerFilterRoute("review", values)', APP_JS)
        self.assertIn('persistReviewerFilterRoute("analysis", values)', APP_JS)
        self.assertIn('reviewerFilterSelection("review")', APP_JS)
        self.assertIn('reviewerFilterSelection("analysis")', APP_JS)
        self.assertIn("const reviewerSelections = typeof reviewerFilterSelections", APP_JS)
        self.assertIn("loadReviewers(reviewerSelections)", APP_JS)
        # A deliberately empty Run picker is a real filter state.  Refreshing
        # must not silently switch to the default Run and replace its reviewer
        # facet with a different set of names.
        self.assertIn("await loadRuns({ preserveEmpty: !state.selectedRunId });", APP_JS)
        self.assertIn("const analysisReviewerOptions = reviewerOptionsFor(", APP_JS)
        self.assertIn("Array.isArray(data.analysis_items)", APP_JS)

    def test_review_filters_reach_url_before_debounced_reload(self) -> None:
        self.assertIn("function persistCurrentReviewRoute(overrides = {})", APP_JS)
        schedule_start = APP_JS.index("function scheduleReviewFilterReload")
        schedule_end = APP_JS.index("\nfunction bindEvents", schedule_start)
        schedule_body = APP_JS[schedule_start:schedule_end]
        self.assertIn(
            'persistCurrentReviewRoute({ issue: "", issueIds: [], casePage: 1 });',
            schedule_body,
        )
        self.assertLess(
            schedule_body.index("persistCurrentReviewRoute"),
            schedule_body.index("window.setTimeout"),
        )

    def test_analysis_multi_filter_stays_open_during_same_page_reload(self) -> None:
        self.assertIn("const previousPage = state.activePage;", APP_JS)
        self.assertIn(
            'if (target === "analysis" && (previousPage !== "analysis" || restoreRoute))',
            APP_JS,
        )
        self.assertIn("keep it open for consecutive selections", APP_JS)
        self.assertIn('document.addEventListener("click", () => closeAllMultiFilters())', APP_JS)
        self.assertIn('if (event.key === "Escape") {\n      closeAllMultiFilters();', APP_JS)

    def test_historical_spotcheck_tags_only_prefill_unsaved_reviews(self) -> None:
        self.assertIn("function currentReviewSourceSuggestion", APP_JS)
        self.assertIn("issue_tag_suggestion", APP_JS)
        self.assertIn("currentReviewSourceSuggestion(caseData)?.annotation", APP_JS)
        self.assertIn("function issueTagSourceSuggestionMarkup", APP_JS)
        self.assertIn("历史抽检预填", APP_JS)
        self.assertIn("保存后才会创建新的 Review 版本", APP_JS)
