"""Frontend runs source contracts; original assertions preserved."""
import unittest
from frontend_contract_fixtures import APP_JS, APP_PY_RUN_COLLECTIONS_DB, INDEX_HTML, Path, RUN_COLLECTION_JS, RUN_COMPARISON_JS, STATIC_DIR, STYLES_CSS


class FrontendRunsContractTest(unittest.TestCase):
    def test_read_only_run_comparison_is_visible_shareable_and_review_linked(self) -> None:
        self.assertIn('id="runComparisonNavButton"', INDEX_HTML)
        self.assertIn('data-page="comparison"', INDEX_HTML)
        self.assertNotIn('class="compact-page-lead run-comparison-lead"', INDEX_HTML)
        self.assertNotIn('查看模型结果', INDEX_HTML)
        self.assertIn('runComparisonNav.hidden = false', APP_JS)
        self.assertNotIn('Run 对比仅对管理员开放。', APP_JS)
        self.assertNotIn('Run 对比仅限管理员。', APP_JS)
        self.assertIn('path: "/run-comparison"', APP_JS)
        self.assertIn('api(`/api/model-run-comparison?', APP_JS)
        self.assertIn('url.searchParams.set("baseline_run"', APP_JS)
        self.assertIn('url.searchParams.set("candidate_run"', APP_JS)
        self.assertIn('url.searchParams.set("issue", String(issueId))', APP_JS)
        self.assertIn('url.searchParams.set("run", String(runId))', APP_JS)
        self.assertIn('url.searchParams.set("comparison", "all")', APP_JS)
        self.assertIn("Run Prompt / 输入配置", INDEX_HTML)
        self.assertIn('id="comparisonRunDiff"', INDEX_HTML)
        self.assertIn('class="case-pagination gallery-pagination comparison-pagination"', INDEX_HTML)
        self.assertIn('id="comparisonPageJump"', INDEX_HTML)
        self.assertIn('id="comparisonPageJumpButton"', INDEX_HTML)
        self.assertIn('id="comparisonGtReference"', INDEX_HTML)
        self.assertIn("payload.gt_references", RUN_COMPARISON_JS)
        self.assertIn('$("#comparisonGtReference")', RUN_COMPARISON_JS)
        self.assertIn("async function jumpToRunComparisonPage", APP_JS)
        self.assertIn('event.key === "Enter"', APP_JS)
        self.assertIn('event.key === "Escape"', APP_JS)
        self.assertIn('loadRunComparison({ historyMode: "push" })', APP_JS)
        self.assertIn(".run-comparison-page {\n  gap: 8px;\n  font-size: 12px;", STYLES_CSS)
        self.assertIn(".comparison-case-table th,\n.comparison-case-table td {", STYLES_CSS)
        self.assertIn("text-align: center;\n  vertical-align: middle;", STYLES_CSS)
        self.assertIn("justify-items: center;", STYLES_CSS)
        self.assertIn(".comparison-transition-filter {\n  display: flex;\n  flex-wrap: wrap;\n  justify-content: flex-end;", STYLES_CSS)
        self.assertLess(
            INDEX_HTML.index('id="comparisonTransitionFilter"'),
            INDEX_HTML.index('id="comparisonSearchInput"'),
        )
        self.assertIn('class="comparison-search"><span>Issue ID / reason</span>', INDEX_HTML)
        self.assertIn('id="comparisonGtFilter"', INDEX_HTML)
        self.assertIn('id="comparisonBaselineLabelFilter"', INDEX_HTML)
        self.assertIn('id="comparisonCandidateLabelFilter"', INDEX_HTML)
        self.assertIn('<option value="NONE">NONE / 无输出</option>', INDEX_HTML)
        self.assertIn('id="comparisonLabelChangeFilter"', INDEX_HTML)
        self.assertIn('id="comparisonResetFilters"', INDEX_HTML)
        self.assertIn('gt_label: state.runComparison.gtLabel', APP_JS)
        self.assertIn('baseline_label: state.runComparison.baselineLabel', APP_JS)
        self.assertIn('candidate_label: state.runComparison.candidateLabel', APP_JS)
        self.assertIn('label_change: state.runComparison.labelChange', APP_JS)
        self.assertIn('run?.baseline_prediction_count || 0', APP_JS)
        self.assertIn('if (repairCoverage && selectedCoverage <= 0 && covered.length)', APP_JS)
        self.assertIn('id="comparisonBaselineRunPicker"', INDEX_HTML)
        self.assertIn('id="comparisonCandidateRunPicker"', INDEX_HTML)
        self.assertIn('class="ui-select-native" id="comparisonBaselineRun"', INDEX_HTML)
        self.assertIn('class="ui-select-native" id="comparisonCandidateRun"', INDEX_HTML)
        self.assertIn('renderRunComparisonSelectors({ repairCoverage: true })', APP_JS)
        self.assertIn('function renderRunComparisonSelectors({ repairCoverage = false }', APP_JS)
        self.assertIn('async function selectRunComparisonRun(side, runId)', APP_JS)
        self.assertIn('applyInferredBaselinesFromRun(run, { reason: "run" })', APP_JS)
        self.assertIn('selectRunComparisonRun("baseline", event.target.value)', APP_JS)
        self.assertIn('selectRunComparisonRun("candidate", event.target.value)', APP_JS)
        self.assertIn('不选择（单 Run 查看）', APP_JS)
        self.assertIn('payload.view_mode === "single"', APP_JS)
        self.assertIn('single ? "Case 明细" : "Case 变化明细"', APP_JS)
        self.assertIn('baseline:a?.extra_inputs,candidate:b?.extra_inputs', APP_JS)
        self.assertIn('dialog.classList.toggle("is-single-run", single)', APP_JS)
        self.assertIn('.comparison-reason-dialog.is-single-run .comparison-reason-grid', STYLES_CSS)
        self.assertIn('$("#comparisonTransitionFilter").hidden = single', APP_JS)
        self.assertIn('$("#comparisonBaselineOutputHeading").hidden = !payload.baseline_run', APP_JS)
        self.assertIn('$("#comparisonCandidateOutputHeading").hidden = !payload.candidate_run', APP_JS)
        self.assertIn('state.runComparison.inputFilter.run = payload.candidate_run ? "candidate" : "baseline"', APP_JS)
        self.assertIn('请至少选择一个有效 Run', APP_JS)
        self.assertIn('无当前数据集输出的一侧将显示为 NONE', APP_JS)
        self.assertIn('pageSize: 10', APP_JS)
        self.assertIn('<option selected>10</option>', INDEX_HTML)
        self.assertIn('comparison-prediction-verdict comparison-chip', APP_JS)
        self.assertIn('.run-comparison-page [hidden] {\n  display: none !important;', STYLES_CSS)
        self.assertIn('.comparison-results.is-single-run .comparison-case-table {', STYLES_CSS)
        self.assertIn('.comparison-results.is-single-run .comparison-extra-inputs {', STYLES_CSS)
        self.assertIn('align-content: center;\n  justify-items: center;\n  text-align: center;', STYLES_CSS)
        self.assertIn('.comparison-prediction-verdict {', STYLES_CSS)
        self.assertIn('comparison-match" : "comparison-mismatch', APP_JS)
        self.assertNotIn('comparison-prediction-side', APP_JS)
        self.assertNotIn('.comparison-prediction-candidate', STYLES_CSS)
        self.assertIn('class="comparison-output-label">${escapeHtml(label)}</strong>', APP_JS)
        self.assertIn('<strong>${escapeHtml(item.gt_label || "—")}</strong>', APP_JS)
        self.assertNotIn('${labelBadge(label, "NONE")}', RUN_COMPARISON_JS)
        self.assertNotIn('${labelBadge(item.gt_label, "—")}', RUN_COMPARISON_JS)
        self.assertIn('.comparison-gt-summary > strong', STYLES_CSS)
        self.assertIn('.comparison-output-label {', STYLES_CSS)
        self.assertNotIn('.comparison-gt-summary .label-badge', STYLES_CSS)
        self.assertNotIn('.comparison-prediction-output .label-badge', STYLES_CSS)
        self.assertIn('align-content: center;\n  justify-items: center;', STYLES_CSS)
        self.assertIn('justify-content: center;\n  flex-wrap: wrap;', STYLES_CSS)
        self.assertIn('.comparison-prediction.is-error {', STYLES_CSS)
        self.assertIn('background: var(--raised);', STYLES_CSS)
        self.assertIn('data-comparison-row', APP_JS)
        self.assertNotIn('data-comparison-reason', APP_JS)
        self.assertIn('event.target.closest("a, button, input, select, textarea")', APP_JS)
        self.assertIn('!["Enter", " "].includes(event.key)', APP_JS)
        self.assertNotIn('点击整行打开 Case 对比', APP_JS)
        self.assertIn('const savedReason = String(prediction?.model_reason || "").trim()', APP_JS)
        self.assertIn('comparison-prediction-reason${savedReason ? " has-saved-reason" : " is-empty"}', APP_JS)
        self.assertIn('.comparison-prediction-reason {', STYLES_CSS)
        self.assertIn('.comparison-prediction-reason.is-empty { color: var(--muted); }', STYLES_CSS)
        self.assertNotIn('cursor: help;', (STATIC_DIR / "css/comparison.css").read_text(encoding="utf-8"))
        self.assertIn('overflow-wrap: anywhere;\n  word-break: break-word;', STYLES_CSS)
        self.assertIn('.comparison-transition-badge.p2p {', STYLES_CSS)
        self.assertIn('.comparison-transition-badge.f2f {', STYLES_CSS)
        self.assertIn('--transition-from: #f87171;\n  --transition-to: #34d399;', STYLES_CSS)
        self.assertIn('--transition-from: #34d399;\n  --transition-to: #f87171;', STYLES_CSS)
        self.assertIn('comparison-inline-review', APP_JS)
        self.assertIn('straight_road: "直行"', APP_JS)
        self.assertIn('grid-template-rows: auto minmax(28px, auto) 26px;', STYLES_CSS)
        self.assertIn('height: 26px !important;', STYLES_CSS)
        self.assertIn('padding: 0 8px !important;', STYLES_CSS)
        self.assertIn('id="comparisonInputFilter"', INDEX_HTML)
        self.assertIn('input_filter: JSON.stringify', APP_JS)
        self.assertIn('function positionComparisonInputFilter()', APP_JS)
        self.assertIn('window.requestAnimationFrame(positionComparisonInputFilter)', APP_JS)
        self.assertIn('overflow-x: hidden;', STYLES_CSS)
        self.assertIn('.comparison-case-table { min-width:0; width:100%; }', STYLES_CSS)
        self.assertIn('margin-top: 10px;', STYLES_CSS)
        self.assertIn('background: color-mix(in srgb, var(--overlay) 72%, var(--raised));', STYLES_CSS)
        self.assertIn('border-radius: 8px;', STYLES_CSS)
        self.assertIn('comparisonSceneTagsHtml(item.scene_review)', APP_JS)
        self.assertIn('comparisonExtraInputsHtml(item.extra_inputs)', APP_JS)
        self.assertIn('id="mediaComparisonExtraInputs"', INDEX_HTML)
        self.assertIn('function comparisonExtraInputFrameHtml(extraInputs, offsetMs)', APP_JS)
        self.assertIn('comparison_extra_inputs:comparisonMediaExtraInputs(issueId)', APP_JS)
        self.assertIn('comparisonExtraInputs: caseData?.comparison_extra_inputs || null', APP_JS)
        self.assertIn('comparisonExtraInputFrameHtml(snapshot.comparisonExtraInputs, offsetMs)', APP_JS)
        self.assertIn('.media-comparison-extra-inputs {', STYLES_CSS)
        self.assertIn('function openComparisonReasonDialog(issueId, { preserveTab = false } = {})', APP_JS)
        self.assertIn('renderComparisonReasonSide("Baseline", item.baseline', APP_JS)
        self.assertIn('renderComparisonReasonSide("Candidate", item.candidate', APP_JS)
        self.assertIn('id="comparisonReasonDialog"', INDEX_HTML)
        self.assertIn('id="comparisonReasonBaselineBody"', INDEX_HTML)
        self.assertIn('id="comparisonReasonCandidateBody"', INDEX_HTML)
        self.assertIn('class="comparison-reason-grid"', INDEX_HTML)
        self.assertIn('aria-keyshortcuts="ArrowUp ArrowDown"', INDEX_HTML)
        self.assertIn('class="comparison-case-shortcuts"', INDEX_HTML)
        self.assertIn("function navigateComparisonCaseDialog(delta)", APP_JS)
        self.assertIn('loadRunComparison({ historyMode: "replace" })', APP_JS)
        self.assertIn('openComparisonReasonDialog(next.issue_id, { preserveTab: true })', APP_JS)
        self.assertIn('comparisonCaseActive &&', APP_JS)
        self.assertIn('.comparison-reason-content p', STYLES_CSS)

    def test_run_collection_export_and_issue_ids_respect_base_path_and_wrap(self) -> None:
        self.assertIn('withBase(`/api/run-evaluations/${encodeURIComponent(payload.id)}/export`)', APP_JS)
        self.assertIn('overflow-wrap:anywhere; word-break:break-word;', STYLES_CSS)

    def test_run_collection_dedicated_route_and_read_only_contract(self) -> None:
        self.assertNotIn('id="runCollectionsNavButton"', INDEX_HTML)
        self.assertIn('id="runCollectionsPage"', INDEX_HTML)
        self.assertIn('path: "/multi-run-evaluation"', APP_JS)
        self.assertIn('pathname === "/run-collections"', APP_JS)
        self.assertIn('? "run-collections"', APP_JS)
        self.assertIn("ensureRunCollectionsDedicatedPage", APP_JS)
        self.assertNotIn('id="runCollectionPairwiseDetails"', INDEX_HTML)
        self.assertIn("applyRunCollectionReadOnlyGating", APP_JS)
        self.assertIn("state.session?.is_admin && state.session?.verified", APP_JS)
        self.assertIn('id="runCollectionReadonlyNote"', INDEX_HTML)

    def test_run_collection_evaluation_contract_exposes_shared_label_and_provenance(self) -> None:
        self.assertIn("Shared label state", RUN_COLLECTION_JS)
        self.assertIn("scope_snapshots", RUN_COLLECTION_JS)
        self.assertIn("reference_ids", RUN_COLLECTION_JS)
        self.assertIn('id="runCollectionLabelReferenceSet"', INDEX_HTML)
        self.assertIn("supported_coverage", RUN_COLLECTION_JS)
        self.assertIn("pairwise_union_denominator", RUN_COLLECTION_JS)
        self.assertIn("reference-set:", APP_PY_RUN_COLLECTIONS_DB)
        self.assertNotIn('<option value="run">Run prediction snapshot</option>', INDEX_HTML)

    def test_run_collection_evaluation_hidden_attribute_wins_over_grid(self) -> None:
        self.assertIn(".run-collection-evaluation[hidden]", STYLES_CSS)
        self.assertIn("display:none !important", STYLES_CSS)

    def test_stage1_true_stuck_has_explicit_comparison_contract(self) -> None:
        self.assertIn('const STAGE1_TRUE_STUCK_LABEL = "真实卡住"', APP_JS)
        self.assertIn('const MODEL_LABELS = [...LABELS, STAGE1_TRUE_STUCK_LABEL]', APP_JS)
        self.assertIn('function modelLabelMatchesGt(modelLabel, gtLabel)', APP_JS)
        self.assertIn('gtLabel === "正确触发" || gtLabel === "无需协助"', APP_JS)
        self.assertIn('modelLabelMatchesGt(cell.model_label, row.gt_label)', APP_JS)

    def test_model_runs_registry_has_url_restorable_pagination(self) -> None:
        self.assertIn('id="runManagerPagination"', INDEX_HTML)
        self.assertIn('id="runPagePrevious"', INDEX_HTML)
        self.assertIn('id="runPageNext"', INDEX_HTML)
        self.assertIn('id="runPageJump"', INDEX_HTML)
        self.assertIn('id="runPageSize"', INDEX_HTML)
        self.assertIn("function currentRunsRouteOptions", APP_JS)
        self.assertIn("function changeRunManagerPage", APP_JS)
        self.assertIn("function jumpToRunManagerPage", APP_JS)
        self.assertIn("function changeRunManagerPageSize", APP_JS)
        self.assertIn("state.runPage", APP_JS)
        self.assertIn("runsFilters: normalizedRunsRouteFilters(params)", APP_JS)
        self.assertIn('if (Number(runs.page) > 1)', APP_JS)

    def test_model_source_preview_supports_excel_files(self) -> None:
        app_root = Path(__file__).resolve().parents[1].joinpath("app")
        main_py = "\n".join(
            p.read_text(encoding="utf-8")
            for p in sorted(app_root.rglob("*.py"))
        )
        self.assertIn('preview_supported = suffix in {".json", ".csv", ".xlsx", ".xlsm"}', main_py)
        self.assertIn('if suffix not in {".json", ".csv", ".xlsx", ".xlsm"}:', main_py)
        self.assertIn("当前仅支持在页面内预览 CSV / JSON / XLSX", main_py)
        self.assertIn("CSV / JSON / XLSX 页面预览", APP_JS)
