"""Frontend integrations source contracts; original assertions preserved."""
import unittest
from frontend_contract_fixtures import APP_ENTRY_JS, APP_JS, INDEX_HTML, STATIC_DIR, STYLES_CSS


class FrontendIntegrationsContractTest(unittest.TestCase):
    def test_batch_gateway_aligns_to_form_and_catalog_scrolls(self) -> None:
        self.assertIn(".batch-page-grid { align-items: stretch; }", STYLES_CSS)
        self.assertIn(".batch-page-grid > .tool-form { align-self: start; }", STYLES_CSS)
        self.assertIn("height: auto; min-height: 0", STYLES_CSS)
        self.assertIn("contain: size; overflow: hidden", STYLES_CSS)
        self.assertIn("contain: none; overflow: visible", STYLES_CSS)
        self.assertIn("grid-template-rows: auto auto auto auto minmax(0, 1fr) auto", STYLES_CSS)
        self.assertIn("overscroll-behavior: contain; scrollbar-gutter: stable", STYLES_CSS)

    def test_batch_model_picker_uses_workspace_dropdown(self) -> None:
        self.assertIn('id="gatewayModelPicker"', INDEX_HTML)
        self.assertIn('id="gatewayModelPickerTrigger"', INDEX_HTML)
        self.assertIn('id="gatewayModelPickerPanel"', INDEX_HTML)
        self.assertIn('id="gatewayProviderPicker"', INDEX_HTML)
        self.assertIn('class="gateway-model-native-select"', INDEX_HTML)
        self.assertIn("data-gateway-picker-model", APP_JS)
        self.assertIn("bindGatewayModelPicker", APP_JS)
        self.assertIn("bindGatewayProviderPicker", APP_JS)
        self.assertIn("openAnchoredPanel", APP_JS)
        self.assertIn("gateway-model-picker-panel", STYLES_CSS)
        self.assertIn("gateway-model-picker-trigger", STYLES_CSS)
        self.assertIn("gateway-provider-picker-panel", STYLES_CSS)
        self.assertIn("width: max(100%, 200px)", STYLES_CSS)
        self.assertIn('title="${escapeHtml(title)}"', APP_JS)
        self.assertIn("focusMediaSurface", APP_JS)
        self.assertIn("kindSelect.blur()", APP_JS)
        self.assertIn("if (latest !== null) seekTo(latest)", APP_JS)
        self.assertIn("let queuedSeekTarget = null", APP_JS)
        self.assertIn("const queueSeek = (target, delay = 75)", APP_JS)
        self.assertIn("queuedSeekTarget !== null", APP_JS)
        self.assertIn('event.target.matches("[data-video-seek]")', APP_JS)
        self.assertIn("requestVideoFrameCallback", APP_JS)
        self.assertIn("window.requestAnimationFrame(() =>", APP_JS)
        self.assertIn('hasPreviousReview ? previous.missing_evidence || [] : []', APP_JS)
        self.assertNotIn('hasPreviousReview ? previous.missing_evidence || [] : ["routing_direction"]', APP_JS)

    def test_system_status_lead_keeps_only_refresh_actions(self) -> None:
        self.assertNotIn("只读查看服务、数据库、备份、容量与外部依赖", INDEX_HTML)
        self.assertNotIn("Read-only service, database, backup", INDEX_HTML)
        self.assertIn(".system-status-lead { min-height: 46px; justify-content: flex-end; }", STYLES_CSS)

    def test_intent_labeling_isolated_dynamic_timeline_contract(self) -> None:
        self.assertIn('id="intentLabelingNavButton" data-page-target="intent"', INDEX_HTML)
        self.assertIn('title="意图标注" hidden', INDEX_HTML)
        self.assertIn('intentLabelingNav.hidden = !canViewIntent', APP_JS)
        self.assertIn('localStorage.setItem("ra-triage-can-view-intent"', APP_JS)
        self.assertIn('const intentAccessResolved = typeof state.session.can_view_intent === "boolean"', APP_JS)
        self.assertIn('if (intentAccessResolved) {', APP_JS)
        self.assertIn('document.documentElement.dataset.canViewIntent === "true"', APP_JS)
        self.assertIn('html[data-can-view-intent="true"] #intentLabelingNavButton[hidden]', STYLES_CSS)
        self.assertIn('["users", "intent", "intent-experiments", "intent-summary"]', APP_JS)
        self.assertIn("意图标注仅对已授权标注人开放。", APP_JS)
        self.assertIn('data-page="intent"', INDEX_HTML)
        self.assertIn('path: "/intent-labeling"', APP_JS)
        self.assertIn('"intent-labeling.js"', APP_ENTRY_JS)
        self.assertIn("state.intentLabeling", APP_JS)
        self.assertIn("data-intent-aggregate-axis", INDEX_HTML)
        self.assertIn("data-intent-frame-axis", INDEX_HTML)
        self.assertIn("function intentRestoreBatchPrefill", APP_JS)
        self.assertIn("expected_revision_id: intent.revisionId", APP_JS)
        self.assertIn("savedEditVersion = intent.editVersion", APP_JS)
        self.assertIn("await intent.savePromise", APP_JS)
        self.assertIn("event.code", APP_JS)
        self.assertIn("INTENT_DIGIT_LABELS", APP_JS)
        self.assertIn("Digit7", APP_JS)
        self.assertIn("Digit8", APP_JS)
        self.assertIn("IntersectionObserver", APP_JS)
        self.assertIn("function intentLabelSummary", APP_JS)
        self.assertIn("function intentSetMediaZoom", APP_JS)
        self.assertIn("function openIntentMedia", APP_JS)
        self.assertIn('function intentMoveFrame(delta, { extendSelection = false, toBoundary = false } = {})', APP_JS)
        self.assertIn('extendSelection: event.shiftKey', APP_JS)
        self.assertIn('toBoundary: boundaryModifier', APP_JS)
        self.assertIn('intent.selectedTimepointIds = intentSelectionRange(anchorId, timepointId)', APP_JS)
        self.assertIn('const hasTargetOffset = offsetMs !== null && offsetMs !== undefined && offsetMs !== ""', APP_JS)
        self.assertIn('|| data.timepoints[0]', APP_JS)
        self.assertIn('selected.forEach((timepoint)', APP_JS)
        self.assertIn('ArrowUp: () => intentNavigateCase(-1)', APP_JS)
        self.assertIn('ArrowDown: () => intentNavigateCase(1)', APP_JS)
        self.assertNotIn('PageUp: () => intentNavigateCase(-1)', APP_JS)
        self.assertIn('KeyB: () => openIntentMedia("bev")', APP_JS)
        self.assertIn('KeyD: () => openIntentComments()', APP_JS)
        self.assertIn('id="intentOpenComments" type="button" aria-keyshortcuts="D"', INDEX_HTML)
        self.assertIn('data-intent-media-controls="camera"', INDEX_HTML)
        self.assertIn('data-intent-open-media="camera"', INDEX_HTML)
        self.assertIn('id="shortcutGuideDialog"', INDEX_HTML)
        self.assertIn('data-shortcut-guide-page="review"', INDEX_HTML)
        self.assertIn("function bindShortcutGuide", APP_JS)
        self.assertIn("function shortcutGuideKeyToken", APP_JS)
        self.assertIn("function filterShortcutGuide", APP_JS)
        self.assertIn('id="shortcutGuideSearchState"', INDEX_HTML)
        self.assertIn('id="shortcutGuideSearchClear"', INDEX_HTML)
        self.assertIn('data-shortcut-search="d"', INDEX_HTML)
        self.assertIn('dialog?.addEventListener("cancel"', APP_JS)
        self.assertIn("scrollbar-gutter: stable", STYLES_CSS)
        self.assertIn('active?.matches?.("#shortcutHelpButton, [data-open-shortcut-guide]")', APP_JS)
        self.assertIn(".media-decision-summary[hidden]", STYLES_CSS)
        self.assertIn('placeholder="例如 cn28896325"', INDEX_HTML)
        self.assertNotIn("data-intent-axis-mode", INDEX_HTML)
        self.assertNotIn("一次选择会填入全部时间点", INDEX_HTML)
        self.assertIn('aria-keyshortcuts="Shift+1"><kbd>⇧1</kbd>左转', INDEX_HTML)
        self.assertIn('aria-keyshortcuts="Shift+7"><kbd>⇧7</kbd>左变道', INDEX_HTML)
        self.assertIn('aria-keyshortcuts="Shift+8"><kbd>⇧8</kbd>右变道', INDEX_HTML)
        self.assertIn('aria-keyshortcuts="1"><kbd>1</kbd>左转', INDEX_HTML)
        self.assertIn('aria-keyshortcuts="7"><kbd>7</kbd>左变道', INDEX_HTML)
        self.assertIn('aria-keyshortcuts="8"><kbd>8</kbd>右变道', INDEX_HTML)
        self.assertIn('id="intentRestoreBatchPrefill" type="button" aria-keyshortcuts="0"', INDEX_HTML)
        self.assertIn('Space: () => openIntentMedia', APP_JS)
        self.assertIn("function cycleIntentMediaKind", APP_JS)
        self.assertIn("state.media.snapshot?.intentPreview && currentTimepointId && exactTimepointIndex < 0", APP_JS)
        self.assertIn('event.key === "ArrowLeft"', APP_JS)
        self.assertIn('event.key === "ArrowRight"', APP_JS)
        self.assertNotIn("模型建议", INDEX_HTML)
        self.assertNotIn('class="intent-card intent-shortcuts"', INDEX_HTML)
        self.assertIn('id="refreshButton" type="button" aria-keyshortcuts="R"', INDEX_HTML)
        self.assertIn("function bindGlobalRefreshShortcut", APP_JS)
        self.assertIn("function bindGlobalSidebarShortcut", APP_JS)
        self.assertIn('event.code !== "Backslash"', APP_JS)
        self.assertIn('id="sidebarToggle" type="button" aria-expanded="true" aria-keyshortcuts="Backslash"', INDEX_HTML)
        self.assertIn('<kbd class="sidebar-shortcut" aria-hidden="true">\\</kbd>', INDEX_HTML)
        self.assertIn("展开 / 折叠左侧工具栏", INDEX_HTML)
        self.assertIn('event.code !== "KeyR"', APP_JS)
        self.assertIn("if (event.shiftKey) intentSetAggregate", APP_JS)
        self.assertIn("else intentSetFrameLabel", APP_JS)
        self.assertIn("button.blur();", APP_JS)
        self.assertIn('class="sidebar-group-label sidebar-label system-group-label"><span class="ui-lang-zh">系统管理', INDEX_HTML)
        self.assertNotIn('class="nav-beta"', INDEX_HTML)
        self.assertIn('#openBatchPredictionButton { order: 7; }', STYLES_CSS)
        self.assertIn('body:is([data-active-page="intent"], [data-active-page="intent-experiments"], [data-active-page="intent-summary"]) .top-actions { min-width: 0; margin-left: auto; }', STYLES_CSS)
        self.assertIn('.ui-select-native { display: none !important;', STYLES_CSS)
        self.assertIn('data-page="intent-summary"', INDEX_HTML)
        self.assertIn('path: "/intent-summary"', APP_JS)
        self.assertIn('id="intentTopbarDatasetPicker" data-placeholder="选择数据集"', INDEX_HTML)
        self.assertNotIn('id="intentTopbarDatasetSelect"', INDEX_HTML)
        self.assertNotIn('id="intentDatasetSelect"', INDEX_HTML)
        self.assertNotIn('id="intentExperimentDatasetSelect"', INDEX_HTML)
        self.assertIn("grid-template-columns: minmax(210px, .9fr) 185px 185px 60px minmax(285px, 1.15fr) minmax(265px, 1fr)", STYLES_CSS)
        self.assertIn("grid-template-columns: minmax(0, 1fr) 280px", STYLES_CSS)
        self.assertIn('html[data-sidebar-pref="collapsed"] .intent-workspace { grid-template-columns: minmax(0, 1fr) 270px; }', STYLES_CSS)
        self.assertIn('html[data-sidebar-pref="collapsed"] .intent-timepoint { flex-basis: 148px; }', STYLES_CSS)
        self.assertIn(".intent-routing-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }", STYLES_CSS)
        self.assertIn("min-height: 34px", STYLES_CSS)
        self.assertIn('@media (min-width: 1251px) and (min-height: 700px)', STYLES_CSS)
        self.assertIn('body[data-active-page="intent"] .main { height: calc(100dvh - 44px); overflow: hidden; padding-bottom: 10px; }', STYLES_CSS)
        self.assertIn('.intent-labeling-page { height: 100%; min-height: 0; grid-template-rows: auto minmax(0, 1fr); }', STYLES_CSS)
        self.assertIn('.intent-main-column { height: 100%; min-height: 0; grid-template-rows: auto minmax(0, 1fr); }', STYLES_CSS)
        self.assertIn('.intent-label-rail { height: 100%; min-height: 0; grid-template-rows: repeat(4, max-content); overflow-y: auto;', STYLES_CSS)
        self.assertIn('id="intentAssigneeFilter"', INDEX_HTML)
        self.assertIn('id="intentAssignmentPicker"', INDEX_HTML)
        self.assertIn('id="intentAssignmentSelect"', INDEX_HTML)
        self.assertIn('id="intentTopbarDatasetPicker"', INDEX_HTML)
        # Intent discussions reuse the shared review discussion dialog; the
        # old intent-only modal must not be duplicated in the page.
        self.assertIn('id="analysisDiscussionDialog"', INDEX_HTML)
        self.assertNotIn('id="intentCommentDialog"', INDEX_HTML)
        self.assertIn("intentAssigneeSearchParams", APP_JS)
        self.assertIn('.intent-timepoint { height: 100%; min-height: 0; grid-template-rows: auto minmax(0, 1fr) auto; }', STYLES_CSS)
        self.assertIn("grid-template-rows: repeat(2, 76px)", STYLES_CSS)
        self.assertIn('id="intentExperimentHistoryTitle"><span class="ui-lang-zh">实验记录</span><span class="ui-lang-en">Experiment records</span>', INDEX_HTML)
        self.assertIn('<span class="ui-lang-zh">标注维度</span><span class="ui-lang-en">Label dimension</span>', INDEX_HTML)
        self.assertIn('<span class="ui-lang-zh">创建并分配</span><span class="ui-lang-en">Create and assign</span>', INDEX_HTML)
        self.assertIn('data-placeholder-en="Select labelers"', INDEX_HTML)
        self.assertIn('uiText("全量盲标", "Full blind labeling")', APP_JS)
        self.assertIn("setIntentExperimentFormAvailability(false)", APP_JS)
        self.assertIn("if (!intentAvailableDatasets().length)", APP_JS)
        self.assertNotIn('throw new Error("没有可用于实验分配的数据集。")', APP_JS)
        self.assertIn('id="intentExperimentCount">0', INDEX_HTML)
        self.assertIn('class="intent-experiment-empty"', INDEX_HTML)
        self.assertIn("if (count) count.textContent = String(experiments.length)", APP_JS)
        self.assertIn('class="intent-experiment-controls"', APP_JS)
        self.assertIn('data-edit-intent-experiment', APP_JS)
        self.assertIn('data-open-intent-experiment', APP_JS)
        self.assertIn('resumeIncomplete: true', APP_JS)
        self.assertIn('queueParams.set("status", shouldResumeIncomplete ? "incomplete" : "all")', APP_JS)
        self.assertIn('queueParams.set("resume", "true")', APP_JS)
        self.assertIn('container.classList.toggle("is-single-axis"', APP_JS)
        self.assertIn('.intent-summary-distributions.is-single-axis', STYLES_CSS)
        self.assertIn('id="intentExperimentEditDialog"', INDEX_HTML)
        self.assertIn('id="intentExperimentEditForm"', INDEX_HTML)
        self.assertIn('method: "PATCH"', APP_JS)
        self.assertIn('原任务分配保持不变', APP_JS)
        self.assertNotIn('class="intent-experiment-actions"', APP_JS)
        self.assertIn('.intent-experiment-controls { display: flex; align-items: center; justify-content: flex-end;', STYLES_CSS)
        self.assertIn('.intent-experiment-controls .button { min-height: 28px;', STYLES_CSS)
        self.assertIn('gap: 11px 12px; padding: 13px 14px;', STYLES_CSS)
        self.assertIn(".intent-timepoint.selected", STYLES_CSS)
        self.assertNotIn('id="intentTimepointSelect"', INDEX_HTML)
        self.assertNotIn('id="intentSaveState"', INDEX_HTML)
        self.assertIn('id="intentMyTasks"', INDEX_HTML)
        self.assertIn('id="intentToggleReveal"', INDEX_HTML)
        self.assertIn('id="intentExperimentReviewers"', INDEX_HTML)
        self.assertIn('id="intentExperimentScope"', INDEX_HTML)
        self.assertIn('id="intentCameraFrameOffset"', INDEX_HTML)
        self.assertIn('id="intentBevFrameOffset"', INDEX_HTML)
        self.assertIn('$("#intentBevFrameOffset").textContent = frameLabel', APP_JS)
        self.assertIn('value="routing">仅 Routing 意图', INDEX_HTML)
        self.assertIn('value="lane_change">仅变道意图', INDEX_HTML)
        self.assertIn('data-intent-axis-section="routing"', INDEX_HTML)
        self.assertIn('data-intent-axis-section="lane_change"', INDEX_HTML)
        self.assertIn("function intentAxisEnabled(axis)", APP_JS)
        self.assertIn("button.closest(\".intent-label-grid\").hidden", APP_JS)
        self.assertIn('ratios.push(`Routing：${ratioText', APP_JS)
        self.assertIn('ratios.push(`变道：${ratioText', APP_JS)
        self.assertIn("if (event.repeat || !intentAxisEnabled(digit[0])) return", APP_JS)
        self.assertIn('event.code === "ArrowLeft" || event.code === "ArrowRight"', APP_JS)
        self.assertIn('class="topbar-baselines intent-topbar-dataset"', INDEX_HTML)
        self.assertIn('class="multi-filter baseline-filter" id="intentTopbarDatasetPicker"', INDEX_HTML)
        self.assertIn('onlyThis: multiple', APP_JS)
        self.assertNotIn('body:is([data-active-page="intent"], [data-active-page="intent-experiments"], [data-active-page="intent-summary"]) .brand { min-width: 0;', STYLES_CSS)
        self.assertNotIn('id="intentExperimentNameSuggestion"', INDEX_HTML)
        self.assertIn('input.dataset.suggestion = suggestion', APP_JS)
        self.assertIn('#intentExperimentName::placeholder', STYLES_CSS)
        self.assertIn('id="intentExperimentNameStatus"', INDEX_HTML)
        self.assertIn('"AI 推理中"', APP_JS)
        self.assertIn('draft_name:', APP_JS)
        self.assertIn('input.value = fallback', APP_JS)
        self.assertIn('payload.source === "llm"', APP_JS)
        self.assertIn('dataset.manualEdited', APP_JS)
        self.assertNotIn('event.key !== "Tab"', APP_JS)
        self.assertIn('/api/intent-experiments/name-suggestion', APP_JS)
        self.assertIn('data-intent-summary-delete', APP_JS)
        self.assertIn('历史修订与删除审计仍会完整保留', INDEX_HTML)
        self.assertIn('id="intentDeleteConfirmDialog"', INDEX_HTML)
        self.assertIn("function bindAnalysisDiscussionEnterSubmit()", APP_JS)
        self.assertIn('event.key !== "Enter"', APP_JS)
        self.assertIn("event.shiftKey", APP_JS)
        self.assertIn("event.isComposing", APP_JS)
        self.assertIn("form.requestSubmit(submit)", APP_JS)
        self.assertIn('function confirmIntentLabelDeletion', APP_JS)
        self.assertNotIn('window.confirm(`确认删除 ${username} 在 ${caseId} 的当前标注', APP_JS)
        self.assertNotIn('window.confirm("确认删除自己在当前 Case 的标注', APP_JS)
        self.assertIn('overlap_reviewers:', APP_JS)
        self.assertIn('dataset_ids: datasetIds', APP_JS)
        self.assertIn('params.append("dataset_id", id)', APP_JS)
        self.assertIn('selected = [available[0].id]', APP_JS)
        self.assertIn('resetCaseCount: previousScope !== nextScope', APP_JS)
        self.assertIn('if (reset || currentCount < 1 || currentCount > maxCount)', APP_JS)
        self.assertIn('item.is_current', APP_JS)
        self.assertIn('reveal_answers', APP_JS)
        self.assertIn('.intent-contributor-labels { min-width: 0; display: flex; flex-wrap: nowrap; align-items: center; gap: 4px; margin-left: auto; }', STYLES_CSS)
        self.assertIn('::-webkit-inner-spin-button', STYLES_CSS)
        self.assertIn("连续扩选 / 收缩时间帧", INDEX_HTML)
        self.assertIn("单选跳到最左 / 最右时间帧", INDEX_HTML)
        self.assertIn('id="intentFrameTitle">当前帧标签', INDEX_HTML)
        self.assertIn('<h3><span>批量预填</span><small class="intent-heading-stat" id="intentCoverage">—</small></h3>', INDEX_HTML)
        self.assertNotIn('一次选择会填入全部时间点', INDEX_HTML)
        self.assertIn('.intent-experiment-form-row { min-width: 0; display: contents; }', STYLES_CSS)
        self.assertIn('grid-template-columns: repeat(8, minmax(0, 1fr))', STYLES_CSS)
        self.assertIn('.intent-experiment-form { grid-template-columns: repeat(4, minmax(0, 1fr)); }', STYLES_CSS)
        self.assertIn('id="intentExperimentAnnotationStatus"', INDEX_HTML)
        self.assertIn('annotation_status_filter:', APP_JS)
        self.assertIn('experimentAnnotationStatusCounts', APP_JS)
        self.assertIn('class="intent-label-grid intent-lane-grid"', INDEX_HTML)
        self.assertIn('.intent-lane-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }', STYLES_CSS)
        self.assertIn('.topbar-baselines {', STYLES_CSS)
        self.assertIn('max-width: min(320px, 34vw);', STYLES_CSS)
        self.assertIn('class="intent-experiment-members-field"', INDEX_HTML)
        self.assertIn('id="intentExperimentMembers" data-placeholder="选择标注人员"', INDEX_HTML)
        self.assertIn('renderMultiFilter(container, {', APP_JS)
        self.assertIn('titleZh: "标注汇总"', APP_JS)
        self.assertNotIn("意图轨迹标注汇总", INDEX_HTML)
        self.assertIn('.intent-experiment-create-body {', STYLES_CSS)
        self.assertIn('min-width: 0; display: block; padding-top: 16px;', STYLES_CSS)
        self.assertNotIn('class="intent-experiment-guide"', INDEX_HTML)
        self.assertNotIn('实验分配契约', INDEX_HTML)
        self.assertIn('创建与分配实验', INDEX_HTML)
        self.assertIn('id="intentSummaryCommentQuery"', INDEX_HTML)
        self.assertIn('id="intentSummaryCommentHits"', INDEX_HTML)
        self.assertIn('id="intentSummaryDistributions"', INDEX_HTML)
        self.assertIn('class="intent-summary-comments-column">评论', INDEX_HTML)
        self.assertIn("function renderIntentSummaryCommentHits", APP_JS)
        self.assertIn("function renderIntentSummaryDistributions", APP_JS)
        self.assertIn("INTENT_WORKSPACE_PREFERENCES_KEY", APP_JS)
        self.assertIn("resetIntentWorkspacePreferences", APP_JS)
        self.assertIn('params.set("q", commentQuery)', APP_JS)
        self.assertIn('justify-content: center; align-items: center', STYLES_CSS)
        self.assertIn('.intent-label-editor > h3 { display: grid; grid-template-columns: max-content minmax(0, 1fr);', STYLES_CSS)
        self.assertIn('selectedCount > 1 ? "多个帧标签" : "当前帧标签"', APP_JS)
        self.assertIn("@media (max-width: 1400px)", STYLES_CSS)
        self.assertNotIn("@media (max-width: 1600px) {\n  .intent-commandbar { grid-template-columns: 200px minmax(260px, 1fr) 160px auto; }\n  .intent-command-actions { grid-column: 1 / -1", STYLES_CSS)
        self.assertNotIn('class="intent-media-header-meta"', INDEX_HTML)
        self.assertNotIn('id="intentMediaHeading"', INDEX_HTML)
        self.assertIn(".shortcut-guide-dialog { width: min(660px, calc(100vw - 28px))", STYLES_CSS)
        self.assertNotIn("同步时间点", INDEX_HTML)
        self.assertIn("aspect-ratio: 16 / 9", STYLES_CSS)
        self.assertIn("object-fit: cover", STYLES_CSS)
        self.assertIn("grid-template-rows: repeat(2, 76px)", STYLES_CSS)
        self.assertNotIn(".intent-media-stage img { width: 100%; height: 100%; display: block; object-fit: contain", STYLES_CSS)
        self.assertIn('id="intentContributorList"', INDEX_HTML)
        self.assertIn('data-intent-delete-mine', APP_JS)
        self.assertIn('data-intent-contributor-menu', APP_JS)
        self.assertNotIn('intent-contributor-counts', APP_JS)
        self.assertNotIn('id="intentContributorActions"', INDEX_HTML)
        self.assertIn('id="intentSummaryAxis"', INDEX_HTML)
        self.assertIn('id="intentSummaryPageSize"', INDEX_HTML)
        self.assertIn('id="intentSummaryPageJump"', INDEX_HTML)
        self.assertIn('id="intentSummaryPageJumpButton"', INDEX_HTML)
        self.assertIn('<option value="100">100</option>', INDEX_HTML)
        self.assertIn("function jumpIntentSummaryPage()", APP_JS)
        self.assertNotIn('id="intentSummaryPageSizePicker"', INDEX_HTML)
        self.assertIn("async function deleteMyIntentLabel", APP_JS)
        self.assertIn('method: "DELETE"', APP_JS)
        self.assertIn('params.set("axis", intent.summaryAxis || "all")', APP_JS)
        self.assertIn('params.set("page_size", String(intent.summaryPageSize || 20))', APP_JS)
        self.assertIn('class="intent-summary-case-link"', APP_JS)
        self.assertIn('if (state.activePage === "intent")', APP_JS)
        self.assertIn('await loadIntentAssignees(intent.selectedDatasetIds, selected, "")', APP_JS)
        self.assertIn('intent.selectedDatasetIds = scopeIds', APP_JS)
        self.assertIn('intent.summaryDatasetIds = selectedIds', APP_JS)
        self.assertIn('intentApiUrl("/api/intent-cases", queueParams)', APP_JS)
        self.assertIn('acknowledgeLocalChange(result)', APP_JS)
        self.assertNotIn('id="intentCommentForm"', INDEX_HTML)
        self.assertIn('class="intent-card intent-collaboration-card intent-contributors-card"', INDEX_HTML)
        self.assertIn('class="intent-card intent-collaboration-card intent-discussion-card"', INDEX_HTML)
        self.assertIn('id="intentContributorsTitle">已有标注', INDEX_HTML)
        self.assertIn('class="intent-contributors-heading"', INDEX_HTML)
        self.assertIn('id="intentToggleReveal"', INDEX_HTML)
        self.assertIn('.intent-contributors-card > .intent-contributors-heading {', STYLES_CSS)
        self.assertIn('.intent-contributor-status.is-labeled', STYLES_CSS)
        self.assertIn('intentChipMarkup', APP_JS)
        self.assertIn("已标注", APP_JS)
        self.assertIn("待标注", APP_JS)
        self.assertNotIn(">轨迹修改<", INDEX_HTML)
        self.assertIn(">Routing 帧分布<", INDEX_HTML)
        self.assertIn("intentSummaryResultMarkup(item.frame_counts?.routing", APP_JS)
        self.assertNotIn('intent-summary-metric is-', APP_JS)
        self.assertNotIn("item.overrides.length", APP_JS)
        self.assertLess(INDEX_HTML.index('id="intentAggregateRouting"'), INDEX_HTML.index('id="intentFrameTitle"'))
        self.assertLess(INDEX_HTML.index('id="intentFrameTitle"'), INDEX_HTML.index('id="intentContributorsTitle"'))
        self.assertLess(INDEX_HTML.index('id="intentContributorsTitle"'), INDEX_HTML.index('id="intentCommentsTitle"'))
        self.assertIn("function renderIntentCollaboration", APP_JS)
        self.assertIn("function openIntentComments", APP_JS)
        self.assertIn('source: "intent"', APP_JS)
        self.assertIn('frameOverride.routing_intent || item.routing_default', APP_JS)
        self.assertIn('frameOverride.lane_change_intent || item.lane_change_default', APP_JS)
        self.assertIn('overrides: payload.labels?.overrides || []', APP_JS)
        self.assertIn('id="intentExportCompact"', INDEX_HTML)
        self.assertIn('id="intentExportExpanded"', INDEX_HTML)
        self.assertIn('id="intentSummaryBulkDelete"', INDEX_HTML)
        self.assertIn('id="intentSummarySelectPage"', INDEX_HTML)
        self.assertIn("function bulkDeleteIntentSummaryLabels()", APP_JS)
        self.assertIn('api("/api/intent-labels/bulk-delete"', APP_JS)
        self.assertIn('downloadIntentExport("expanded")', APP_JS)
        self.assertIn('include_incomplete: "true"', APP_JS)
        self.assertIn('params.set("experiment_id", experimentId)', APP_JS)
        self.assertIn('boundaryModifier && !event.shiftKey && event.code === "KeyZ"', APP_JS)
        self.assertIn('function intentUndo()', APP_JS)
        self.assertIn('data-shortcut-search="mod+z"', INDEX_HTML)
        self.assertNotIn('"input, textarea, select, button, [contenteditable=', APP_JS)
        self.assertNotIn('const status = item.completed ? "已完成" : "进行中"', APP_JS)
        self.assertIn("timeline.scrollLeft += event.deltaY", APP_JS)
        self.assertIn("滚轮横向浏览", INDEX_HTML)
        self.assertIn("function activateIntentTimelineThumbnails", APP_JS)
        self.assertIn('rootMargin: "48px"', APP_JS)
        self.assertIn('loading="lazy" decoding="async"', APP_JS)
        self.assertIn("function updateIntentTimelineState", APP_JS)
        self.assertIn("function renderIntentActiveFrame", APP_JS)
        self.assertIn("function intentJumpToCaseOrdinal", APP_JS)
        self.assertIn("function intentJumpToFrameOrdinal", APP_JS)
        self.assertIn('id="intentCaseOrdinalInput"', INDEX_HTML)
        self.assertIn('id="intentFrameOrdinalInput"', INDEX_HTML)
        self.assertIn("renderIntentTimeline({ loadThumbnails: !deferTimelineThumbnails })", APP_JS)
        self.assertEqual(APP_JS.count("renderIntentTimeline("), 2)
        self.assertIn("renderIntentCase({ deferTimelineThumbnails: true })", APP_JS)
        self.assertNotIn("intent.activeTimepointId = timepointId;\n  renderIntentCase();", APP_JS)
        self.assertIn("heroReady.finally", APP_JS)

    def test_trail_update_exposes_safe_preview_and_commit_contract(self) -> None:
        self.assertIn('id="trailUpdateCommitButton"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateCapability"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateSafetyBadge"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateLoadButton"', INDEX_HTML)
        self.assertIn('id="trailUpdateResults"', INDEX_HTML)
        self.assertIn('id="trailUpdateResults" aria-label="Trail update results" hidden', INDEX_HTML)
        self.assertIn("ra_stuck_auto_result", INDEX_HTML)
        self.assertIn("ra_stuck_auto_result_info", INDEX_HTML)
        self.assertIn("setTrailAttributeUpdatePreviewVisible", APP_JS)
        self.assertIn(".trail-update-onboarding", STYLES_CSS)
        self.assertIn("commitTrailAttributeUpdate", APP_JS)
        self.assertIn('id="trailUpdateConfirmDialog"', INDEX_HTML)
        self.assertIn('id="trailUpdateJsonDialog"', INDEX_HTML)
        self.assertIn('id="trailUpdateJsonPreview"', INDEX_HTML)
        self.assertEqual(INDEX_HTML.count('data-trail-json-preview='), 2)
        self.assertNotIn('id="trailUpdateTableSummary"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateIssueTableSummary"', INDEX_HTML)
        self.assertNotIn("只 deep-merge", INDEX_HTML)
        self.assertIn("openTrailUpdateJsonPreview", APP_JS)
        self.assertIn("downloadTrailUpdateJson", APP_JS)
        self.assertIn("copyTrailUpdateJson", APP_JS)
        self.assertIn("trail-update-json-dialog", STYLES_CSS)
        self.assertIn("openTrailUpdateConfirm", APP_JS)
        self.assertIn("trailUpdateConfirmResolver", APP_JS)
        self.assertIn("trailUpdateConfirmSetExpanded", APP_JS)
        self.assertIn('id="trailUpdateConfirmExpand"', INDEX_HTML)
        self.assertIn("<details class=\"trail-update-confirm-item\">", APP_JS)
        self.assertIn("trail-update-confirm-item-details", STYLES_CSS)
        self.assertIn("trail-update-confirm-dialog", STYLES_CSS)
        self.assertIn('params.set("probe_trail", "false")', APP_JS)
        self.assertIn('params.set("refresh", "true")', APP_JS)
        self.assertIn("trailAttributePreviewNeedsLoad", APP_JS)
        self.assertIn('api(trailUpdateEndpoint(runId, false, force), { cache: "no-store" })', APP_JS)
        self.assertIn("function trailUpdateStatusEndpoint", APP_JS)
        self.assertIn('/api/trail-attribute-update/status?', APP_JS)
        self.assertIn('api(trailUpdateStatusEndpoint(items, force), { cache: "no-store" })', APP_JS)
        self.assertIn("async function refreshTrailAttributeStatus", APP_JS)
        self.assertIn("function patchTrailAttributeStatus", APP_JS)
        self.assertIn("data-trail-update-status-issue", APP_JS)
        self.assertIn("void refreshTrailAttributeStatus({ runId, previewKey, requestSeq, force }).catch(() => {});", APP_JS)
        self.assertIn("syncTrailAttributeActions", APP_JS)
        self.assertIn("syncTrailIssueActions", APP_JS)
        self.assertIn("trailUpdateWriteReady", APP_JS)
        self.assertIn("setTrailAttributeLoading", APP_JS)
        self.assertIn('trailPage?.classList.add("is-loading")', APP_JS)
        self.assertIn(".trail-update-page.is-loading .button:disabled { opacity: 1; filter: none; }", STYLES_CSS)
        self.assertIn('trail-update-page hidden is-loading" id="trailAttributeUpdatePage"', INDEX_HTML)
        self.assertIn("min-height: 52px", STYLES_CSS)
        self.assertIn(".trail-update-confirm-list { display: block", STYLES_CSS)
        self.assertNotIn("window.confirm(", APP_JS[APP_JS.index("function commitTrailIssueExclusion"):APP_JS.index("function bindTrailAttributeUpdateEvents")])
        self.assertIn('id="trailUpdateReviewTab"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateSectionTitle"', INDEX_HTML)
        self.assertIn('id="trailUpdateRunPicker"', INDEX_HTML)
        self.assertIn('id="trailUpdateRunPickerPanel"', INDEX_HTML)
        self.assertIn('class="ui-select-native gateway-model-native-select"', INDEX_HTML)
        self.assertNotIn("trail-update-section-heading", STYLES_CSS)
        self.assertIn("font-size: 11px", STYLES_CSS)
        self.assertIn("font-size: 9px", STYLES_CSS)
        self.assertNotIn("box-shadow: inset 0 -8px 18px", STYLES_CSS)
        self.assertNotIn("border-bottom: 1px solid rgba(34,211,238,.25)", STYLES_CSS)
        self.assertIn('class="page-card trail-update-header-card"', INDEX_HTML)
        self.assertIn('id="trailUpdateReviewControlsPanel"', INDEX_HTML)
        self.assertIn('id="trailUpdateRunHint"', INDEX_HTML)
        self.assertIn("No model Run in this environment", APP_JS)
        self.assertIn("does not share Runs with production 8785", APP_JS)
        self.assertIn("Do not inherit the Review gallery's", APP_JS)
        self.assertIn("No model Run selected (all Runs)", APP_JS)
        self.assertNotIn("no Run merges the latest Review from all Runs", INDEX_HTML)
        self.assertNotIn('id="trailUpdateWriteHint"', INDEX_HTML)
        self.assertIn("vertical-align: middle", STYLES_CSS)
        self.assertIn("border-spacing: 0 5px", STYLES_CSS)
        self.assertIn("trail-update-table td:first-child", STYLES_CSS)
        self.assertIn("Trail 更新状态", INDEX_HTML)
        self.assertIn("数据集版本", INDEX_HTML)
        self.assertIn("ra_stuck_auto_result_info.ra_triage_dashboard.should_exclude", INDEX_HTML)
        self.assertIn("trail-update-field-stat-card", INDEX_HTML)
        self.assertIn("trail-update-issue-summary-grid", INDEX_HTML)
        self.assertIn(".trail-update-issue-summary-grid", STYLES_CSS)
        self.assertIn("align-items: stretch", STYLES_CSS)
        self.assertIn(".trail-update-direct-table .trail-update-comment { text-align: center; }", STYLES_CSS)
        self.assertIn("const shortPath = patchPath.split", APP_JS)
        self.assertIn("grid-template-columns: minmax(0, 1fr)", STYLES_CSS)
        self.assertIn(".analysis-stat-card.trail-update-field-stat-card", STYLES_CSS)
        self.assertIn("white-space: normal", STYLES_CSS)
        self.assertIn("-webkit-line-clamp: 2", STYLES_CSS)
        self.assertNotIn('id="trailUpdateInfoFieldDetail"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateIssueFieldDetail"', INDEX_HTML)
        self.assertIn("trailUpdateStatusSummary", APP_JS)
        self.assertIn("trail_update_status_summary", APP_JS)
        self.assertIn('id="trailUpdateFilterForm"', INDEX_HTML)
        self.assertIn('id="trailUpdateSearchInput"', INDEX_HTML)
        self.assertIn('id="trailUpdateGtFilter"', INDEX_HTML)
        self.assertIn('id="trailUpdateModelLabelFilter"', INDEX_HTML)
        self.assertIn('id="trailUpdateReviewerFilter"', INDEX_HTML)
        self.assertIn('id="trailUpdateReviewStatusFilter"', INDEX_HTML)
        self.assertIn('id="trailUpdateStatusFilter"', INDEX_HTML)
        self.assertIn('id="trailUpdatePagination"', INDEX_HTML)
        self.assertIn('id="trailUpdatePageSize"', INDEX_HTML)
        self.assertIn("function normalizedTrailUpdateRouteFilters", APP_JS)
        self.assertIn("function applyTrailUpdateRouteControls", APP_JS)
        self.assertIn("function trailUpdateFilteredItems", APP_JS)
        self.assertIn("function renderTrailUpdatePagination", APP_JS)
        self.assertIn("trail_status", APP_JS)
        self.assertIn("review_status", APP_JS)
        self.assertIn("renderTrailUpdateFilters", APP_JS)
        self.assertIn("trailUpdateStatusSummary(data, filteredItems)", APP_JS)
        self.assertIn("allItems = Array.isArray(data?.items)", APP_JS)
        self.assertIn('data-label="模型 reason"', APP_JS)
        self.assertIn('data-label="预计写入 info"', APP_JS)
        self.assertIn("trail-update-comment-target", APP_JS)
        self.assertIn("trail-update-comment-target", STYLES_CSS)
        self.assertIn("content: attr(data-label)", STYLES_CSS)
        self.assertIn(".trail-update-table tbody tr:has(.trail-update-empty)", STYLES_CSS)
        self.assertIn("grid-template-columns: minmax(0, 1fr); grid-template-rows: auto auto auto", STYLES_CSS)
        self.assertIn("function trailUpdateTargetSpec", APP_JS)
        self.assertIn("target_path", APP_JS)
        self.assertIn("is-synced", STYLES_CSS)
        self.assertIn("analysis-review-status-bar", APP_JS)
        self.assertIn("trail-status-${escapeHtml(meta.key)}", APP_JS)
        self.assertIn("data-trail-update-status-key", APP_JS)
        self.assertIn("baseline_id", APP_JS)
        self.assertIn("data.baselines", APP_JS)
        self.assertIn("title=\"${escapeHtml(sourceRun.title)}\"", APP_JS)
        self.assertIn("trail-update-status-card", INDEX_HTML)
        self.assertIn("trail-update-status-heading", STYLES_CSS)
        self.assertIn(".analysis-review-status-card.trail-update-status-card", STYLES_CSS)
        self.assertIn("grid-template-columns: minmax(0, 1fr) minmax(0, 2fr) minmax(0, 2fr)", STYLES_CSS)
        self.assertIn("grid-template-rows: auto auto", STYLES_CSS)
        self.assertNotIn('id="trailUpdateStatusDetail"', INDEX_HTML)
        self.assertIn("cursor: default", STYLES_CSS)
        self.assertNotIn(".trail-update-source-cell, .trail-update-comment[title], .trail-update-reason[title] { cursor: help; }", STYLES_CSS)
        self.assertIn("bindUiSelect(picker", APP_JS)
        self.assertNotIn("Preview fingerprint", INDEX_HTML)
        self.assertNotIn('id="trailUpdateIssueDigest"', INDEX_HTML)
        self.assertNotIn("trailUpdateIssueDigest", APP_JS)
        self.assertIn("loadPageData &&", APP_JS)
        self.assertIn("trailAttributePreviewNeedsLoad", APP_JS)
        bootstrap_body = APP_JS[APP_JS.index("async function bootstrap"):]
        self.assertNotIn("initialPageRequests.push(loadTrailAttributePreview())", bootstrap_body)
        self.assertIn("void loadTrailAttributePreview().catch", bootstrap_body)
        self.assertIn("renderTrailAttributeRunPicker();", APP_JS)
        self.assertIn('id="trailUpdateIssueTab"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueEntries"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueAddButton"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateIssueHistoricalExclusionsButton"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueJsonImportButton"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueExcelImportButton"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueClearAllButton"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueJsonImportDialog"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueJsonImportFile"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueExcelImportDialog"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueExcelImportFile"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueJsonImportPreview"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueExcelImportPreview"', INDEX_HTML)
        self.assertIn('class="trail-update-direct-footer"', INDEX_HTML)
        self.assertIn("data-trail-issue-entry-id", INDEX_HTML)
        self.assertIn("data-trail-issue-entry-comment", INDEX_HTML)
        self.assertIn("loadTrailIssuePreview", APP_JS)
        self.assertNotIn("loadTrailHistoricalExclusions", APP_JS)
        self.assertNotIn("/api/trail-attribute-update/historical-exclusions", APP_JS)
        self.assertIn("clearTrailIssueEntries", APP_JS)
        self.assertIn("historicalExclusionSourceMarkup", APP_JS)
        self.assertIn("data-trail-issue-entry-source", APP_JS)
        self.assertIn("commitTrailIssueExclusion", APP_JS)
        self.assertIn("refreshTrailReviewAfterIssueCommit", APP_JS)
        self.assertIn("await loadTrailAttributePreview(true);", APP_JS)
        self.assertIn("/api/trail-attribute-update/issue-preview", APP_JS)
        self.assertIn("/api/trail-attribute-update/issue-commit", APP_JS)
        self.assertNotIn("真实接口 · 预览优先", INDEX_HTML)
        self.assertIn("预计改动（仅写 info）", INDEX_HTML)
        self.assertIn("预计写入 info", INDEX_HTML)
        self.assertIn("<th>数据集版本</th>", INDEX_HTML)
        self.assertIn("should_exclude_comment", INDEX_HTML)
        self.assertIn("entries: parsed.entries", APP_JS)
        self.assertIn("requested_entries", APP_JS)
        self.assertNotIn("Issue 与排除说明", INDEX_HTML)
        self.assertIn('data-trail-issue-entry-id rows="2"', INDEX_HTML)
        self.assertIn(".trail-update-direct-table th,", STYLES_CSS)
        self.assertIn("vertical-align: middle", STYLES_CSS)
        self.assertIn(".trail-update-direct-actions", STYLES_CSS)
        self.assertNotIn(".trail-update-entry-heading", STYLES_CSS)
        self.assertIn(".trail-update-direct-footer", STYLES_CSS)
        self.assertIn("multiple per row", APP_JS)
        self.assertIn("parsed.ids.forEach", APP_JS)
        self.assertIn("trailIssueImportState", APP_JS)
        self.assertIn("previewTrailIssueJsonImport", APP_JS)
        self.assertIn("previewTrailIssueExcelImport", APP_JS)
        self.assertIn("applyTrailIssueImportPreview", APP_JS)
        self.assertIn("/api/trail-attribute-update/issue-import/json-preview", APP_JS)
        self.assertIn("/api/trail-attribute-update/issue-import/excel-preview", APP_JS)
        self.assertIn("allowReadOnlyMutation: true", APP_JS)
        self.assertIn("trail-update-import-preview-table", INDEX_HTML)
        self.assertIn(".trail-update-import-preview", STYLES_CSS)
        self.assertIn("field_update", APP_JS)
        self.assertIn("不改模型 label", APP_JS)
        self.assertNotIn("trailInfoPreviewJson", APP_JS)
        self.assertNotIn("trail-update-json-preview", STYLES_CSS)
        self.assertIn('data-trail-json-preview="review"', INDEX_HTML)
        self.assertIn('data-trail-json-preview="issue"', INDEX_HTML)
        self.assertIn("trail-update-result-actions", STYLES_CSS)
        self.assertIn("排除说明", INDEX_HTML)
        self.assertIn('id="trailUpdateProgressDialog"', INDEX_HTML)
        self.assertIn("openTrailUpdateProgress", APP_JS)
        self.assertIn("finishTrailUpdateProgress", APP_JS)
        self.assertIn("data-trail-progress-stage", INDEX_HTML)
        self.assertIn("trail-update-progress-track.is-running", STYLES_CSS)
        self.assertIn('id="trailUpdateIssueHistory"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueHistoryList"', INDEX_HTML)
        self.assertIn("loadTrailIssueHistory", APP_JS)
        self.assertIn("/api/trail-attribute-update/issue-history", APP_JS)
        self.assertIn("trail-update-history-item", STYLES_CSS)
        self.assertIn(".trail-update-historical-source", STYLES_CSS)
        self.assertNotIn("三步生成待处理草稿", INDEX_HTML)
        self.assertIn("loadPageData &&", APP_JS)
        self.assertIn("trailAttributePreviewNeedsLoad", APP_JS)

    def test_db_backed_mentions_cover_review_analysis_and_issue_exclusion(self) -> None:
        self.assertIn('api("/api/mention-users")', APP_JS)
        self.assertIn("state.mentionUsers", APP_JS)
        self.assertIn("activeMentionQuery", APP_JS)
        self.assertIn("review-mention-popover", APP_JS)
        self.assertIn("function reviewMentionCaretAnchor", APP_JS)
        self.assertIn("function positionReviewMentionPopover", APP_JS)
        self.assertIn("reviewMentionCaretAnchor(textarea, active.start)", APP_JS)
        self.assertIn('popover.classList.toggle("opens-up", opensUp)', APP_JS)
        self.assertIn('event.key === "Escape"', APP_JS)
        self.assertIn('}, { capture: true });', APP_JS)
        self.assertIn("preserveTrigger: true", APP_JS)
        self.assertIn("item.username.includes(normalizedQuery)", APP_JS)
        self.assertIn('item.displayName.toLocaleLowerCase("zh-CN").includes(normalizedQuery)', APP_JS)
        self.assertIn("\\u3400-\\u9fff", APP_JS)
        self.assertIn(
            "梁祥辉",
            (STATIC_DIR.parent / "app" / "db_parts" / "access.py").read_text(
                encoding="utf-8"
            ),
        )
        self.assertIn("reviewCommentBodyMarkup", APP_JS)
        self.assertIn('uiText("自己", "You")', APP_JS)
        self.assertNotIn("item !== current", APP_JS)
        self.assertIn(".review-mention-popover", STYLES_CSS)
        self.assertIn("position: fixed", STYLES_CSS)
        self.assertIn(".review-mention-popover.opens-up", STYLES_CSS)
        self.assertIn(".review-mention-option.is-active", STYLES_CSS)
        self.assertNotIn("可用 @ldap 通知同事", APP_JS)
        self.assertNotIn("可输入 @ldap", INDEX_HTML)
        self.assertIn('id="analysisDiscussionDialog"', INDEX_HTML)
        self.assertIn("data-analysis-discussion", APP_JS)
        self.assertIn('class="analysis-discussion-link"', APP_JS)
        self.assertIn(
            'const discussionRunId = state.selectedRunId || annotation.model_run_id || "";',
            APP_JS,
        )
        self.assertIn('runId: button.dataset.modelRunId || ""', APP_JS)
        self.assertNotIn('class="button button-quiet" type="button" data-analysis-discussion', APP_JS)
        self.assertIn(".analysis-discussion-link, .text-link", STYLES_CSS)
        self.assertIn("data-trail-update-discussion", APP_JS)
        self.assertNotIn('<th>操作</th>', INDEX_HTML)
        self.assertIn('class="trail-update-issue-meta"', APP_JS)
        self.assertIn(".trail-update-issue-meta > small", STYLES_CSS)
        self.assertNotIn('data-label="操作"', APP_JS)
        self.assertIn('colspan="8" class="trail-update-empty"', INDEX_HTML)
        self.assertIn('source: "trail-update"', APP_JS)
        self.assertIn("review.model_run_id || model.run_id", APP_JS)
        self.assertIn('/comments?model_run_id=', APP_JS)
        self.assertIn('openComments: params.get("comments") === "1"', APP_JS)
        self.assertIn('source: "deep-link"', APP_JS)
        self.assertIn("data-review-comments", APP_JS)
        self.assertIn('reply_to_id: context.replyTo?.id || null', APP_JS)
        self.assertIn('data-comment-reply=', APP_JS)
        self.assertIn('data-comment-share=', APP_JS)
        self.assertIn("analysisDiscussionShareUrl", APP_JS)
        self.assertIn("navigator.share", APP_JS)
        self.assertIn("navigator.clipboard?.writeText", APP_JS)
        self.assertIn('url.searchParams.set("comment"', APP_JS)
        self.assertIn('.replace(/^\\s*(?:#{1,3}|>|[-+*]|\\d+[.)])\\s+/gm, "")', APP_JS)
        self.assertIn('data-comment-format="bold"', INDEX_HTML)
        self.assertIn("data-comment-image", INDEX_HTML)
        self.assertIn("comments-with-attachments", APP_JS)
        self.assertIn('"X-RA-Triage-Request": "comment-v1"', APP_JS)
        self.assertIn("comment-markdown-image", STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .comment-thread-list', STYLES_CSS)
        self.assertNotIn('/annotations`, {\n      method: "POST",\n      body: JSON.stringify({\n        model_run_id: String(context.runId', APP_JS)
        self.assertIn(".trail-update-discussion-link", STYLES_CSS)
        self.assertIn("saveAnalysisDiscussion", APP_JS)
        self.assertIn("data-mention-composer", INDEX_HTML)
        self.assertIn("data-trail-issue-entry-comment data-mention-composer", APP_JS)
        self.assertIn('id="mentionUserForm"', INDEX_HTML)
        self.assertIn("does not grant Dashboard write or admin access", INDEX_HTML)
