from __future__ import annotations

import unittest
from pathlib import Path

from frontend_js import (  # type: ignore  # unittest discover puts tests/ on sys.path
    JS_DIR,
    MANIFEST_PATH,
    STATIC_DIR,
    load_app_entry_js,
    load_app_js,
)


APP_JS = load_app_js()
APP_ENTRY_JS = load_app_entry_js()
STYLES_CSS = (STATIC_DIR / "styles.css").read_text(encoding="utf-8")
INDEX_HTML = (STATIC_DIR / "index.html").read_text(encoding="utf-8")
RUN_COMPARISON_JS = (JS_DIR / "run-comparison.js").read_text(encoding="utf-8")


class FrontendContractTest(unittest.TestCase):
    def test_admin_run_comparison_is_hidden_shareable_and_review_linked(self) -> None:
        self.assertIn('id="runComparisonNavButton"', INDEX_HTML)
        self.assertIn('data-page="comparison"', INDEX_HTML)
        self.assertIn('runComparisonNav.hidden = !state.session.is_admin', APP_JS)
        self.assertIn('path: "/run-comparison"', APP_JS)
        self.assertIn('api(`/api/model-run-comparison?', APP_JS)
        self.assertIn('url.searchParams.set("baseline_run"', APP_JS)
        self.assertIn('url.searchParams.set("candidate_run"', APP_JS)
        self.assertIn('url.searchParams.set("issue", String(issueId))', APP_JS)
        self.assertIn('url.searchParams.set("run", String(runId))', APP_JS)
        self.assertIn('url.searchParams.set("comparison", "all")', APP_JS)
        self.assertIn("基线 Prompt / 输入快照", INDEX_HTML)
        self.assertIn("新 Run Prompt / 输入快照", INDEX_HTML)
        self.assertIn('class="case-pagination gallery-pagination comparison-pagination"', INDEX_HTML)
        self.assertIn('id="comparisonPageJump"', INDEX_HTML)
        self.assertIn('id="comparisonPageJumpButton"', INDEX_HTML)
        self.assertIn("async function jumpToRunComparisonPage", APP_JS)
        self.assertIn('event.key === "Enter"', APP_JS)
        self.assertIn('event.key === "Escape"', APP_JS)
        self.assertIn('loadRunComparison({ historyMode: "push" })', APP_JS)
        self.assertIn(".run-comparison-page {\n  gap: 8px;\n  font-size: 12px;", STYLES_CSS)
        self.assertIn(".comparison-case-table th,\n.comparison-case-table td {", STYLES_CSS)
        self.assertIn("text-align: center;\n  vertical-align: middle;", STYLES_CSS)
        self.assertIn("justify-items: center;", STYLES_CSS)
        self.assertIn(".comparison-transition-filter {\n  display: flex;\n  flex-wrap: wrap;\n  justify-content: flex-end;", STYLES_CSS)
        self.assertLess(
            INDEX_HTML.index('id="comparisonTransitionFilter"'),
            INDEX_HTML.index('id="comparisonSearchInput"'),
        )
        self.assertIn('class="comparison-search"><span>Issue ID / reason</span>', INDEX_HTML)
        self.assertIn('id="comparisonGtFilter"', INDEX_HTML)
        self.assertIn('id="comparisonBaselineLabelFilter"', INDEX_HTML)
        self.assertIn('id="comparisonCandidateLabelFilter"', INDEX_HTML)
        self.assertIn('<option value="NONE">NONE / 无输出</option>', INDEX_HTML)
        self.assertIn('id="comparisonLabelChangeFilter"', INDEX_HTML)
        self.assertIn('id="comparisonResetFilters"', INDEX_HTML)
        self.assertIn('gt_label: state.runComparison.gtLabel', APP_JS)
        self.assertIn('baseline_label: state.runComparison.baselineLabel', APP_JS)
        self.assertIn('candidate_label: state.runComparison.candidateLabel', APP_JS)
        self.assertIn('label_change: state.runComparison.labelChange', APP_JS)
        self.assertIn('run?.baseline_prediction_count || 0', APP_JS)
        self.assertIn('if (selectedCoverage <= 0 && covered.length)', APP_JS)
        self.assertIn('至少一侧覆盖当前数据集', APP_JS)
        self.assertIn('无当前数据集输出的一侧将显示为 NONE', APP_JS)
        self.assertIn('pageSize: 10', APP_JS)
        self.assertIn('<option selected>10</option>', INDEX_HTML)
        self.assertIn('comparison-prediction-verdict comparison-chip', APP_JS)
        self.assertIn('.comparison-prediction-verdict {', STYLES_CSS)
        self.assertIn('comparison-match" : "comparison-mismatch', APP_JS)
        self.assertNotIn('comparison-prediction-side', APP_JS)
        self.assertNotIn('.comparison-prediction-candidate', STYLES_CSS)
        self.assertIn('class="comparison-output-label">${escapeHtml(label)}</strong>', APP_JS)
        self.assertIn('<strong>${escapeHtml(item.gt_label || "—")}</strong>', APP_JS)
        self.assertNotIn('${labelBadge(label, "NONE")}', RUN_COMPARISON_JS)
        self.assertNotIn('${labelBadge(item.gt_label, "—")}', RUN_COMPARISON_JS)
        self.assertIn('.comparison-gt-summary > strong', STYLES_CSS)
        self.assertIn('.comparison-output-label {', STYLES_CSS)
        self.assertNotIn('.comparison-gt-summary .label-badge', STYLES_CSS)
        self.assertNotIn('.comparison-prediction-output .label-badge', STYLES_CSS)
        self.assertIn('align-content: center;\n  justify-items: center;', STYLES_CSS)
        self.assertIn('justify-content: center;\n  flex-wrap: wrap;', STYLES_CSS)
        self.assertIn('.comparison-prediction.is-error {', STYLES_CSS)
        self.assertIn('background: var(--raised);', STYLES_CSS)
        self.assertIn('data-comparison-row', APP_JS)
        self.assertNotIn('data-comparison-reason', APP_JS)
        self.assertIn('event.target.closest("a, button, input, select, textarea")', APP_JS)
        self.assertIn('!["Enter", " "].includes(event.key)', APP_JS)
        self.assertIn('点击整行对比 Reason', APP_JS)
        self.assertIn('title="${escapeHtml(reason)}" aria-label="${escapeHtml(reason)}"', APP_JS)
        self.assertIn('.comparison-prediction-reason {', STYLES_CSS)
        self.assertIn('cursor: help;', STYLES_CSS)
        self.assertIn('overflow-wrap: anywhere;\n  word-break: break-word;', STYLES_CSS)
        self.assertIn('.comparison-transition-badge.p2p {', STYLES_CSS)
        self.assertIn('.comparison-transition-badge.f2f {', STYLES_CSS)
        self.assertIn('--transition-from: #f87171;\n  --transition-to: #34d399;', STYLES_CSS)
        self.assertIn('--transition-from: #34d399;\n  --transition-to: #f87171;', STYLES_CSS)
        self.assertIn('.comparison-review-links {\n  min-height: 88px;', STYLES_CSS)
        self.assertIn('function openComparisonReasonDialog(issueId)', APP_JS)
        self.assertIn('renderComparisonReasonSide("Baseline", item.baseline', APP_JS)
        self.assertIn('renderComparisonReasonSide("Candidate", item.candidate', APP_JS)
        self.assertIn('id="comparisonReasonDialog"', INDEX_HTML)
        self.assertIn('id="comparisonReasonBaselineBody"', INDEX_HTML)
        self.assertIn('id="comparisonReasonCandidateBody"', INDEX_HTML)
        self.assertIn('class="comparison-reason-grid"', INDEX_HTML)
        self.assertIn('.comparison-reason-content p', STYLES_CSS)

    def test_stage1_true_stuck_has_explicit_comparison_contract(self) -> None:
        self.assertIn('const STAGE1_TRUE_STUCK_LABEL = "真实卡住"', APP_JS)
        self.assertIn('const MODEL_LABELS = [...LABELS, STAGE1_TRUE_STUCK_LABEL]', APP_JS)
        self.assertIn('function modelLabelMatchesGt(modelLabel, gtLabel)', APP_JS)
        self.assertIn('gtLabel === "正确触发" || gtLabel === "无需协助"', APP_JS)
        self.assertIn('modelLabelMatchesGt(cell.model_label, row.gt_label)', APP_JS)

    def test_frontend_modules_load_in_manifest_order_from_thin_entry(self) -> None:
        names = [
            line.strip()
            for line in MANIFEST_PATH.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ]
        self.assertGreaterEqual(len(names), 8)
        self.assertEqual(names[0], "core-base.js")
        self.assertEqual(names[-1], "bind-bootstrap.js")
        for name in names:
            self.assertTrue((JS_DIR / name).is_file(), name)
            self.assertIn(f'"{name}"', APP_ENTRY_JS)
        self.assertIn("CACHE_VERSION", APP_ENTRY_JS)
        self.assertIn("manual-triage-278", APP_ENTRY_JS)
        self.assertIn("function setBaselineScopes", APP_JS)
        self.assertIn("function applyInferredBaselinesFromRun", APP_JS)
        self.assertIn("clearIncompatible: true", APP_JS)
        self.assertNotIn("(preferDefault ? state.modelRuns[0]", APP_JS)
        self.assertIn("never carry an implicit/inherited Run", APP_JS)
        self.assertIn("baselineLabelForScope(item.baseline_scope)", APP_JS)
        self.assertIn("...baselineRows", APP_JS)
        self.assertIn("baselineMediaReady", APP_JS)
        self.assertIn("function currentWorksetIssueCount", APP_JS)
        self.assertIn("currentWorksetIssueCount()", APP_JS)
        self.assertIn("inferred_baseline_ids", APP_JS)
        self.assertIn("data-multi-only", APP_JS)
        self.assertIn("onlyThis: true", APP_JS)
        self.assertIn(".multi-filter-only", STYLES_CSS)
        self.assertIn(".multi-filter.is-open .multi-filter-caret", STYLES_CSS)
        self.assertIn("function appendBaselineParams", APP_JS)
        self.assertIn('id="baselineFilter"', INDEX_HTML)
        self.assertIn('id="gtSyncButton"', INDEX_HTML)
        self.assertIn('id="gtSyncSourceTime"', INDEX_HTML)
        self.assertIn('id="gtSyncTooltip" role="tooltip"', INDEX_HTML)
        self.assertIn('aria-describedby="gtSyncTooltip"', INDEX_HTML)
        self.assertIn('"gt-sync.js"', APP_ENTRY_JS)
        self.assertIn("async function refreshAuthoritativeGt", APP_JS)
        self.assertIn('/api/gt-sync', APP_JS)
        self.assertIn('result.status === "running"', APP_JS)
        self.assertIn("GT 后台同步已开始", APP_JS)
        self.assertIn('class="ui-lang-zh">同步</span>', INDEX_HTML)
        self.assertIn(".gt-sync-control .gt-sync-button,", STYLES_CSS)
        self.assertIn("baselines: normalizeBaselineIds(state.selectedBaselineIds)", APP_JS)
        self.assertIn("Array.isArray(current.baselines)", APP_JS)
        self.assertIn('latestGtSyncTimestamp(visibleItems, "last_checked_at")', APP_JS)
        self.assertIn("function renderGtSyncTooltip", APP_JS)
        self.assertIn("本次结果", APP_JS)
        self.assertIn("Trail GT 更新", APP_JS)
        self.assertIn(".gt-sync-meta:hover ~ .gt-sync-tooltip", STYLES_CSS)
        self.assertIn("renderGtSyncStatus(data.gt_sync)", APP_JS)
        self.assertIn(".gt-sync-control", STYLES_CSS)
        self.assertIn("baselines", APP_JS)
        self.assertIn("/static/js/", APP_ENTRY_JS)
        self.assertIn("script.async = false", APP_ENTRY_JS)
        self.assertIn("app.js?v=manual-triage-278", INDEX_HTML)
        self.assertIn('"work-split.js"', APP_ENTRY_JS)
        # Product logic must live in domain modules, not the entry loader.
        self.assertNotIn("async function bootstrap", APP_ENTRY_JS)
        self.assertNotIn("function withBase(path)", APP_ENTRY_JS)
        self.assertIn("async function bootstrap", APP_JS)
        self.assertIn("function withBase(path)", APP_JS)

    def test_frontend_uses_one_base_path_boundary(self) -> None:
        self.assertIn('meta[name="ra-triage-base"]', APP_JS)
        self.assertIn("const CONFIGURED_BASE_PATH = normalizeClientBasePath(", APP_JS)
        self.assertIn("window.__RA_TRIAGE_BASE__ ?? CONFIGURED_BASE_PATH", APP_JS)
        self.assertIn("function withBase(path)", APP_JS)
        self.assertIn("function stripBasePath(pathname)", APP_JS)
        self.assertIn("removeBasePath(value, CONFIGURED_BASE_PATH)", APP_JS)
        self.assertIn("fetch(withBase(path)", APP_JS)
        self.assertIn("function normalizeApiPayloadUrls(value)", APP_JS)
        self.assertIn('key === "url" || key.endsWith("_url")', APP_JS)
        self.assertIn("stripBasePath(window.location.pathname)", APP_JS)

    def test_gallery_card_does_not_nest_controls_under_button_role(self) -> None:
        self.assertIn('class="issue-card-open"', APP_JS)
        self.assertIn('data-open-issue="${escapeHtml(item.issue_id)}"', APP_JS)
        self.assertIn('querySelectorAll("[data-open-issue]")', APP_JS)
        self.assertNotIn(
            'data-issue-id="${escapeHtml(item.issue_id)}" role="button"',
            APP_JS,
        )

    def test_gallery_reviewer_metadata_shares_the_label_row(self) -> None:
        card_start = APP_JS.index("function issueCard(item)")
        card_end = APP_JS.index("\nfunction caseGallerySignature", card_start)
        card_body = APP_JS[card_start:card_end]
        labels_start = card_body.index('<div class="issue-card-labels">')
        labels_end = card_body.index('</div>', labels_start)
        labels_body = card_body[labels_start:labels_end]
        self.assertIn('class="issue-reviewer"', labels_body)
        self.assertNotIn('<div class="issue-reviewer">', card_body)

    def test_dense_gallery_labels_do_not_split_or_overflow_the_card(self) -> None:
        card_start = APP_JS.index("function issueCard(item)")
        card_end = APP_JS.index("\nfunction caseGallerySignature", card_start)
        card_body = APP_JS[card_start:card_end]
        self.assertIn("grid-auto-rows: 1fr; align-items: stretch;", STYLES_CSS)
        self.assertIn(".issue-card-heading { min-width: 0; min-height: 19px;", STYLES_CSS)
        self.assertNotIn('class="issue-title"', card_body)
        self.assertNotIn("rawTitle", card_body)
        self.assertIn(".issue-card-labels {\n  min-width: 0; overflow: hidden;", STYLES_CSS)
        self.assertIn(
            ".issue-label-pair { flex: 0 0 auto; display: inline-flex;",
            STYLES_CSS,
        )
        self.assertIn(
            ".issue-label-pair > small { flex: 0 0 auto;",
            STYLES_CSS,
        )

    def test_gallery_heading_only_surfaces_actionable_review_flags(self) -> None:
        self.assertIn("function issueCardReviewFlag(annotation)", APP_JS)
        self.assertIn('annotation?.is_excluded', APP_JS)
        self.assertIn('annotation?.review_status === "needs_gt_review"', APP_JS)
        self.assertIn('data-card-review-flag="excluded"', APP_JS)
        self.assertIn('data-card-review-flag="needs_gt_review"', APP_JS)
        self.assertIn("应该排除", APP_JS)
        self.assertIn("GT 待复核", APP_JS)
        self.assertNotIn('labelBadge(annotation, t("gallery.pending_review"))', APP_JS)
        self.assertIn("review_status: item.annotation.review_status", APP_JS)
        self.assertIn("is_excluded: Boolean(item.annotation.is_excluded)", APP_JS)
        self.assertIn(".issue-card-flag-needs-gt", STYLES_CSS)
        self.assertIn(".issue-card-flag-excluded", STYLES_CSS)

    def test_analysis_run_scope_is_ellipsized_with_full_title(self) -> None:
        self.assertIn('$("#analysisReviewScope").title = reviewScope;', APP_JS)
        self.assertIn(
            ".analysis-stat-card > small {\n  min-width: 0; overflow: hidden; display: block;",
            STYLES_CSS,
        )
        self.assertIn("text-overflow: ellipsis; white-space: nowrap;", STYLES_CSS)

    def test_manual_triage_brand_links_to_review_home(self) -> None:
        self.assertIn('class="sidebar-copy sidebar-home"', INDEX_HTML)
        self.assertIn('data-page-target="review" data-app-path="/review"', INDEX_HTML)
        self.assertIn('aria-label="Manual Triage 首页"', INDEX_HTML)

    def test_color_theme_is_persisted_and_applied_before_first_paint(self) -> None:
        self.assertIn('data-color-theme="dark"', INDEX_HTML)
        self.assertIn('localStorage.getItem("ra-triage-color-theme")', INDEX_HTML)
        self.assertIn('id="themeToggleButton"', INDEX_HTML)
        self.assertIn("function applyColorTheme(theme", APP_JS)
        self.assertIn('localStorage.setItem("ra-triage-color-theme"', APP_JS)
        self.assertIn('html[data-color-theme="light"]', STYLES_CSS)
        self.assertIn('color-scheme: light', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .issue-card { background: var(--raised); }', STYLES_CSS)

    def test_light_theme_keeps_controls_and_non_media_surfaces_readable(self) -> None:
        self.assertIn('html[data-color-theme="light"] input::placeholder', STYLES_CSS)
        self.assertIn('-webkit-text-fill-color: #627086', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .comparison-summary', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .bev-video-controls', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .gateway-model-option strong', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .analysis-stat-card > strong', STYLES_CSS)
        self.assertIn('background: var(--overlay);', STYLES_CSS)
        self.assertIn('--faint: #64748b', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .review-tag-axis-title', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .issue-id', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .run-source-tab em', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .button-primary', STYLES_CSS)
        self.assertIn('styles.css?v=manual-triage-278', INDEX_HTML)
        self.assertIn(".review-exclude-toggle { display: grid; grid-template-columns: auto minmax(0, 1fr); align-items: center;", STYLES_CSS)
        self.assertIn("display: flex; align-items: baseline; flex-wrap: wrap; gap: 6px;", STYLES_CSS)
        self.assertIn("max-height: min(70dvh, 640px); overflow: auto;", STYLES_CSS)
        self.assertIn("justify-content: flex-end; margin-left: auto;", STYLES_CSS)
        self.assertIn('id="resetReviewFiltersButton"', INDEX_HTML)
        self.assertIn('class="ui-lang-zh">重置</span>', INDEX_HTML)
        self.assertIn('class="ui-lang-en">Reset</span>', INDEX_HTML)
        self.assertIn("async function resetReviewFilters", APP_JS)
        self.assertIn("flex-wrap: nowrap; align-items: center; gap: 3px;", STYLES_CSS)
        self.assertIn(".issue-card-heading-main", STYLES_CSS)
        self.assertIn('class="issue-card-heading-main"', APP_JS)
        self.assertIn('class="row-evidence" title="', APP_JS)
        self.assertIn("enteringReviewHome", APP_JS)
        self.assertIn("needsReload", APP_JS)
        self.assertIn("--ui-chevron-mask:", STYLES_CSS)
        self.assertNotIn('content: "⌄"', STYLES_CSS)
        self.assertIn('id="splitFilteredButton"', INDEX_HTML)
        self.assertIn('id="workSplitDialog"', INDEX_HTML)
        self.assertIn('id="workAssigneeFilter"', INDEX_HTML)
        self.assertIn("function openWorkSplitDialog", APP_JS)
        self.assertIn("function updateWorkSplitAdminVisibility", APP_JS)
        self.assertIn("/api/cases/work-split", APP_JS)
        self.assertIn("/api/work-assignees", APP_JS)
        self.assertIn("workAssigneeRequestSeq", APP_JS)
        self.assertIn("Object.entries(currentReviewFilterPayload())", APP_JS)
        self.assertIn("params.set(\"work_assignee\"", APP_JS)
        self.assertIn("baselines: selectedBaselineQueryValue()", APP_JS)
        self.assertIn(".review-tag-option-row", STYLES_CSS)
        self.assertIn('class="ui-lang-zh">模型标注</span>', INDEX_HTML)
        self.assertIn('class="ui-lang-en">Model label</span>', INDEX_HTML)
        self.assertNotIn('<span>人工标注</span>', INDEX_HTML)
        self.assertIn('params.set("model_label", modelLabel)', APP_JS)
        self.assertIn('url.searchParams.set("model_label", modelLabel)', APP_JS)
        self.assertIn("function renderReviewCatalogFilters", APP_JS)
        self.assertIn('data-placeholder="全部 GT"', INDEX_HTML)
        self.assertIn('id="analysisModelLabelFilter"', INDEX_HTML)
        self.assertIn('id="analysisSceneFilter"', INDEX_HTML)
        self.assertIn('id="analysisTriggerFilter"', INDEX_HTML)
        self.assertIn('id="analysisEgressFilter"', INDEX_HTML)
        self.assertIn('id="analysisPageSize"', INDEX_HTML)
        self.assertIn("function changeAnalysisPageSize", APP_JS)
        self.assertIn('id="analysisPageJump"', INDEX_HTML)
        self.assertIn('id="analysisPageJumpButton"', INDEX_HTML)
        self.assertIn("function jumpToAnalysisPage", APP_JS)
        self.assertIn('id="casePageSummary"', INDEX_HTML)
        self.assertIn('id="casePageJump"', INDEX_HTML)
        self.assertIn('id="casePageJumpButton"', INDEX_HTML)
        self.assertIn("function jumpToCasePage", APP_JS)
        self.assertIn('$("#casePageJumpButton")?.addEventListener("click", commitCasePageJump)', APP_JS)
        self.assertNotIn('casePageJump?.addEventListener("change", commitCasePageJump)', APP_JS)
        # Review, analysis, Trail exclusion candidates, and admin Run
        # comparison all expose the shared jump-to-page control.
        self.assertEqual(INDEX_HTML.count('class="page-jump-control"'), 4)
        self.assertIn("const requestedPage = state.reviewAnalysis.page", APP_JS)
        self.assertIn("state.reviewAnalysis.page = requestedPage", APP_JS)
        self.assertIn("page_count", APP_JS)
        self.assertIn("pageSize: state.reviewAnalysis.pageSize", APP_JS)
        self.assertIn('id="analysisClusterPanels"', INDEX_HTML)
        self.assertIn('id="analysisReviewStatusChart"', INDEX_HTML)
        self.assertIn('id="analysisReviewStatusSummary"', INDEX_HTML)
        self.assertIn('class="analysis-decision-grid"', INDEX_HTML)
        self.assertIn('id="analysisConfusionMatrix"', INDEX_HTML)
        self.assertIn('id="analysisConfusionSummary"', INDEX_HTML)
        self.assertIn("function renderAnalysisConfusion", APP_JS)
        self.assertIn("function bindAnalysisConfusionHover", APP_JS)
        self.assertIn("function bindAnalysisLinkedHover", APP_JS)
        self.assertIn("const item = pointerItem || focusItem", APP_JS)
        self.assertIn('root.addEventListener("pointerover", (event)', APP_JS)
        self.assertIn('root.addEventListener("focusin", (event)', APP_JS)
        self.assertIn('data-confusion-row=', APP_JS)
        self.assertIn('data-confusion-col=', APP_JS)
        self.assertIn('data-confusion-col="${columnIndex}" tabindex="0"', APP_JS)
        self.assertIn('label === "NONE" ? uiText("未输出", "NONE")', APP_JS)
        self.assertNotIn('id="analysisEvidenceClusters"', INDEX_HTML)
        self.assertNotIn('id="analysisAnnotationFilter"', INDEX_HTML)
        self.assertNotIn('id="analysisTagFilter"', INDEX_HTML)
        self.assertNotIn('id="analysisReasonClusters"', INDEX_HTML)
        self.assertNotIn('原因文本主题', INDEX_HTML)
        self.assertIn("function renderAnalysisClusterPanels", APP_JS)
        self.assertIn("function renderAnalysisReviewStatus", APP_JS)
        self.assertIn("function bindAnalysisReviewStatusHover", APP_JS)
        self.assertIn('data-review-status-key=', APP_JS)
        self.assertIn('role="listitem" tabindex="0"', APP_JS)
        self.assertIn("data.summary?.review_status_counts", APP_JS)
        self.assertIn('key: "needs_gt_review"', APP_JS)
        self.assertIn(".analysis-review-status-bar", STYLES_CSS)
        self.assertIn('grid-template-areas: "confusion status"', STYLES_CSS)
        self.assertIn('grid-template-areas: "status" "confusion"', STYLES_CSS)
        self.assertIn("minmax(610px, 2fr) minmax(280px, .78fr)", STYLES_CSS)
        self.assertIn("grid-template-rows: auto minmax(0, 1fr)", STYLES_CSS)
        self.assertIn(".analysis-cluster-card > .analysis-pie-groups", STYLES_CSS)
        self.assertNotIn("筛选用上方", APP_JS)
        self.assertNotIn("hover 查看详情", APP_JS)
        self.assertIn("function renderAnalysisPieSvg", APP_JS)
        self.assertIn("function analysisDonutSlicePath", APP_JS)
        self.assertIn("#24d3ef", APP_JS)
        self.assertIn("ANALYSIS_PIE_BASE_LIGHT", APP_JS)
        self.assertIn('html[data-color-theme="light"] .analysis-cluster-card', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .multi-filter-trigger', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .analysis-pie-center b', STYLES_CSS)
        self.assertIn("background: transparent", STYLES_CSS)
        self.assertIn("function renderMultiFilter", APP_JS)
        self.assertIn("模型结果 Review", APP_JS)
        self.assertIn("Model Result Review", APP_JS)
        self.assertIn("function formatModelConfidence", APP_JS)
        self.assertIn("function reviewAnnotationsForCurrentRun", APP_JS)
        self.assertIn("function reviewAnnotationsForAllRuns", APP_JS)
        self.assertIn("function inheritedHistoricalTagsForCurrentRun", APP_JS)
        self.assertIn("historicalReview", APP_JS)
        self.assertIn("function initialReviewTagsForCurrentRun", APP_JS)
        self.assertIn("data.labelled ?? data.reviewed_failures", APP_JS)
        self.assertIn("包含模型与 GT 一致的 Review", APP_JS)
        self.assertIn("条判错已复核", APP_JS)
        self.assertIn("across ${runCount} model runs", APP_JS)
        self.assertIn("data-selected-tags-section", APP_JS)
        self.assertIn("data-remove-review-tag", APP_JS)
        self.assertIn("data-selected-missing-evidence", APP_JS)
        self.assertIn("data-remove-review-evidence", APP_JS)
        self.assertIn("missing-evidence-selected-chip", APP_JS)
        # Missing-evidence chips use coral-orange, not no_assist amber.
        self.assertIn(
            ".tag-group-selected-chip.missing-evidence-selected-chip",
            STYLES_CSS,
        )
        self.assertIn("rgba(251,146,60", STYLES_CSS)
        # Screenshot drop zone: drag/drop + single form paste; browse only opens picker.
        self.assertIn('id="screenshotPasteZone"', APP_JS)
        self.assertIn("is-dragover", APP_JS)
        self.assertIn(".screenshot-paste-zone.is-dragover", STYLES_CSS)
        self.assertIn("imageFilesFromDataTransfer", APP_JS)
        self.assertIn('pasteZone.addEventListener("drop"', APP_JS)
        self.assertIn("拖拽到此处", APP_JS)
        # Exactly one Review evidence paste path; the second belongs to the
        # independent Markdown comment composer.
        self.assertIn('// Single form-level paste handler', APP_JS)
        self.assertEqual(APP_JS.count('addEventListener("paste"'), 2)
        self.assertIn('textarea.addEventListener("paste"', APP_JS)
        self.assertIn("event.stopPropagation()", APP_JS)
        # Shared anchored dropdowns: prefer down, flip by free space.
        self.assertIn("function positionAnchoredPanel", APP_JS)
        self.assertIn("function openAnchoredPanel", APP_JS)
        self.assertIn("function populateUiSelect", APP_JS)
        self.assertIn("function bindUiSelect", APP_JS)
        self.assertNotIn("function bindReviewStatusPicker", APP_JS)
        self.assertIn('id="expectedOutputInput"', APP_JS)
        self.assertIn("function syncExpectedOutputFromTags", APP_JS)
        self.assertIn("function expectedOutputSelectionState", APP_JS)
        self.assertIn('class="review-expected-output-heading"', APP_JS)
        self.assertIn('class="expected-output-rule"', APP_JS)
        self.assertIn("Tags 指向多个期望输出，请先消除冲突", APP_JS)
        self.assertIn('class="ui-select-inference-marker"', APP_JS)
        self.assertIn(".ui-select-option.is-inferred", STYLES_CSS)
        self.assertIn(".expected-output-picker .ui-select-summary", STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .ui-select-inference-marker', STYLES_CSS)
        self.assertIn("option.dataset.inferred =", APP_JS)
        self.assertIn('option.value === inference.value ? "true" : "false"', APP_JS)
        self.assertIn('expectedOutputInput.dataset.selectionSource = "manual"', APP_JS)
        self.assertIn('conflictKind === "selection"', APP_JS)
        self.assertIn("改回自动推断项或调整 Tags", APP_JS)
        self.assertIn("select.disabled = false", APP_JS)
        self.assertNotIn("select.disabled = true", APP_JS)
        self.assertIn('uiText("状态：选择冲突", "Status: Selection conflict")', APP_JS)
        self.assertIn(".review-expected-output-heading", STYLES_CSS)
        self.assertIn(".review-expected-output-hint.is-conflict", STYLES_CSS)
        self.assertIn("font-size: 12px", STYLES_CSS)
        self.assertIn("text-overflow: ellipsis; white-space: nowrap", STYLES_CSS)
        self.assertIn(".expected-output-rule-popover", STYLES_CSS)
        self.assertIn('false_trigger: "误触发"', APP_JS)
        self.assertIn('ra: "正确触发"', APP_JS)
        self.assertIn('no_assist: "无需协助"', APP_JS)
        self.assertIn('expected_output: $("#expectedOutputInput")?.value || ""', APP_JS)
        self.assertNotIn('review_status: $("#reviewStatusInput").value', APP_JS)
        self.assertIn('id="exportTrailExpectedOutputButton"', INDEX_HTML)
        self.assertIn("导出 GT 更新表", INDEX_HTML)
        self.assertNotIn("trail-export-button", INDEX_HTML)
        self.assertNotIn(".trail-export-button", STYLES_CSS)
        self.assertIn("GT 复核状态", INDEX_HTML)
        self.assertIn('id="reviewStatusFilter"', INDEX_HTML)
        self.assertIn('reviewStatus: getMultiFilterValues($("#reviewStatusFilter"))', APP_JS)
        self.assertIn('params.set("review_status", reviewStatus)', APP_JS)
        self.assertIn('review_status: joinFilterList(getMultiFilterValues($("#reviewStatusFilter")))', APP_JS)
        self.assertIn('id="expectedOutputPicker"', APP_JS)
        self.assertIn('bindUiSelect($("#expectedOutputPicker")', APP_JS)
        self.assertIn('pending: t("status.pending")', APP_JS)
        self.assertIn('reviewed: t("status.matches_gt")', APP_JS)
        self.assertIn('downloadReviewAnalysis("trail_xlsx")', APP_JS)
        self.assertIn("function renderAnalysisComparisonFilter", APP_JS)
        self.assertIn("function bindAnalysisComparisonPicker", APP_JS)
        self.assertIn('id="modelRunPicker"', INDEX_HTML)
        self.assertIn('id="analysisComparisonFilter"', INDEX_HTML)
        self.assertIn('class="multi-filter" id="analysisComparisonFilter"', INDEX_HTML)
        self.assertIn("detailMediaKindPicker", APP_JS)
        self.assertIn("Prefer down", APP_JS)
        # Fixed panels must use pixel width — % min-width becomes viewport width.
        self.assertIn("min-width: 0 !important", STYLES_CSS)
        self.assertIn("panel.style.minWidth = widthPx", APP_JS)
        self.assertIn('id="gatewayProviderPicker"', INDEX_HTML)
        self.assertIn("function bindGatewayProviderPicker", APP_JS)
        self.assertIn("function closeGatewayProviderPicker", APP_JS)
        self.assertIn("gateway-provider-option", APP_JS)
        self.assertIn(".gateway-provider-picker-panel", STYLES_CSS)
        self.assertIn("function bindSelectedReviewTagControls", APP_JS)
        self.assertIn("const section = container.dataset.selectedTagsSection", APP_JS)
        self.assertIn("REVIEW_DRAFT_STORAGE_PREFIX", APP_JS)
        self.assertIn("persistReviewDraft", APP_JS)
        self.assertIn("beforeunload", APP_JS)
        self.assertIn("if (runId) return bound;", APP_JS)
        self.assertIn("legacy unbound annotation", APP_JS)
        self.assertIn("clearReviewDraft(state.selectedId, payload.model_run_id)", APP_JS)
        self.assertIn("comparison-side-label", APP_JS)
        self.assertIn("state.reviewComparisonStatus = \"all\";", APP_JS)
        self.assertIn("const displayPrediction = prediction || (comparisonStatus === \"none\" ? \"NONE\" : \"\")", APP_JS)
        self.assertIn("comparison-summary > .label-正确触发", STYLES_CSS)
        self.assertIn("height: 20px; box-sizing: border-box", STYLES_CSS)
        self.assertIn("min-height: 20px; line-height: 20px", STYLES_CSS)
        self.assertIn("max-width: 100%; min-height: 20px", STYLES_CSS)
        self.assertIn("flex: 0 1 auto; max-width: 100%", STYLES_CSS)
        self.assertIn("position: absolute; right: 4px; top: 50%", STYLES_CSS)
        self.assertIn("padding-right: 17px", STYLES_CSS)
        self.assertIn('data-tag-section="${escapeHtml(section)}"', APP_JS)
        self.assertIn('analysis-chip.tag-chip[data-tag-group="false_trigger"]', STYLES_CSS)
        self.assertIn("visibility: hidden", STYLES_CSS)
        self.assertIn('[data-tag-group="false_trigger"]', STYLES_CSS)
        self.assertIn('[data-tag-group="true_trigger"]', STYLES_CSS)
        self.assertIn('[data-tag-group="ra"]', STYLES_CSS)
        self.assertIn('.app-shell.sidebar-collapsed .app-sidebar', STYLES_CSS)
        self.assertIn('background: var(--raised);', STYLES_CSS)
        self.assertIn('[data-tag-group="no_assist"]', STYLES_CSS)
        self.assertIn("model_run_id: state.reviewEditRunId", APP_JS)
        self.assertIn("expected_previous_annotation_id", APP_JS)
        self.assertIn("history-run", APP_JS)
        self.assertIn("toFixed(3)", APP_JS)
        self.assertIn("is-compact", STYLES_CSS)
        self.assertIn('data-open-history="review"', APP_JS)
        self.assertIn('id="gtFilter"', INDEX_HTML)
        self.assertIn('data-placeholder="全部 GT"', INDEX_HTML)
        self.assertIn("data-multi-select-all", APP_JS)
        self.assertIn("data-multi-invert", APP_JS)
        self.assertIn("data-multi-clear", APP_JS)
        self.assertIn(
            'return comparisonStatusParam(getMultiFilterValues(root));',
            APP_JS,
        )
        self.assertIn(
            'An existing filter with no checked values is an explicit "全部结果"',
            APP_JS,
        )
        self.assertIn(
            'Zero checked values is the user\'s explicit "全部结果" choice.',
            APP_JS,
        )
        self.assertIn('if (runId) {\n      url.searchParams.set("comparison", comparisonStatus);', APP_JS)
        self.assertNotIn('if (runId && comparisonStatus !== "all")', APP_JS)
        # loadRuns() and loadCases() overlap on first paint.  Until the native
        # select owns real options, its temporary empty value must not erase a
        # run supplied by the deep link.
        self.assertIn('const runFilter = $("#modelRunFilter");', APP_JS)
        self.assertIn('const runOptionsReady = Boolean(', APP_JS)
        self.assertIn('[...runFilter.options].some((option) => option.value)', APP_JS)
        self.assertIn('if (runOptionsReady)', APP_JS)
        self.assertIn('state.selectedRunId = runFilter.value;', APP_JS)
        self.assertIn("class=\"multi-filter\"", INDEX_HTML)
        self.assertIn(".analysis-pie-groups.dual", STYLES_CSS)
        self.assertIn(".analysis-pie-legend-line", STYLES_CSS)
        self.assertIn(".analysis-pie-group:has(.is-hover) .analysis-pie-slice:not(.is-hover)", STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .analysis-pie-slice.is-hover', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .analysis-pie-tooltip', STYLES_CSS)
        self.assertIn("function paintAnalysisFromCache", APP_JS)
        self.assertIn("function enterAnalysisPage", APP_JS)
        self.assertIn("function buildAnalysisQueryParams", APP_JS)
        self.assertIn("@keyframes analysis-pie-enter", STYLES_CSS)
        self.assertIn("analysis-pie-svg is-enter", APP_JS)
        self.assertIn("html.ra-ui-ready .app-frame", STYLES_CSS)
        self.assertIn('html[data-sidebar-pref="collapsed"] .app-frame', STYLES_CSS)
        self.assertIn("dataset.sidebarPref", INDEX_HTML)
        self.assertIn("function markUiReady", APP_JS)
        self.assertIn("function bindMobileFilterDrawers", APP_JS)
        self.assertIn("data-mobile-filter-toggle", INDEX_HTML)
        self.assertIn("data-mobile-filter-panel", INDEX_HTML)
        self.assertIn('id="mobileSidebarBackdrop"', INDEX_HTML)
        self.assertIn("mobileSidebarOpen", APP_JS)
        self.assertIn("isMobileSidebarViewport", APP_JS)
        self.assertIn("sidebar-mobile-open", APP_JS)
        self.assertIn("mobile-sidebar-backdrop", STYLES_CSS)
        self.assertIn("margin-left: 0;", STYLES_CSS)
        self.assertIn(".review-tag-groups { grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 6px; }", STYLES_CSS)
        self.assertIn(".run-source-tab:not(.active) > span:nth-child(2)", STYLES_CSS)
        self.assertIn(".run-source-tab.active {", STYLES_CSS)
        self.assertIn('title="Model result file"', INDEX_HTML)
        self.assertIn('class="ui-lang-zh">模型结果文件</strong>', INDEX_HTML)
        self.assertIn(".mobile-filter-bar", STYLES_CSS)
        # Phone topbar: title row separate from dataset picker so h1 never stacks vertically.
        self.assertIn('"brand actions"', STYLES_CSS)
        self.assertIn('"baselines baselines"', STYLES_CSS)
        self.assertIn('"metrics metrics"', STYLES_CSS)
        # Metrics use equal grid cells (not clipped horizontal scroll).
        self.assertIn("Equal 4 columns", STYLES_CSS)
        self.assertIn("grid-template-columns: repeat(4, minmax(0, 1fr))", STYLES_CSS)
        # Narrow desktop also wraps metrics; cells are centered.
        self.assertIn("max-width: 1200px", STYLES_CSS)
        self.assertIn("align-items: center; justify-content: center", STYLES_CSS)
        self.assertIn("text-align: center", STYLES_CSS)
        self.assertIn("env(safe-area-inset-top", STYLES_CSS)
        self.assertIn("#dce6f2", STYLES_CSS)
        self.assertIn(".multi-filter-trigger", STYLES_CSS)
        self.assertIn(".multi-filter-option {", STYLES_CSS)
        self.assertIn("select option { color: #eef4fa; background: #111a27; font-weight: 560; }", STYLES_CSS)
        self.assertIn(
            ".multi-filter-option span { min-width: 0; overflow: hidden; color: #f2f6fb; text-overflow: ellipsis; white-space: nowrap; }",
            STYLES_CSS,
        )
        self.assertIn(".tag-option-check span", STYLES_CSS)
        self.assertIn(".multi-filter-option:has(input:checked)", STYLES_CSS)
        self.assertIn(".multi-filter.is-disabled { pointer-events: none; }", STYLES_CSS)
        self.assertIn("color: #ffffff", STYLES_CSS)
        self.assertIn(".multi-filter-action", STYLES_CSS)
        self.assertIn('id="resetReviewAnalysisButton"', INDEX_HTML)
        self.assertIn('class="ui-lang-zh">重置</span>', INDEX_HTML)
        self.assertIn("grid-template-columns: repeat(2, minmax(0, 1fr))", STYLES_CSS)

    def test_batch_gateway_aligns_to_form_and_catalog_scrolls(self) -> None:
        self.assertIn(".batch-page-grid { align-items: stretch; }", STYLES_CSS)
        self.assertIn(".batch-page-grid > .tool-form { align-self: start; }", STYLES_CSS)
        self.assertIn("height: auto; min-height: 0", STYLES_CSS)
        self.assertIn("contain: size; overflow: hidden", STYLES_CSS)
        self.assertIn("contain: none; overflow: visible", STYLES_CSS)
        self.assertIn("grid-template-rows: auto auto auto auto minmax(0, 1fr) auto", STYLES_CSS)
        self.assertIn("overscroll-behavior: contain; scrollbar-gutter: stable", STYLES_CSS)

    def test_batch_model_picker_uses_workspace_dropdown(self) -> None:
        self.assertIn('id="gatewayModelPicker"', INDEX_HTML)
        self.assertIn('id="gatewayModelPickerTrigger"', INDEX_HTML)
        self.assertIn('id="gatewayModelPickerPanel"', INDEX_HTML)
        self.assertIn('id="gatewayProviderPicker"', INDEX_HTML)
        self.assertIn('class="gateway-model-native-select"', INDEX_HTML)
        self.assertIn("data-gateway-picker-model", APP_JS)
        self.assertIn("bindGatewayModelPicker", APP_JS)
        self.assertIn("bindGatewayProviderPicker", APP_JS)
        self.assertIn("openAnchoredPanel", APP_JS)
        self.assertIn("gateway-model-picker-panel", STYLES_CSS)
        self.assertIn("gateway-model-picker-trigger", STYLES_CSS)
        self.assertIn("gateway-provider-picker-panel", STYLES_CSS)
        self.assertIn("width: max(100%, 200px)", STYLES_CSS)
        self.assertIn('title="${escapeHtml(title)}"', APP_JS)
        self.assertIn("focusMediaSurface", APP_JS)
        self.assertIn("kindSelect.blur()", APP_JS)
        self.assertIn("seekTo(target)", APP_JS)
        self.assertIn('event.target.matches("[data-video-seek]")', APP_JS)
        self.assertIn("requestVideoFrameCallback", APP_JS)
        self.assertIn("window.requestAnimationFrame(() =>", APP_JS)
        self.assertIn('hasPreviousReview ? previous.missing_evidence || [] : []', APP_JS)
        self.assertNotIn('hasPreviousReview ? previous.missing_evidence || [] : ["routing_direction"]', APP_JS)

    def test_review_filter_type_matches_analysis_filter_type(self) -> None:
        self.assertIn("function scheduleReviewFilterReload", APP_JS)
        self.assertNotIn("const scheduleReviewFilterReload", APP_JS)
        self.assertLess(
            APP_JS.index("function scheduleReviewFilterReload"),
            APP_JS.index("function bindEvents"),
        )
        self.assertIn(".review-filters label { min-width: 0; display: grid; gap: 3px; color: var(--faint); font-size: 11px; }", STYLES_CSS)
        self.assertIn(".review-filters input, .review-filters select { min-width: 0; height: 32px; padding: 5px 29px 5px 7px; font-size: 12px; }", STYLES_CSS)
        self.assertIn("repeat(6, minmax(84px, .58fr)) auto", STYLES_CSS)
        self.assertIn("filter-submit { height: 32px; padding: 5px 8px; white-space: nowrap; }", STYLES_CSS)
        self.assertIn(".analysis-filters label { min-width: 0; display: grid; gap: 3px; color: var(--faint); font-size: 11px; }", STYLES_CSS)
        self.assertIn(".analysis-filters input, .analysis-filters select { height: 34px; min-width: 0; padding: 5px 29px 5px 8px; font-size: 12px; }", STYLES_CSS)
        self.assertIn('id="analysisExclusionFilter"', INDEX_HTML)
        self.assertIn('id="reviewExclusionFilter"', INDEX_HTML)
        self.assertIn('data-placeholder="全部（含问题排除）"', INDEX_HTML)
        self.assertIn("function selectedAnalysisExclusionFilter", APP_JS)
        self.assertIn("function selectedReviewExclusionFilter", APP_JS)
        self.assertIn('params.set("exclusion", exclusion)', APP_JS)
        self.assertIn('exclusion: selectedAnalysisExclusionFilter()', APP_JS)
        self.assertIn('selectedReviewExclusionFilter()', APP_JS)
        self.assertIn(".analysis-exclusion-filter", STYLES_CSS)

    def test_system_status_lead_keeps_only_refresh_actions(self) -> None:
        self.assertNotIn("只读查看服务、数据库、备份、容量与外部依赖", INDEX_HTML)
        self.assertNotIn("Read-only service, database, backup", INDEX_HTML)
        self.assertIn(".system-status-lead { min-height: 46px; justify-content: flex-end; }", STYLES_CSS)

    def test_read_only_mode_blocks_mutating_frontend_requests(self) -> None:
        self.assertIn('state.session?.read_only', APP_JS)
        self.assertIn('const isMutation = ["POST", "PUT", "PATCH", "DELETE"].includes(method)', APP_JS)
        self.assertIn('document.documentElement.dataset.accessMode', APP_JS)
        self.assertIn('"X-RA-Triage-Request": "browser-v1"', APP_JS)

    def test_tags_have_shared_scene_catalog_and_user_access_has_a_separate_admin_page(self) -> None:
        self.assertNotIn('id="manageReviewTagsButton"', INDEX_HTML)
        self.assertNotIn('id="tagManagerDialog"', INDEX_HTML)
        self.assertIn('/api/review-tags', APP_JS)
        self.assertIn('id="userManagementNavButton"', INDEX_HTML)
        self.assertIn('data-app-path="/users"', INDEX_HTML)
        self.assertIn('id="userManagementPage"', INDEX_HTML)
        self.assertIn("userManagementNav.hidden = !state.session.is_admin", APP_JS)
        self.assertIn('api("/api/access-users"', APP_JS)
        self.assertNotIn('id="addSceneTagButton"', APP_JS)
        self.assertIn(".access-panel { width: min(980px, 100%); max-width: 980px; margin-inline: auto;", STYLES_CSS)

    def test_review_panel_separates_issue_tags_and_model_error(self) -> None:
        self.assertIn("function renderReviewTagGroups", APP_JS)
        self.assertIn('class="review-section issue-tag-section"', APP_JS)
        self.assertIn('class="review-section model-error-section"', APP_JS)
        self.assertIn('class="review-tag-dropdown review-dropdown"', APP_JS)
        self.assertIn('data-tag-summary=', APP_JS)
        self.assertIn('data-tag-group=', APP_JS)
        self.assertIn('data-tag-dropdown-shortcut=', APP_JS)
        self.assertIn('const REVIEW_TAG_GROUP_SHORTCUTS = Object.freeze({', APP_JS)
        self.assertIn('q: "environment"', APP_JS)
        self.assertIn('w: "self_intent"', APP_JS)
        self.assertIn('a: "false_trigger"', APP_JS)
        self.assertIn('s: "true_trigger"', APP_JS)
        self.assertIn('z: "ra"', APP_JS)
        self.assertIn('x: "no_assist"', APP_JS)
        self.assertIn('function bindReviewKeyboardShortcuts()', APP_JS)
        self.assertIn('data-review-tag-option-shortcut=', APP_JS)
        self.assertIn('"9", "0", "-", "="', APP_JS)
        self.assertIn("REVIEW_TAG_OPTION_SHORTCUTS.includes(key)", APP_JS)
        self.assertIn('key === "[" || key === "]"', APP_JS)
        self.assertIn('class="review-control-shortcut review-nav-shortcut"', APP_JS)
        self.assertIn('.review-control-shortcut {', STYLES_CSS)
        self.assertIn("grid-template-columns: minmax(0, 1fr) auto auto", STYLES_CSS)
        self.assertIn("text-overflow: ellipsis; white-space: nowrap", STYLES_CSS)
        self.assertIn("min-width: 67px; display: inline-flex", STYLES_CSS)
        self.assertNotIn("review-section-kicker", APP_JS)
        self.assertNotIn("review-section-help", APP_JS)
        self.assertNotIn("review-scope-note", APP_JS)
        self.assertIn("function currentRunOutputMarkup", APP_JS)
        self.assertIn("当前 Run Reason", APP_JS)
        self.assertNotIn("完整 Config", APP_JS)
        self.assertNotIn("原始输出对象", APP_JS)
        self.assertIn('id="reviewExcludeInput"', APP_JS)
        self.assertIn('class="ui-lang-zh">应该排除</strong>', APP_JS)
        self.assertIn('class="ui-lang-en">Exclude</strong>', APP_JS)
        self.assertNotIn('<strong>是否应该排除</strong>', APP_JS)
        self.assertNotIn('class="review-title"', APP_JS)
        self.assertIn("Issue 标签", APP_JS)
        self.assertIn("Issue tags", APP_JS)
        self.assertIn("模型结果 Review", APP_JS)
        self.assertIn("Model Result Review", APP_JS)
        self.assertNotIn("<h2>模型判错</h2>", APP_JS)
        self.assertIn('data-open-history="review"', APP_JS)
        self.assertNotIn('class="review-history-toggle"', APP_JS)
        self.assertIn(".review-section-heading h2 { color: var(--text); font-size: 16px; }", STYLES_CSS)
        self.assertIn("is_excluded: Boolean($(\"#reviewExcludeInput\")?.checked)", APP_JS)
        app_root = Path(__file__).resolve().parents[1].joinpath("app")
        main_py = "\n".join(
            p.read_text(encoding="utf-8")
            for p in [
                app_root / "runtime.py",
                app_root / "http_support.py",
                app_root / "main.py",
            ]
        )
        self.assertIn('"section": "scene"', main_py)
        self.assertIn('"section": "egress"', main_py)
        self.assertIn('"section": "interaction_decision"', main_py)
        self.assertIn('"group": "environment"', main_py)
        self.assertIn('"group": "self_intent"', main_py)
        self.assertIn('"group": "false_trigger"', main_py)
        self.assertIn('"group": "true_trigger"', main_py)
        # Axis/group chrome uses message-catalog keys (I18n); domain option labels stay catalog Chinese.
        self.assertIn('t("tag.env")', APP_JS)
        self.assertIn('t("tag.ego_intent")', APP_JS)
        self.assertIn('t("tag.scene")', APP_JS)
        self.assertIn('t("tag.trigger")', APP_JS)
        self.assertIn('t("tag.false_trigger")', APP_JS)
        self.assertIn('t("tag.should_trigger")', APP_JS)
        self.assertIn('t("tag.correct_trigger")', APP_JS)
        self.assertIn('"tag.env": "环境"', APP_JS)
        self.assertIn('"tag.ego_intent": "自车意图"', APP_JS)
        self.assertIn('"tag.false_trigger": "误触发"', APP_JS)
        self.assertIn(
            ".review-tag-groups { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 5px;",
            STYLES_CSS,
        )
        self.assertIn(".review-tag-dropdown > summary", STYLES_CSS)
        self.assertIn('id="reviewTagCreateDialog"', INDEX_HTML)
        self.assertIn('id="reviewTagCreateForm"', INDEX_HTML)
        self.assertIn('id="reviewTagCreateMode"', INDEX_HTML)
        self.assertIn("function openReviewTagEditorDialog", APP_JS)
        self.assertIn('mode: "edit"', APP_JS)
        self.assertIn("openDialog(\"reviewTagCreateDialog\")", APP_JS)
        self.assertIn("class=\"tag-group-trailing\"", APP_JS)
        self.assertIn("class=\"tag-group-chevron\"", APP_JS)
        self.assertNotIn('window.prompt("场景标签标题"', APP_JS)
        self.assertIn('id="missingEvidenceCreateDialog"', INDEX_HTML)
        self.assertIn("function openMissingEvidenceEditorDialog", APP_JS)
        self.assertIn("left: -1px; right: -1px; z-index: 22", STYLES_CSS)
        self.assertIn("display: grid; grid-template-columns: minmax(0, 1fr); gap: 4px", STYLES_CSS)
        self.assertIn("width: 100%; min-width: 0; max-width: 100%; justify-content: flex-start", STYLES_CSS)
        self.assertNotIn("grid-template-columns: repeat(2, minmax(min-content, max-content))", STYLES_CSS)
        self.assertNotIn(".review-tag-dropdown .review-tag-options .tag-option:last-child:nth-child(odd)", STYLES_CSS)
        self.assertNotIn("width: max-content; min-width: calc(100% + 2px); max-width: min(320px, calc(100vw - 24px))", STYLES_CSS)
        self.assertNotIn(".review-tag-groups > .review-tag-dropdown:nth-child(2) .review-tag-options", STYLES_CSS)
        self.assertNotIn('class="custom-tag-create"', APP_JS)
        self.assertNotIn(".custom-tag-create { position: sticky;", STYLES_CSS)
        self.assertIn("overflow: hidden; text-overflow: ellipsis; white-space: nowrap;", STYLES_CSS)
        self.assertIn("text-overflow: ellipsis; white-space: nowrap;", STYLES_CSS)
        self.assertIn('textarea id="annotationNote" rows="2"', APP_JS)
        self.assertIn(".review-reason textarea { min-height: 54px; height: 54px;", STYLES_CSS)
        self.assertIn(".review-section { display: grid; gap: 7px; padding: 0; border: 0", STYLES_CSS)
        self.assertIn('data-open-review-tag-creator', APP_JS)
        # All six managed Issue-tag axes render the ＋ create control.
        self.assertIn('class="tag-catalog-add-button"', APP_JS)
        self.assertIn("function reviewTagGroupLabel", APP_JS)
        self.assertIn('key === "false_trigger"', APP_JS)
        self.assertIn('key === "true_trigger"', APP_JS)
        self.assertIn('key === "ra"', APP_JS)
        self.assertIn('key === "no_assist"', APP_JS)
        self.assertIn("暂无标签，点 ＋ 添加", APP_JS)
        self.assertIn("REVIEW_TAG_MANAGED_GROUPS", main_py)
        self.assertIn('"false_trigger": "interaction_decision"', main_py)
        self.assertIn('"ra": "egress"', main_py)
        self.assertIn("tag-option-menu-toggle", APP_JS)
        self.assertIn("data-tag-menu-toggle", APP_JS)
        self.assertIn("function closeAllTagOptionMenus", APP_JS)
        self.assertIn("function positionTagOptionMenuPanel", APP_JS)
        self.assertIn("function resetTagOptionMenuPanel", APP_JS)
        self.assertIn("is-drop-up", APP_JS)
        self.assertIn("is-fixed-menu", APP_JS)
        self.assertIn(".tag-option-menu-panel.is-drop-up", STYLES_CSS)
        self.assertIn(".tag-option-menu-panel.is-fixed-menu", STYLES_CSS)
        self.assertIn('scheduleAnalysisFilterReload', APP_JS)
        self.assertNotIn('<button class="button button-primary" type="submit">应用</button>', INDEX_HTML)
        self.assertIn(".tag-catalog-add-button", STYLES_CSS)
        self.assertIn(".tag-option-menu-panel", STYLES_CSS)
        self.assertIn(".tag-option-with-menu", STYLES_CSS)
        self.assertIn('api("/api/review-tags"', APP_JS)
        self.assertIn('"key": "environment_other"', main_py)

    def test_review_dropdowns_close_when_focus_leaves_the_control(self) -> None:
        self.assertIn("function closeAllReviewDropdowns", APP_JS)
        self.assertIn("function positionReviewDropdownPanel", APP_JS)
        self.assertIn("function prepareReviewDropdownPanelForMeasure", APP_JS)
        self.assertIn("const desiredHeight = Math.min(naturalH, Math.floor(vh * 0.55), 420);", APP_JS)
        self.assertIn("spaceBelow < desiredHeight && spaceAbove > spaceBelow", APP_JS)
        self.assertIn("function prepareTagOptionMenuPanelForMeasure", APP_JS)
        self.assertIn("is-positioned", APP_JS)
        self.assertIn(":not(.is-positioned)", STYLES_CSS)
        # Place in the same tick as open — no rAF that paints absolute-down first.
        self.assertIn("prepareReviewDropdownPanelForMeasure(panel);\n      positionReviewDropdownPanel(dropdown);", APP_JS)
        self.assertIn("prepareTagOptionMenuPanelForMeasure(panel);\n        positionTagOptionMenuPanel(menu);", APP_JS)
        self.assertIn('summary?.addEventListener(\n      "pointerdown"', APP_JS)
        self.assertIn(".tag-option-menu-panel:not([hidden]):not(.is-positioned)", STYLES_CSS)

        self.assertIn("function resetReviewDropdownPanel", APP_JS)
        self.assertIn("is-fixed-dropdown", APP_JS)
        self.assertIn(".is-fixed-dropdown", STYLES_CSS)
        evidence_start = APP_JS.index('class="evidence-dropdown review-dropdown review-tag-dropdown"')
        evidence_end = APP_JS.index('id="missingEvidenceOptions"', evidence_start)
        evidence_header = APP_JS[evidence_start:evidence_end]
        self.assertIn('data-open-missing-evidence-creator', evidence_header)
        self.assertLess(
            evidence_header.index('data-open-missing-evidence-creator'),
            evidence_header.index('id="evidenceSummaryCount"'),
        )

        self.assertIn("function bindReviewDropdownDismiss", APP_JS)
        self.assertIn("reviewDropdownDismissBound", APP_JS)
        self.assertIn('target?.closest(".review-dropdown")', APP_JS)
        self.assertIn('if (event.key === "Escape") closeAllReviewDropdowns()', APP_JS)

    def test_model_source_preview_supports_excel_files(self) -> None:
        app_root = Path(__file__).resolve().parents[1].joinpath("app")
        main_py = "\n".join(
            p.read_text(encoding="utf-8")
            for p in sorted(app_root.rglob("*.py"))
        )
        self.assertIn('preview_supported = suffix in {".json", ".csv", ".xlsx", ".xlsm"}', main_py)
        self.assertIn('if suffix not in {".json", ".csv", ".xlsx", ".xlsm"}:', main_py)
        self.assertIn("当前仅支持在页面内预览 CSV / JSON / XLSX", main_py)
        self.assertIn("CSV / JSON / XLSX 页面预览", APP_JS)

    def test_detail_media_reuses_frame_timeline_outside_modal(self) -> None:
        self.assertIn("function mediaTimelineMarkup", APP_JS)
        self.assertIn('data-detail-media-frame', APP_JS)
        self.assertIn('mediaTimelineMarkup(activeFrames, index, "detail-media-frame")', APP_JS)
        self.assertIn('mediaTimelineButtonsMarkup(frames, state.media.index, "media-frame")', APP_JS)
        self.assertIn(".detail-media-timeline", STYLES_CSS)

    def test_review_save_updates_history_without_reselecting_the_case(self) -> None:
        save_start = APP_JS.index("async function saveAnnotation(event)")
        save_end = APP_JS.index("\nfunction mediaFrames", save_start)
        save_body = APP_JS[save_start:save_end]
        self.assertIn("updateReviewHistory(state.selectedCase)", save_body)
        self.assertIn("refreshReviewDerivedData()", save_body)
        self.assertNotIn("selectCase(", save_body)

    def test_native_buttons_keep_their_entire_surface_clickable(self) -> None:
        self.assertIn('id="reviewSaveButton"', APP_JS)
        self.assertIn('class="button button-primary full-width review-save-button"', APP_JS)
        self.assertIn(".review-save-button {", STYLES_CSS)
        self.assertIn("button > * { pointer-events: none; }", STYLES_CSS)

    def test_review_catalog_creator_buttons_keep_the_compact_summary_order(self) -> None:
        evidence_start = APP_JS.index('class="evidence-dropdown review-dropdown review-tag-dropdown"')
        evidence_end = APP_JS.index('id="missingEvidenceOptions"', evidence_start)
        evidence_header = APP_JS[evidence_start:evidence_end]
        self.assertLess(
            evidence_header.index('data-open-missing-evidence-creator'),
            evidence_header.index("</summary>"),
        )
        self.assertIn(".review-tag-dropdown > summary .tag-catalog-add-button", STYLES_CSS)
        self.assertIn('target?.closest(".tag-catalog-add-button")', APP_JS)
        self.assertIn('if (target?.closest(".tag-catalog-add-button")) event.preventDefault();', APP_JS)

    def test_missing_evidence_creation_uses_shared_catalog_and_hint(self) -> None:
        self.assertIn('id="missingEvidenceCreateHint"', INDEX_HTML)
        self.assertIn('api("/api/missing-evidence"', APP_JS)
        self.assertNotIn("创建后所有用户、所有 Issue 都可见", APP_JS)
        self.assertIn("function missingEvidenceOptionMarkup", APP_JS)
        self.assertIn('data-edit-missing-evidence=', APP_JS)
        self.assertIn('data-delete-missing-evidence=', APP_JS)
        self.assertIn('data-open-missing-evidence-creator', APP_JS)
        self.assertIn("tag-option-with-menu evidence-tag-option", APP_JS)
        self.assertIn('method: "PUT"', APP_JS)
        self.assertIn('method: "DELETE"', APP_JS)
        self.assertIn("loadConfig()", APP_JS[APP_JS.index("async function refreshChangedData"):])
        self.assertIn(".evidence-option-deleted", STYLES_CSS)

    def test_review_mutations_acknowledge_server_revision_and_keep_form_dom(self) -> None:
        self.assertIn("function acknowledgeLocalChange(payload)", APP_JS)
        self.assertIn("acknowledgeLocalChange(result)", APP_JS)
        delete_start = APP_JS.index("async function deleteAnnotationVersion")
        delete_end = APP_JS.index("\nfunction renderReview", delete_start)
        delete_body = APP_JS[delete_start:delete_end]
        self.assertIn("syncReviewFormFromCase(caseData)", delete_body)
        self.assertNotIn("renderReview(caseData)", delete_body)

    def test_issue_detail_exposes_optional_ra_recording_and_event_links(self) -> None:
        self.assertIn("external_links", APP_JS)
        self.assertIn("RA 录屏 ↗", APP_JS)
        self.assertIn("RA Event ↗", APP_JS)
        self.assertIn("function openRaEventDialog(caseData)", APP_JS)
        self.assertIn('data-open-ra-event', APP_JS)
        self.assertIn("detailExternalLinks", APP_JS)
        self.assertIn('"/api/cases/" + encodeURIComponent(issueId) + "/trail-metadata"', APP_JS)
        self.assertIn("startTrailDetailMetadata(issueId, requestSeq)", APP_JS)
        self.assertIn("applyTrailDetailMetadata(result, issueId, requestSeq)", APP_JS)
        self.assertIn("externalLinks.ares_trip_id", APP_JS)
        self.assertIn("externalLinks.ares_timestamp_ms", APP_JS)
        self.assertIn("dashboard_should_exclude", APP_JS)
        self.assertNotIn("reviewExcludeTrailHint", APP_JS)
        self.assertNotIn("Trail info marks this Issue for exclusion", APP_JS)
        self.assertIn('id="raEventDialog"', INDEX_HTML)
        self.assertIn('id="raEventTableBody"', INDEX_HTML)
        self.assertIn("ra-event-table", STYLES_CSS)

    def test_issue_detail_keeps_media_first_and_avoids_loading_flash(self) -> None:
        preferred_start = APP_JS.index("function preferredMediaKind(caseData)")
        bev_offset = APP_JS.index("if (caseData?.assets?.frames?.length)", preferred_start)
        video_offset = APP_JS.index("if (caseData?.assets?.video?.url)", preferred_start)
        self.assertLess(video_offset, bev_offset)
        self.assertIn('preload="metadata"', APP_JS)
        self.assertNotIn('posterUrl: frames[heroFrameIndex(frames)]?.url || ""', APP_JS)
        self.assertNotIn('posterUrl: bev[heroFrameIndex(bev)]?.url || ""', APP_JS)
        self.assertIn('poster="${escapeHtml(posterUrl)}"', APP_JS)
        self.assertIn('?include_media=false', APP_JS)
        self.assertIn('/api/cases/${encodeURIComponent(issueId)}/media', APP_JS)
        self.assertIn("async function loadDeferredCaseMedia", APP_JS)
        self.assertIn('media_status === "pending"', APP_JS)
        self.assertIn("const hadDetail = Boolean(state.selectedCase)", APP_JS)
        self.assertIn("}, 140);", APP_JS)

    def test_gallery_refresh_reuses_loaded_thumbnails_without_transitions(self) -> None:
        self.assertIn("function caseGallerySignature(items)", APP_JS)
        self.assertIn("function reuseGalleryThumbnails(list, previousThumbnails)", APP_JS)
        self.assertIn("previous.image.naturalWidth <= 0", APP_JS)
        self.assertNotIn("transition: border-color 150ms ease-out, background 150ms ease-out", STYLES_CSS)

    def test_media_switch_preloads_and_decodes_before_replacing_the_view(self) -> None:
        self.assertIn("function preloadDetailImage(caseData, kind, index, root, onReady)", APP_JS)
        self.assertIn("image.decode", APP_JS)
        self.assertIn('root.setAttribute("aria-busy", "true")', APP_JS)
        self.assertIn("preloadDetailImage(caseData, kind, nextIndex, root", APP_JS)
        self.assertIn("function preloadMediaDialogImage(url, onReady)", APP_JS)
        self.assertIn('previewImage.dataset.mediaUrl = targetUrl', APP_JS)
        self.assertIn("function applyDetailImageFrame(root, caseData, kind, index, loadedImage = null)", APP_JS)
        self.assertIn("image.before(nextImage)", APP_JS)
        self.assertIn('nextImage.style.visibility = "visible"', APP_JS)
        self.assertIn('image.style.zIndex = "1"', APP_JS)
        self.assertIn("window.requestAnimationFrame(() => window.requestAnimationFrame(commit))", APP_JS)
        self.assertIn('root.querySelectorAll("#detailMediaPreviousButton, #detailMediaNextButton")', APP_JS)
        self.assertNotIn('root.querySelectorAll("button, select")', APP_JS)
        self.assertIn('class="detail-media-image"', APP_JS)
        self.assertIn(".hero-media-button img.detail-media-image", STYLES_CSS)
        self.assertNotIn(".detail-media-image { opacity: 0", STYLES_CSS)
        self.assertNotIn(".issue-thumbnail img.is-loaded", STYLES_CSS)
        self.assertNotIn(".issue-card:hover .issue-thumbnail img", STYLES_CSS)

    def test_review_history_exposes_explicit_delete_action(self) -> None:
        self.assertIn('data-delete-annotation="${escapeHtml(annotation.id)}"', APP_JS)
        self.assertIn('method: "DELETE"', APP_JS)
        self.assertIn("deleteAnnotationVersion(caseData", APP_JS)
        self.assertIn(".history-delete-button", STYLES_CSS)


    def test_detail_queue_index_is_editable_for_jump(self) -> None:
        self.assertIn('id="detailQueueIndexInput"', APP_JS)
        self.assertIn("function jumpToQueueIndex", APP_JS)
        self.assertIn("function bindDetailQueueIndexJump", APP_JS)
        self.assertIn(".detail-queue-index-input", STYLES_CSS)
        self.assertIn("manual-triage-278", APP_ENTRY_JS)

    def test_multi_issue_query_contract(self) -> None:
        self.assertIn('id="openIssueQueryButton"', INDEX_HTML)
        self.assertIn('id="issueQueryDialog"', INDEX_HTML)
        self.assertIn('id="issueQueryInput"', INDEX_HTML)
        self.assertIn("parseIssueIdsInput", APP_JS)
        self.assertIn("issue_ids", APP_JS)
        self.assertIn('"issue-query.js"', APP_ENTRY_JS)
        self.assertIn("state.reviewIssueIds", APP_JS)

    def test_intent_labeling_isolated_dynamic_timeline_contract(self) -> None:
        self.assertIn('data-page-target="intent"', INDEX_HTML)
        self.assertIn('data-page="intent"', INDEX_HTML)
        self.assertIn('path: "/intent-labeling"', APP_JS)
        self.assertIn('"intent-labeling.js"', APP_ENTRY_JS)
        self.assertIn("state.intentLabeling", APP_JS)
        self.assertIn("data-intent-aggregate-axis", INDEX_HTML)
        self.assertIn("data-intent-frame-axis", INDEX_HTML)
        self.assertIn("function intentRestoreBatchPrefill", APP_JS)
        self.assertIn("expected_revision_id: intent.revisionId", APP_JS)
        self.assertIn("savedEditVersion = intent.editVersion", APP_JS)
        self.assertIn("await intent.savePromise", APP_JS)
        self.assertIn("event.code", APP_JS)
        self.assertIn("Digit7", APP_JS)
        self.assertIn("IntersectionObserver", APP_JS)
        self.assertIn("function intentLabelSummary", APP_JS)
        self.assertIn("function intentSetMediaZoom", APP_JS)
        self.assertIn('data-intent-media-controls="camera"', INDEX_HTML)
        self.assertIn('placeholder="例如 cn28896325"', INDEX_HTML)
        self.assertIn("批量预填（全部时间点）", INDEX_HTML)
        self.assertNotIn("同步时间点", INDEX_HTML)
        self.assertIn("aspect-ratio: 16 / 9", STYLES_CSS)
        self.assertIn("object-fit: cover", STYLES_CSS)
        self.assertIn("grid-template-rows: repeat(2, 60px)", STYLES_CSS)
        self.assertNotIn(".intent-media-stage img { width: 100%; height: 100%; display: block; object-fit: contain", STYLES_CSS)

    def test_reviewer_filter_survives_top_bar_and_collaboration_refresh(self) -> None:
        self.assertIn("function reviewerFilterSelection(page)", APP_JS)
        self.assertIn("function persistReviewerFilterRoute(page, values)", APP_JS)
        self.assertIn("function reviewerFilterSelections()", APP_JS)
        self.assertIn("function reviewerOptionsWithSelected(options, selected)", APP_JS)
        self.assertIn("Current filter", APP_JS)
        # Persist the active custom-filter selection before the asynchronous
        # facet reload so an Issue detail URL retains reviewer=jasperchen.
        self.assertIn('persistReviewerFilterRoute("review", values)', APP_JS)
        self.assertIn('persistReviewerFilterRoute("analysis", values)', APP_JS)
        self.assertIn('reviewerFilterSelection("review")', APP_JS)
        self.assertIn('reviewerFilterSelection("analysis")', APP_JS)
        self.assertIn("const reviewerSelections = typeof reviewerFilterSelections", APP_JS)
        self.assertIn("loadReviewers(reviewerSelections)", APP_JS)
        # A deliberately empty Run picker is a real filter state.  Refreshing
        # must not silently switch to the default Run and replace its reviewer
        # facet with a different set of names.
        self.assertIn("await loadRuns({ preserveEmpty: !state.selectedRunId });", APP_JS)

    def test_work_assignee_filter_survives_custom_facet_rebuild(self) -> None:
        self.assertIn("function workAssigneeRouteSelection()", APP_JS)
        self.assertIn("function workAssigneeFilterSelection()", APP_JS)
        self.assertIn("function persistWorkAssigneeFilterRoute(values)", APP_JS)
        self.assertIn("function workAssigneeOptionsWithSelected(options, selected)", APP_JS)
        # The canonical URL is the fallback while the custom multi-select has
        # no inputs during an async work-assignee facet refresh.
        self.assertIn('params.get("work_assignee") || params.get("assignee")', APP_JS)
        self.assertIn('persistWorkAssigneeFilterRoute(values)', APP_JS)
        self.assertIn('persistWorkAssigneeFilterRoute([name])', APP_JS)
        self.assertIn('persistWorkAssigneeFilterRoute?.([])', APP_JS)
        self.assertIn('workAssigneeFilterSelection()', APP_JS)
        self.assertIn('renderWorkAssigneeFilter(workAssigneeFilterSelection())', APP_JS)

    def test_trail_update_exposes_safe_preview_and_commit_contract(self) -> None:
        self.assertIn('id="trailUpdateCommitButton"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateCapability"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateSafetyBadge"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateLoadButton"', INDEX_HTML)
        self.assertIn('id="trailUpdateResults"', INDEX_HTML)
        self.assertIn('id="trailUpdateResults" aria-label="Trail update results" hidden', INDEX_HTML)
        self.assertIn("ra_stuck_auto_result", INDEX_HTML)
        self.assertIn("ra_stuck_auto_result_info", INDEX_HTML)
        self.assertIn("setTrailAttributeUpdatePreviewVisible", APP_JS)
        self.assertIn(".trail-update-onboarding", STYLES_CSS)
        self.assertIn("commitTrailAttributeUpdate", APP_JS)
        self.assertIn('id="trailUpdateConfirmDialog"', INDEX_HTML)
        self.assertIn('id="trailUpdateJsonDialog"', INDEX_HTML)
        self.assertIn('id="trailUpdateJsonPreview"', INDEX_HTML)
        self.assertEqual(INDEX_HTML.count('data-trail-json-preview='), 2)
        self.assertNotIn('id="trailUpdateTableSummary"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateIssueTableSummary"', INDEX_HTML)
        self.assertNotIn("只 deep-merge", INDEX_HTML)
        self.assertIn("openTrailUpdateJsonPreview", APP_JS)
        self.assertIn("downloadTrailUpdateJson", APP_JS)
        self.assertIn("copyTrailUpdateJson", APP_JS)
        self.assertIn("trail-update-json-dialog", STYLES_CSS)
        self.assertIn("openTrailUpdateConfirm", APP_JS)
        self.assertIn("trailUpdateConfirmResolver", APP_JS)
        self.assertIn("trailUpdateConfirmSetExpanded", APP_JS)
        self.assertIn('id="trailUpdateConfirmExpand"', INDEX_HTML)
        self.assertIn("<details class=\"trail-update-confirm-item\">", APP_JS)
        self.assertIn("trail-update-confirm-item-details", STYLES_CSS)
        self.assertIn("trail-update-confirm-dialog", STYLES_CSS)
        self.assertIn('params.set("probe_trail", "false")', APP_JS)
        self.assertIn('params.set("refresh", "true")', APP_JS)
        self.assertIn("trailAttributePreviewNeedsLoad", APP_JS)
        self.assertIn('api(trailUpdateEndpoint(runId, false, force), { cache: "no-store" })', APP_JS)
        self.assertIn("function trailUpdateStatusEndpoint", APP_JS)
        self.assertIn('/api/trail-attribute-update/status?', APP_JS)
        self.assertIn('api(trailUpdateStatusEndpoint(items, force), { cache: "no-store" })', APP_JS)
        self.assertIn("async function refreshTrailAttributeStatus", APP_JS)
        self.assertIn("function patchTrailAttributeStatus", APP_JS)
        self.assertIn("data-trail-update-status-issue", APP_JS)
        self.assertIn("void refreshTrailAttributeStatus({ runId, previewKey, requestSeq, force }).catch(() => {});", APP_JS)
        self.assertIn("syncTrailAttributeActions", APP_JS)
        self.assertIn("syncTrailIssueActions", APP_JS)
        self.assertIn("trailUpdateWriteReady", APP_JS)
        self.assertIn("setTrailAttributeLoading", APP_JS)
        self.assertIn('trailPage?.classList.add("is-loading")', APP_JS)
        self.assertIn(".trail-update-page.is-loading .button:disabled { opacity: 1; filter: none; }", STYLES_CSS)
        self.assertIn('trail-update-page hidden is-loading" id="trailAttributeUpdatePage"', INDEX_HTML)
        self.assertIn("min-height: 52px", STYLES_CSS)
        self.assertIn(".trail-update-confirm-list { display: block", STYLES_CSS)
        self.assertNotIn("window.confirm(", APP_JS[APP_JS.index("function commitTrailIssueExclusion"):APP_JS.index("function bindTrailAttributeUpdateEvents")])
        self.assertIn('id="trailUpdateReviewTab"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateSectionTitle"', INDEX_HTML)
        self.assertIn('id="trailUpdateRunPicker"', INDEX_HTML)
        self.assertIn('id="trailUpdateRunPickerPanel"', INDEX_HTML)
        self.assertIn('class="ui-select-native gateway-model-native-select"', INDEX_HTML)
        self.assertNotIn("trail-update-section-heading", STYLES_CSS)
        self.assertIn("font-size: 11px", STYLES_CSS)
        self.assertIn("font-size: 9px", STYLES_CSS)
        self.assertNotIn("box-shadow: inset 0 -8px 18px", STYLES_CSS)
        self.assertNotIn("border-bottom: 1px solid rgba(34,211,238,.25)", STYLES_CSS)
        self.assertIn('class="page-card trail-update-header-card"', INDEX_HTML)
        self.assertIn('id="trailUpdateReviewControlsPanel"', INDEX_HTML)
        self.assertIn('id="trailUpdateRunHint"', INDEX_HTML)
        self.assertIn("No model Run in this environment", APP_JS)
        self.assertIn("does not share Runs with production 8785", APP_JS)
        self.assertIn("Do not inherit the Review gallery's", APP_JS)
        self.assertIn("No model Run selected (all Runs)", APP_JS)
        self.assertNotIn("no Run merges the latest Review from all Runs", INDEX_HTML)
        self.assertNotIn('id="trailUpdateWriteHint"', INDEX_HTML)
        self.assertIn("vertical-align: middle", STYLES_CSS)
        self.assertIn("border-spacing: 0 5px", STYLES_CSS)
        self.assertIn("trail-update-table td:first-child", STYLES_CSS)
        self.assertIn("Trail 更新状态", INDEX_HTML)
        self.assertIn("数据集版本", INDEX_HTML)
        self.assertIn("ra_stuck_auto_result_info.ra_triage_dashboard.should_exclude", INDEX_HTML)
        self.assertIn("trail-update-field-stat-card", INDEX_HTML)
        self.assertIn("trail-update-issue-summary-grid", INDEX_HTML)
        self.assertIn(".trail-update-issue-summary-grid", STYLES_CSS)
        self.assertIn("align-items: stretch", STYLES_CSS)
        self.assertIn(".trail-update-direct-table .trail-update-comment { text-align: center; }", STYLES_CSS)
        self.assertIn("const shortPath = patchPath.split", APP_JS)
        self.assertIn("grid-template-columns: minmax(0, 1fr)", STYLES_CSS)
        self.assertIn(".analysis-stat-card.trail-update-field-stat-card", STYLES_CSS)
        self.assertIn("white-space: normal", STYLES_CSS)
        self.assertIn("-webkit-line-clamp: 2", STYLES_CSS)
        self.assertNotIn('id="trailUpdateInfoFieldDetail"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateIssueFieldDetail"', INDEX_HTML)
        self.assertIn("trailUpdateStatusSummary", APP_JS)
        self.assertIn("trail_update_status_summary", APP_JS)
        self.assertIn('id="trailUpdateFilterForm"', INDEX_HTML)
        self.assertIn('id="trailUpdateSearchInput"', INDEX_HTML)
        self.assertIn('id="trailUpdateGtFilter"', INDEX_HTML)
        self.assertIn('id="trailUpdateModelLabelFilter"', INDEX_HTML)
        self.assertIn('id="trailUpdateReviewerFilter"', INDEX_HTML)
        self.assertIn('id="trailUpdateReviewStatusFilter"', INDEX_HTML)
        self.assertIn('id="trailUpdateStatusFilter"', INDEX_HTML)
        self.assertIn('id="trailUpdatePagination"', INDEX_HTML)
        self.assertIn('id="trailUpdatePageSize"', INDEX_HTML)
        self.assertIn("function normalizedTrailUpdateRouteFilters", APP_JS)
        self.assertIn("function applyTrailUpdateRouteControls", APP_JS)
        self.assertIn("function trailUpdateFilteredItems", APP_JS)
        self.assertIn("function renderTrailUpdatePagination", APP_JS)
        self.assertIn("trail_status", APP_JS)
        self.assertIn("review_status", APP_JS)
        self.assertIn("renderTrailUpdateFilters", APP_JS)
        self.assertIn("trailUpdateStatusSummary(data, filteredItems)", APP_JS)
        self.assertIn("allItems = Array.isArray(data?.items)", APP_JS)
        self.assertIn('data-label="模型 reason"', APP_JS)
        self.assertIn('data-label="预计写入 info"', APP_JS)
        self.assertIn("trail-update-comment-target", APP_JS)
        self.assertIn("trail-update-comment-target", STYLES_CSS)
        self.assertIn("content: attr(data-label)", STYLES_CSS)
        self.assertIn(".trail-update-table tbody tr:has(.trail-update-empty)", STYLES_CSS)
        self.assertIn("grid-template-columns: minmax(0, 1fr); grid-template-rows: auto auto auto", STYLES_CSS)
        self.assertIn("function trailUpdateTargetSpec", APP_JS)
        self.assertIn("target_path", APP_JS)
        self.assertIn("is-synced", STYLES_CSS)
        self.assertIn("analysis-review-status-bar", APP_JS)
        self.assertIn("trail-status-${escapeHtml(meta.key)}", APP_JS)
        self.assertIn("data-trail-update-status-key", APP_JS)
        self.assertIn("baseline_id", APP_JS)
        self.assertIn("data.baselines", APP_JS)
        self.assertIn("title=\"${escapeHtml(sourceRun.title)}\"", APP_JS)
        self.assertIn("trail-update-status-card", INDEX_HTML)
        self.assertIn("trail-update-status-heading", STYLES_CSS)
        self.assertIn(".analysis-review-status-card.trail-update-status-card", STYLES_CSS)
        self.assertIn("grid-template-columns: minmax(0, 1fr) minmax(0, 2fr) minmax(0, 2fr)", STYLES_CSS)
        self.assertIn("grid-template-rows: auto auto", STYLES_CSS)
        self.assertNotIn('id="trailUpdateStatusDetail"', INDEX_HTML)
        self.assertIn("cursor: default", STYLES_CSS)
        self.assertNotIn(".trail-update-source-cell, .trail-update-comment[title], .trail-update-reason[title] { cursor: help; }", STYLES_CSS)
        self.assertIn("bindUiSelect(picker", APP_JS)
        self.assertNotIn("Preview fingerprint", INDEX_HTML)
        self.assertNotIn('id="trailUpdateIssueDigest"', INDEX_HTML)
        self.assertNotIn("trailUpdateIssueDigest", APP_JS)
        self.assertIn("loadPageData &&", APP_JS)
        self.assertIn("trailAttributePreviewNeedsLoad", APP_JS)
        bootstrap_body = APP_JS[APP_JS.index("async function bootstrap"):]
        self.assertNotIn("initialPageRequests.push(loadTrailAttributePreview())", bootstrap_body)
        self.assertIn("void loadTrailAttributePreview().catch", bootstrap_body)
        self.assertIn("renderTrailAttributeRunPicker();", APP_JS)
        self.assertIn('id="trailUpdateIssueTab"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueEntries"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueAddButton"', INDEX_HTML)
        self.assertNotIn('id="trailUpdateIssueHistoricalExclusionsButton"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueJsonImportButton"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueExcelImportButton"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueClearAllButton"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueJsonImportDialog"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueJsonImportFile"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueExcelImportDialog"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueExcelImportFile"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueJsonImportPreview"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueExcelImportPreview"', INDEX_HTML)
        self.assertIn('class="trail-update-direct-footer"', INDEX_HTML)
        self.assertIn("data-trail-issue-entry-id", INDEX_HTML)
        self.assertIn("data-trail-issue-entry-comment", INDEX_HTML)
        self.assertIn("loadTrailIssuePreview", APP_JS)
        self.assertNotIn("loadTrailHistoricalExclusions", APP_JS)
        self.assertNotIn("/api/trail-attribute-update/historical-exclusions", APP_JS)
        self.assertIn("clearTrailIssueEntries", APP_JS)
        self.assertIn("historicalExclusionSourceMarkup", APP_JS)
        self.assertIn("data-trail-issue-entry-source", APP_JS)
        self.assertIn("commitTrailIssueExclusion", APP_JS)
        self.assertIn("refreshTrailReviewAfterIssueCommit", APP_JS)
        self.assertIn("await loadTrailAttributePreview(true);", APP_JS)
        self.assertIn("/api/trail-attribute-update/issue-preview", APP_JS)
        self.assertIn("/api/trail-attribute-update/issue-commit", APP_JS)
        self.assertNotIn("真实接口 · 预览优先", INDEX_HTML)
        self.assertIn("预计改动（仅写 info）", INDEX_HTML)
        self.assertIn("预计写入 info", INDEX_HTML)
        self.assertIn("<th>数据集版本</th>", INDEX_HTML)
        self.assertIn("should_exclude_comment", INDEX_HTML)
        self.assertIn("entries: parsed.entries", APP_JS)
        self.assertIn("requested_entries", APP_JS)
        self.assertNotIn("Issue 与排除说明", INDEX_HTML)
        self.assertIn('data-trail-issue-entry-id rows="2"', INDEX_HTML)
        self.assertIn(".trail-update-direct-table th,", STYLES_CSS)
        self.assertIn("vertical-align: middle", STYLES_CSS)
        self.assertIn(".trail-update-direct-actions", STYLES_CSS)
        self.assertNotIn(".trail-update-entry-heading", STYLES_CSS)
        self.assertIn(".trail-update-direct-footer", STYLES_CSS)
        self.assertIn("multiple per row", APP_JS)
        self.assertIn("parsed.ids.forEach", APP_JS)
        self.assertIn("trailIssueImportState", APP_JS)
        self.assertIn("previewTrailIssueJsonImport", APP_JS)
        self.assertIn("previewTrailIssueExcelImport", APP_JS)
        self.assertIn("applyTrailIssueImportPreview", APP_JS)
        self.assertIn("/api/trail-attribute-update/issue-import/json-preview", APP_JS)
        self.assertIn("/api/trail-attribute-update/issue-import/excel-preview", APP_JS)
        self.assertIn("allowReadOnlyMutation: true", APP_JS)
        self.assertIn("trail-update-import-preview-table", INDEX_HTML)
        self.assertIn(".trail-update-import-preview", STYLES_CSS)
        self.assertIn("field_update", APP_JS)
        self.assertIn("不改模型 label", APP_JS)
        self.assertNotIn("trailInfoPreviewJson", APP_JS)
        self.assertNotIn("trail-update-json-preview", STYLES_CSS)
        self.assertIn('data-trail-json-preview="review"', INDEX_HTML)
        self.assertIn('data-trail-json-preview="issue"', INDEX_HTML)
        self.assertIn("trail-update-result-actions", STYLES_CSS)
        self.assertIn("排除说明", INDEX_HTML)
        self.assertIn('id="trailUpdateProgressDialog"', INDEX_HTML)
        self.assertIn("openTrailUpdateProgress", APP_JS)
        self.assertIn("finishTrailUpdateProgress", APP_JS)
        self.assertIn("data-trail-progress-stage", INDEX_HTML)
        self.assertIn("trail-update-progress-track.is-running", STYLES_CSS)
        self.assertIn('id="trailUpdateIssueHistory"', INDEX_HTML)
        self.assertIn('id="trailUpdateIssueHistoryList"', INDEX_HTML)
        self.assertIn("loadTrailIssueHistory", APP_JS)
        self.assertIn("/api/trail-attribute-update/issue-history", APP_JS)
        self.assertIn("trail-update-history-item", STYLES_CSS)
        self.assertIn(".trail-update-historical-source", STYLES_CSS)
        self.assertNotIn("三步生成待处理草稿", INDEX_HTML)
        self.assertIn("loadPageData &&", APP_JS)
        self.assertIn("trailAttributePreviewNeedsLoad", APP_JS)

    def test_historical_spotcheck_tags_only_prefill_unsaved_reviews(self) -> None:
        self.assertIn("function currentReviewSourceSuggestion", APP_JS)
        self.assertIn("issue_tag_suggestion", APP_JS)
        self.assertIn("currentReviewSourceSuggestion(caseData)?.annotation", APP_JS)
        self.assertIn("function issueTagSourceSuggestionMarkup", APP_JS)
        self.assertIn("历史抽检预填", APP_JS)
        self.assertIn("保存后才会创建新的 Review 版本", APP_JS)

    def test_db_backed_mentions_cover_review_analysis_and_issue_exclusion(self) -> None:
        self.assertIn('api("/api/mention-users")', APP_JS)
        self.assertIn("state.mentionUsers", APP_JS)
        self.assertIn("activeMentionQuery", APP_JS)
        self.assertIn("review-mention-popover", APP_JS)
        self.assertIn("function reviewMentionCaretAnchor", APP_JS)
        self.assertIn("function positionReviewMentionPopover", APP_JS)
        self.assertIn("reviewMentionCaretAnchor(textarea, active.start)", APP_JS)
        self.assertIn('popover.classList.toggle("opens-up", opensUp)', APP_JS)
        self.assertIn('event.key === "Escape"', APP_JS)
        self.assertIn("preserveTrigger: true", APP_JS)
        self.assertIn("item.username.includes(normalizedQuery)", APP_JS)
        self.assertIn('item.displayName.toLocaleLowerCase("zh-CN").includes(normalizedQuery)', APP_JS)
        self.assertIn("\\u3400-\\u9fff", APP_JS)
        self.assertIn(
            "梁祥辉",
            (STATIC_DIR.parent / "app" / "db_parts" / "access.py").read_text(
                encoding="utf-8"
            ),
        )
        self.assertIn("reviewCommentBodyMarkup", APP_JS)
        self.assertIn('uiText("自己", "You")', APP_JS)
        self.assertNotIn("item !== current", APP_JS)
        self.assertIn(".review-mention-popover", STYLES_CSS)
        self.assertIn("position: fixed", STYLES_CSS)
        self.assertIn(".review-mention-popover.opens-up", STYLES_CSS)
        self.assertIn(".review-mention-option.is-active", STYLES_CSS)
        self.assertNotIn("可用 @ldap 通知同事", APP_JS)
        self.assertNotIn("可输入 @ldap", INDEX_HTML)
        self.assertIn('id="analysisDiscussionDialog"', INDEX_HTML)
        self.assertIn("data-analysis-discussion", APP_JS)
        self.assertIn('class="analysis-discussion-link"', APP_JS)
        self.assertNotIn('class="button button-quiet" type="button" data-analysis-discussion', APP_JS)
        self.assertIn(".analysis-discussion-link, .text-link", STYLES_CSS)
        self.assertIn("data-trail-update-discussion", APP_JS)
        self.assertNotIn('<th>操作</th>', INDEX_HTML)
        self.assertIn('class="trail-update-issue-meta"', APP_JS)
        self.assertIn(".trail-update-issue-meta > small", STYLES_CSS)
        self.assertNotIn('data-label="操作"', APP_JS)
        self.assertIn('colspan="8" class="trail-update-empty"', INDEX_HTML)
        self.assertIn('source: "trail-update"', APP_JS)
        self.assertIn("review.model_run_id || model.run_id", APP_JS)
        self.assertIn('/comments?model_run_id=', APP_JS)
        self.assertIn('openComments: params.get("comments") === "1"', APP_JS)
        self.assertIn('source: "deep-link"', APP_JS)
        self.assertIn("data-review-comments", APP_JS)
        self.assertIn('reply_to_id: context.replyTo?.id || null', APP_JS)
        self.assertIn('data-comment-reply=', APP_JS)
        self.assertIn('data-comment-share=', APP_JS)
        self.assertIn("analysisDiscussionShareUrl", APP_JS)
        self.assertIn("navigator.share", APP_JS)
        self.assertIn("navigator.clipboard?.writeText", APP_JS)
        self.assertIn('url.searchParams.set("comment"', APP_JS)
        self.assertIn('.replace(/^\\s*(?:#{1,3}|>|[-+*]|\\d+[.)])\\s+/gm, "")', APP_JS)
        self.assertIn('data-comment-format="bold"', INDEX_HTML)
        self.assertIn("data-comment-image", INDEX_HTML)
        self.assertIn("comments-with-attachments", APP_JS)
        self.assertIn('"X-RA-Triage-Request": "comment-v1"', APP_JS)
        self.assertIn("comment-markdown-image", STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .comment-thread-list', STYLES_CSS)
        self.assertNotIn('/annotations`, {\n      method: "POST",\n      body: JSON.stringify({\n        model_run_id: String(context.runId', APP_JS)
        self.assertIn(".trail-update-discussion-link", STYLES_CSS)
        self.assertIn("saveAnalysisDiscussion", APP_JS)
        self.assertIn("data-mention-composer", INDEX_HTML)
        self.assertIn("data-trail-issue-entry-comment data-mention-composer", APP_JS)
        self.assertIn('id="mentionUserForm"', INDEX_HTML)
        self.assertIn("does not grant Dashboard write or admin access", INDEX_HTML)


if __name__ == "__main__":
    unittest.main()
