"""Frontend media source contracts; original assertions preserved."""
import unittest
from frontend_contract_fixtures import APP_ENTRY_JS, APP_JS, APP_PY_CASES_DB, APP_PY_CASES_ROUTER, APP_PY_LABELING_DB, APP_PY_LABELING_ROUTER, CAMPAIGNS_JS, INDEX_HTML, LABELING_SUMMARY_JS, STATIC_DIR, STYLES_CSS


class FrontendMediaContractTest(unittest.TestCase):
    def test_light_theme_keeps_controls_and_non_media_surfaces_readable(self) -> None:
        self.assertIn('html[data-color-theme="light"] input::placeholder', STYLES_CSS)
        self.assertIn('-webkit-text-fill-color: #627086', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .comparison-summary', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .bev-video-controls', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .gateway-model-option strong', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .analysis-stat-card > strong', STYLES_CSS)
        self.assertIn('background: var(--overlay);', STYLES_CSS)
        self.assertIn('--faint: #64748b', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .review-tag-axis-title', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .issue-id', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .run-source-tab em', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .button-primary', STYLES_CSS)
        self.assertIn('`${activeBase}/static/${path}?v=manual-triage-560`', INDEX_HTML)
        self.assertIn(".review-exclude-toggle { display: grid; grid-template-columns: auto minmax(0, 1fr) auto; align-items: center;", STYLES_CSS)
        self.assertIn("display: flex; align-items: baseline; flex-wrap: wrap; gap: 6px;", STYLES_CSS)
        self.assertIn("max-height: min(70dvh, 640px); overflow: auto;", STYLES_CSS)
        self.assertIn("justify-content: flex-end; margin-left: auto;", STYLES_CSS)
        self.assertIn('id="resetReviewFiltersButton"', INDEX_HTML)
        self.assertIn('class="ui-lang-zh">重置</span>', INDEX_HTML)
        self.assertIn('class="ui-lang-en">Reset</span>', INDEX_HTML)
        self.assertIn("async function resetReviewFilters", APP_JS)
        self.assertIn("flex-wrap: nowrap; align-items: center; gap: 3px;", STYLES_CSS)
        self.assertIn(".issue-card-heading-main", STYLES_CSS)
        self.assertIn('class="issue-card-heading-main"', APP_JS)
        self.assertIn('class="row-evidence" title="', APP_JS)
        self.assertIn("enteringReviewHome", APP_JS)
        self.assertIn("needsReload", APP_JS)
        self.assertIn("--ui-chevron-mask:", STYLES_CSS)
        self.assertNotIn('content: "⌄"', STYLES_CSS)
        self.assertIn('id="splitFilteredButton"', INDEX_HTML)
        self.assertIn('id="workSplitPanel"', INDEX_HTML)
        self.assertIn('id="workAssigneeFilter"', INDEX_HTML)
        self.assertIn('id="analysisWorkAgreementField">', INDEX_HTML)
        self.assertIn('if (analysisField) analysisField.hidden = false;', APP_JS)
        self.assertIn("function openWorkSplitDialog", APP_JS)
        self.assertIn("function updateWorkSplitAdminVisibility", APP_JS)
        self.assertIn("/api/cases/work-split", APP_JS)
        self.assertIn("/api/cases/work-splits", APP_JS)
        self.assertIn('data-page-target="review-assignments"', INDEX_HTML)
        self.assertIn('data-page="review-assignments"', INDEX_HTML)
        self.assertIn('path: "/review-assignments"', APP_JS)
        self.assertIn("function loadReviewAssignments", APP_JS)
        self.assertIn("function reassignReviewAssignment", APP_JS)
        self.assertIn("已完成，锁定", APP_JS)
        self.assertIn("/api/work-assignees", APP_JS)
        self.assertIn("workAssigneeRequestSeq", APP_JS)
        self.assertIn("Object.entries(currentReviewFilterPayload())", APP_JS)
        self.assertIn("params.set(\"work_assignee\"", APP_JS)
        self.assertIn("baselines: selectedBaselineQueryValue()", APP_JS)
        self.assertIn('id="workSplitReviewersPerIssue"', INDEX_HTML)
        self.assertIn('id="workSplitReviewersPerIssuePicker"', INDEX_HTML)
        self.assertIn('class="ui-select-native" id="workSplitReviewersPerIssue"', INDEX_HTML)
        self.assertIn('id="workSplitOverlapRatio"', INDEX_HTML)
        self.assertIn('id="workSplitOverlapPicker"', INDEX_HTML)
        self.assertIn('id="analysisWorkAgreementPicker"', INDEX_HTML)
        self.assertIn('class="ui-select-native" id="analysisWorkAgreementFilter"', INDEX_HTML)
        self.assertIn('class="ui-select work-split-person-picker"', APP_JS)
        self.assertIn("function renderWorkSplitPersonPickers", APP_JS)
        self.assertIn("function reviewAssignmentBatchHref", APP_JS)
        self.assertIn('uiText("去判错复核", "Open Review")', APP_JS)
        self.assertIn('uiText("去原因聚类", "Open analysis")', APP_JS)
        self.assertIn('workSplitId: item?.split_id || ""', APP_JS)
        self.assertIn('url.searchParams.set("work_split", review.workSplitId)', APP_JS)
        self.assertIn('url.searchParams.set("work_split", analysis.workSplitId)', APP_JS)
        self.assertIn('params.set("work_split_id", options.workSplitId)', APP_JS)
        self.assertNotIn('id="reviewWorkSplitPicker"', INDEX_HTML)
        self.assertIn('id="analysisWorkSplitPicker"', INDEX_HTML)
        self.assertIn("async function loadAnalysisWorkSplits", APP_JS)
        self.assertIn("/api/review-work-splits?", APP_JS)
        self.assertIn("analysisWorkSplitOptionLabel", APP_JS)
        self.assertIn("function renderWorkSplitReviewersPerIssuePicker", APP_JS)
        self.assertIn("function renderWorkSplitOverlapPicker", APP_JS)
        self.assertIn("overlap_ratio: overlapRatio", APP_JS)
        self.assertIn("workSplitOverlapRatio()", APP_JS)
        self.assertNotIn('input.disabled = reviewers > 1', APP_JS)
        self.assertNotIn('assignees.map((item) => ({ ...item, count: null }))', APP_JS)
        self.assertIn("reviewers_per_issue: reviewersPerIssue", APP_JS)
        self.assertIn('t("work.blind_estimate"', APP_JS)
        self.assertIn('id="workSplitName"', INDEX_HTML)
        self.assertIn('id="labelingTaskNameStatus"', INDEX_HTML)
        self.assertIn('class="work-split-toolbar assignment-footer-row"', INDEX_HTML)
        self.assertIn("function ruleBasedAssignmentName", APP_JS)
        self.assertIn("/api/assignment-name-suggestion", APP_JS)
        self.assertIn('bindAssignmentNameInput("review")', APP_JS)
        self.assertIn('bindAssignmentNameInput("labeling")', APP_JS)
        self.assertIn('id="workSplitRefreshName"', INDEX_HTML)
        self.assertIn('id="labelingTaskRefreshName"', INDEX_HTML)
        self.assertNotIn("function regenerateAssignmentName", APP_JS)
        self.assertNotIn("manual || !gatewayConfigured", APP_JS)
        self.assertIn('["llm", "rule"].includes(input.dataset.suggestionSource)', APP_JS)
        self.assertIn('node.dataset.status = status', APP_JS)
        self.assertIn('uiText("规则结果", "Rule result")', APP_JS)
        self.assertIn('uiText("模型结果", "Model result")', APP_JS)
        self.assertIn('uiText("手动编辑", "Manual")', APP_JS)
        self.assertNotIn("规则已生成", APP_JS)
        self.assertNotIn('class="ui-lang-zh">新建实验</span><span class="ui-lang-en">NEW EXPERIMENT</span>', INDEX_HTML)
        self.assertNotIn('class="ui-lang-zh">复核工作管理</span><span class="ui-lang-en">REVIEW WORK MANAGEMENT</span>', INDEX_HTML)
        self.assertNotIn("NEW EXPERIMENT", INDEX_HTML)
        self.assertNotIn("EXPERIMENT HISTORY", INDEX_HTML)
        self.assertNotIn("review-assignments-eyebrow", INDEX_HTML)
        self.assertNotIn('<h2><span class="ui-lang-zh">任务分配</span><span class="ui-lang-en">Review assignments</span></h2>', INDEX_HTML)
        self.assertIn('<h2><span class="ui-lang-zh">分配配置</span><span class="ui-lang-en">Assignment setup</span></h2>', INDEX_HTML)
        self.assertIn('id="labelingTaskHistoryTitle"><span class="ui-lang-zh">实验记录</span><span class="ui-lang-en">Experiment records</span>', INDEX_HTML)
        self.assertNotIn('id="labelingTaskSummary"', INDEX_HTML)
        self.assertNotIn('id="workSplitSummary"', INDEX_HTML)
        self.assertNotIn('id="workSplitDialogHint"', INDEX_HTML)
        self.assertIn('class="ui-lang-zh">实验名称</span><span class="ui-lang-en">Experiment name</span>', INDEX_HTML)
        self.assertIn("if (name) body.name = name", APP_JS)
        self.assertIn('@router.post("/api/assignment-name-suggestion")', APP_PY_CASES_ROUTER)
        self.assertIn("task_name or f\"Review task", APP_PY_CASES_ROUTER)
        self.assertIn("task_name or f\"标注任务", APP_PY_LABELING_ROUTER)
        self.assertIn(".assignment-footer-row { flex-wrap: nowrap", STYLES_CSS)
        self.assertIn('id="analysisWorkAgreementFilter"', INDEX_HTML)
        self.assertIn('params.set("work_agreement"', APP_JS)
        self.assertIn("item.multi_review || null", APP_JS)
        self.assertIn("work_split_id:", APP_JS)
        self.assertIn(".review-tag-option-row", STYLES_CSS)
        self.assertIn('class="ui-lang-zh">模型标注</span>', INDEX_HTML)
        self.assertIn('class="ui-lang-en">Model label</span>', INDEX_HTML)
        self.assertNotIn('<span>人工标注</span>', INDEX_HTML)
        self.assertIn('params.set("model_label", modelLabel)', APP_JS)
        self.assertIn('url.searchParams.set("model_label", modelLabel)', APP_JS)
        self.assertIn("function renderReviewCatalogFilters", APP_JS)
        self.assertIn('value: "no_gt"', APP_JS)
        self.assertIn('"comparison.no_gt": "NO GT · GT 待复核"', APP_JS)
        self.assertIn('return "no_gt"', APP_JS)
        self.assertIn("comparison-no_gt", STYLES_CSS)
        self.assertIn('data-placeholder="全部 GT"', INDEX_HTML)
        self.assertIn('id="analysisModelLabelFilter"', INDEX_HTML)
        self.assertIn('id="analysisIssueInput"', INDEX_HTML)
        self.assertIn('class="analysis-issue-input"', INDEX_HTML)
        self.assertIn('id="analysisSceneFilter"', INDEX_HTML)
        self.assertIn('id="analysisTriggerFilter"', INDEX_HTML)
        self.assertIn('id="analysisEgressFilter"', INDEX_HTML)
        self.assertIn('id="analysisPageSize"', INDEX_HTML)
        self.assertIn("function changeAnalysisPageSize", APP_JS)
        self.assertIn('id="analysisPageJump"', INDEX_HTML)
        self.assertIn('id="analysisPageJumpButton"', INDEX_HTML)
        self.assertIn("function jumpToAnalysisPage", APP_JS)
        self.assertIn('id="casePageSummary"', INDEX_HTML)
        self.assertIn('id="casePageJump"', INDEX_HTML)
        self.assertIn('id="casePageJumpButton"', INDEX_HTML)
        self.assertIn("function jumpToCasePage", APP_JS)
        self.assertIn('$("#casePageJumpButton")?.addEventListener("click", commitCasePageJump)', APP_JS)
        self.assertNotIn('casePageJump?.addEventListener("change", commitCasePageJump)', APP_JS)
        # Review, analysis, Trail exclusion candidates, and admin Run
        # comparison all expose the shared jump-to-page control.
        self.assertEqual(INDEX_HTML.count('class="page-jump-control"'), 6)
        self.assertIn("const requestedPage = state.reviewAnalysis.page", APP_JS)
        self.assertIn("state.reviewAnalysis.page = requestedPage", APP_JS)
        self.assertIn("page_count", APP_JS)
        self.assertIn("pageSize: state.reviewAnalysis.pageSize", APP_JS)
        self.assertIn('id="analysisClusterPanels"', INDEX_HTML)
        self.assertIn('id="analysisReviewStatusChart"', INDEX_HTML)
        self.assertIn('id="analysisReviewStatusSummary"', INDEX_HTML)
        self.assertIn('class="analysis-decision-grid"', INDEX_HTML)
        self.assertIn('id="analysisConfusionMatrix"', INDEX_HTML)
        self.assertIn('id="analysisConfusionSummary"', INDEX_HTML)
        self.assertIn("function renderAnalysisConfusion", APP_JS)
        self.assertIn("function bindAnalysisConfusionHover", APP_JS)
        self.assertIn("function bindAnalysisLinkedHover", APP_JS)
        self.assertIn("const item = pointerItem || focusItem", APP_JS)
        self.assertIn('root.addEventListener("pointerover", (event)', APP_JS)
        self.assertIn('root.addEventListener("focusin", (event)', APP_JS)
        self.assertIn('data-confusion-row=', APP_JS)
        self.assertIn('data-confusion-col=', APP_JS)
        self.assertIn('data-confusion-col="${columnIndex}" tabindex="0"', APP_JS)
        self.assertIn('label === "NONE" ? uiText("未输出", "NONE")', APP_JS)
        self.assertNotIn('id="analysisEvidenceClusters"', INDEX_HTML)
        self.assertNotIn('id="analysisAnnotationFilter"', INDEX_HTML)
        self.assertNotIn('id="analysisTagFilter"', INDEX_HTML)
        self.assertNotIn('id="analysisReasonClusters"', INDEX_HTML)
        self.assertNotIn('原因文本主题', INDEX_HTML)
        self.assertIn("function renderAnalysisClusterPanels", APP_JS)
        self.assertIn("function renderAnalysisReviewStatus", APP_JS)
        self.assertIn("function bindAnalysisReviewStatusHover", APP_JS)
        self.assertIn('data-review-status-key=', APP_JS)
        self.assertIn('role="listitem" tabindex="0"', APP_JS)
        self.assertIn("data.summary?.model_review_status_counts", APP_JS)
        self.assertNotIn('key: "blocked_by_label"', APP_JS)
        self.assertIn('value: "needs_gt_review", label: uiText("GT 待复核"', APP_JS)
        self.assertIn(".analysis-review-status-bar", STYLES_CSS)
        self.assertIn('grid-template-areas: "confusion status"', STYLES_CSS)
        self.assertIn('grid-template-areas: "status" "confusion"', STYLES_CSS)
        self.assertIn("minmax(610px, 2fr) minmax(280px, .78fr)", STYLES_CSS)
        self.assertIn("grid-template-rows: auto minmax(0, 1fr)", STYLES_CSS)
        self.assertIn(".analysis-cluster-card > .analysis-pie-groups", STYLES_CSS)
        self.assertNotIn("筛选用上方", APP_JS)
        self.assertNotIn("hover 查看详情", APP_JS)
        self.assertIn("function renderAnalysisPieSvg", APP_JS)
        self.assertIn("function analysisDonutSlicePath", APP_JS)
        self.assertIn("#24d3ef", APP_JS)
        self.assertIn("ANALYSIS_PIE_BASE_LIGHT", APP_JS)
        self.assertIn('html[data-color-theme="light"] .analysis-cluster-card', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .multi-filter-trigger', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .analysis-pie-center b', STYLES_CSS)
        self.assertIn("background: transparent", STYLES_CSS)
        self.assertIn("function renderMultiFilter", APP_JS)
        self.assertIn("模型结果 Review", APP_JS)
        self.assertIn("Model Result Review", APP_JS)
        self.assertIn("function formatModelConfidence", APP_JS)
        self.assertIn("function reviewAnnotationsForCurrentRun", APP_JS)
        self.assertIn("function reviewAnnotationsForAllRuns", APP_JS)
        self.assertIn("function inheritedHistoricalTagsForCurrentRun", APP_JS)
        self.assertIn("historicalReview", APP_JS)
        self.assertIn("function initialReviewTagsForCurrentRun", APP_JS)
        self.assertIn("data.labelled ?? data.reviewed_failures", APP_JS)
        self.assertIn("包含模型与 GT 一致的 Review", APP_JS)
        self.assertIn("条判错已复核", APP_JS)
        self.assertIn("across ${runCount} model runs", APP_JS)
        self.assertIn("data-selected-tags-section", APP_JS)
        self.assertIn("data-remove-review-tag", APP_JS)
        self.assertIn("data-selected-missing-evidence", APP_JS)
        self.assertIn("data-remove-review-evidence", APP_JS)
        self.assertIn("missing-evidence-selected-chip", APP_JS)
        # Missing-evidence chips use coral-orange, not no_assist amber.
        self.assertIn(
            ".tag-group-selected-chip.missing-evidence-selected-chip",
            STYLES_CSS,
        )
        self.assertIn("rgba(251,146,60", STYLES_CSS)
        # Screenshot drop zone: drag/drop + single form paste; browse only opens picker.
        self.assertIn('id="screenshotPasteZone"', APP_JS)
        self.assertIn("is-dragover", APP_JS)
        self.assertIn(".screenshot-paste-zone.is-dragover", STYLES_CSS)
        self.assertIn("imageFilesFromDataTransfer", APP_JS)
        self.assertIn('pasteZone.addEventListener("drop"', APP_JS)
        self.assertIn("拖拽到此处", APP_JS)
        # Case-labeling reuses the same paste-zone component with its own ids.
        self.assertIn('id="caseLabelingPasteZone"', APP_JS)
        self.assertIn('id="caseLabelingPendingScreenshots"', APP_JS)
        self.assertIn('$("#caseLabelingForm")?.addEventListener("paste"', APP_JS)
        self.assertIn("data-remove-case-screenshot", APP_JS)
        # Labeling history opens the shared dialog, like Review's J button,
        # and the topbar keeps its right cluster right-aligned without metrics.
        self.assertIn("function bindCaseLabelingEditorShortcuts", APP_JS)
        self.assertIn('toggleHistoryDialog("labeling", state.caseLabeling.caseData)', APP_JS)
        self.assertIn('uiText("标注历史", "Label history")', APP_JS)
        self.assertIn("caseLabelingHistoryMarkup(caseData)", APP_JS)
        self.assertNotIn("caseLabelingHistoryPanel", APP_JS)
        # Labeling history reuses Review's annotationHistory cards (no delete).
        self.assertIn("function annotationHistory(annotations, options = {})", APP_JS)
        self.assertIn("function caseLabelingHistoryAnnotations", APP_JS)
        self.assertIn("annotationHistory(caseLabelingHistoryAnnotations(caseData)", APP_JS)
        self.assertIn("deletable: false", APP_JS)
        # Labeling detail loads Trail metadata so RA 录屏 / RA Event links show.
        self.assertIn("void startTrailDetailMetadata(normalized, seq)", APP_JS)
        self.assertIn(
            '$("#caseLabelingExternalLinks")?.querySelector("[data-open-ra-event]")',
            APP_JS,
        )
        self.assertIn(
            'body[data-active-page^="labeling"] .gt-sync-control { margin-left: auto; }',
            STYLES_CSS,
        )
        # Gallery filter bar adds labeler / result-category / exclusion filters.
        self.assertIn('id="caseLabelingAuthorPicker"', INDEX_HTML)
        self.assertIn('id="caseLabelingLabelPicker"', INDEX_HTML)
        self.assertIn('id="caseLabelingExclusionPicker"', INDEX_HTML)
        self.assertIn("function renderCaseLabelingAuthorPicker", APP_JS)
        self.assertIn("function renderCaseLabelingLabelPicker", APP_JS)
        self.assertIn("function renderCaseLabelingExclusionPicker", APP_JS)
        self.assertIn('exclusion: joinFilterList(state.caseLabeling.exclusion)', APP_JS)
        self.assertIn("function renderCaseLabelingMultiPicker", APP_JS)
        self.assertIn("renderMultiFilter(root", APP_JS)
        self.assertIn("def labeling_labelers", APP_PY_LABELING_DB)
        self.assertIn('author: str = ""', APP_PY_LABELING_ROUTER)
        # M8a-1 / M8c #24: create-task is a standalone page reusing work-split helpers.
        self.assertIn('id="caseLabelingCreateTask"', INDEX_HTML)
        self.assertIn('id="caseLabelingNewTaskPage"', INDEX_HTML)
        self.assertIn('id="caseLabelingNewTaskPage" data-page="labeling-new-task"', INDEX_HTML)
        self.assertIn('id="labelingTaskBack"', INDEX_HTML)
        self.assertIn('id="labelingTaskPeople"', INDEX_HTML)
        self.assertIn('id="labelingTaskReviewersPerIssuePicker"', INDEX_HTML)
        self.assertIn('id="labelingTaskOverlapPicker"', INDEX_HTML)
        self.assertIn('path: "/case-labeling/new-task"', APP_JS)
        self.assertIn('if (target === "labeling-new-task")', APP_JS)
        self.assertIn('showPage("labeling-new-task", { historyMode: "push" })', APP_JS)
        self.assertIn("function enterLabelingNewTask", APP_JS)
        self.assertIn(
            "loadCaseLabelingCases({ page: state.caseLabeling.page, persistRoute: false })",
            APP_JS,
        )
        self.assertIn('initialRoute.page === "labeling-new-task"', APP_JS)
        self.assertIn('initialPageRequests.push(enterLabelingNewTask({ route: initialRoute }))', APP_JS)
        self.assertIn('returnTo: target === "labeling-new-task" && previousPage === "labeling"', APP_JS)
        self.assertIn('page === "labeling" || page === "labeling-new-task"', APP_JS)
        self.assertNotIn("labelingTaskDialog", INDEX_HTML)
        self.assertNotIn("openLabelingTaskDialog", APP_JS)
        self.assertIn("function generateLabelingTask", APP_JS)
        self.assertIn("function bindLabelingTaskControls", APP_JS)
        self.assertIn("function labelingTaskFilterPayload", APP_JS)
        self.assertIn('renderWorkSplitPersonPickers("#labelingTaskPeople")', APP_JS)
        self.assertIn(
            'function renderWorkSplitPersonPickers(rootSelector = "#workSplitPeople")',
            APP_JS,
        )
        self.assertIn(
            'function readWorkSplitAssignees(rootSelector = "#workSplitPeople")', APP_JS
        )
        self.assertIn(
            "if (typeof bindLabelingTaskControls === \"function\") bindLabelingTaskControls();",
            APP_JS,
        )
        self.assertIn("def _project_labeling_cases", APP_PY_LABELING_DB)
        self.assertIn("def labeling_case_issue_ids", APP_PY_LABELING_DB)
        self.assertIn("database.labeling_case_issue_ids", APP_PY_LABELING_ROUTER)
        self.assertIn('"assignments": assignments', APP_PY_LABELING_ROUTER)
        # M8a-2: per-assignee task-queue filter on the Case-labeling gallery.
        self.assertIn('id="caseLabelingAssigneePicker"', INDEX_HTML)
        self.assertNotIn('id="caseLabelingAssignee"', INDEX_HTML)
        self.assertIn('<span>任务负责人</span><div class="multi-filter" id="caseLabelingAssigneePicker"', INDEX_HTML)
        self.assertIn("function renderCaseLabelingAssigneePicker", APP_JS)
        self.assertIn('assignee: joinFilterList(state.caseLabeling.assignee)', APP_JS)
        self.assertIn(
            'assignee: overrides.assignee ?? labeling.assignee ?? []',
            APP_JS,
        )
        self.assertIn("def labeling_assignees", APP_PY_LABELING_DB)
        self.assertIn('assignee: str = ""', APP_PY_LABELING_ROUTER)
        # M8a-3: per-task / per-assignee progress + Review work-split leak fix.
        self.assertIn('id="caseLabelingTaskProgress"', INDEX_HTML)
        self.assertIn("function renderCaseLabelingTaskProgress", APP_JS)
        self.assertIn("function caseLabelingTaskOptionLabel", APP_JS)
        self.assertIn("def labeling_task_progress", APP_PY_LABELING_DB)
        self.assertIn("database.labeling_task_progress", APP_PY_LABELING_ROUTER)
        self.assertIn(
            "\"WHERE split.task_kind != 'labeling'\"", APP_PY_CASES_DB
        )
        # M8b: confusion-pair + scenario cluster chips on the labeling gallery.
        self.assertNotIn('id="caseLabelingClusterStrip"', INDEX_HTML)
        self.assertIn('id="labelingSummaryPage"', INDEX_HTML)
        self.assertIn('data-page-target="labeling-summary"', INDEX_HTML)
        self.assertIn('function renderLabelingSummary', LABELING_SUMMARY_JS)
        for filter_id in (
            "labelSummarySearch", "labelSummaryTaskPicker", "labelSummaryStatusPicker",
            "labelSummaryAuthorPicker", "labelSummaryAssigneePicker",
            "labelSummaryGtPicker", "labelSummaryLabelPicker",
            "labelSummaryDiscussionPicker", "labelSummaryExclusionPicker",
        ):
            self.assertIn(f'id="{filter_id}"', INDEX_HTML)
        self.assertIn('class="analysis-summary-grid"', LABELING_SUMMARY_JS)
        self.assertIn('class="analysis-decision-grid"', LABELING_SUMMARY_JS)
        self.assertIn('id="labelSummaryClusterPanels"', LABELING_SUMMARY_JS)
        self.assertIn('id="labelSummaryCaseList"', LABELING_SUMMARY_JS)
        self.assertIn('function restoreLabelSummaryRoute()', LABELING_SUMMARY_JS)
        self.assertIn('function labelSummaryRouteOptions(overrides = {})', LABELING_SUMMARY_JS)
        self.assertIn('if (page === "labeling-summary")', APP_JS)
        self.assertIn('target === "labeling-summary" && typeof labelSummaryRouteOptions === "function"', APP_JS)
        self.assertIn('const filters = labelingTaskFilterPayload();', CAMPAIGNS_JS)
        self.assertIn('status: str = "all"', APP_PY_LABELING_ROUTER)
        self.assertIn('database.labeling_labelers', APP_PY_LABELING_ROUTER)
        self.assertIn('database.labeling_assignees', APP_PY_LABELING_ROUTER)
        self.assertIn("function renderCaseLabelingClusterStrip", APP_JS)
        self.assertIn("function loadCaseLabelingClusters", APP_JS)
        self.assertIn('cluster: state.caseLabeling.cluster || ""', APP_JS)
        self.assertIn(
            'cluster: cluster === "adjudicated" || /^(pair|scenario):.{1,200}$/.test(cluster) ? cluster : ""',
            APP_JS,
        )
        self.assertIn("def labeling_clusters", APP_PY_LABELING_DB)
        self.assertIn("def _parse_labeling_cluster", APP_PY_LABELING_DB)
        self.assertIn("database.labeling_clusters", APP_PY_LABELING_ROUTER)
        self.assertIn('"/api/labeling/clusters"', APP_PY_LABELING_ROUTER)
        self.assertIn(".review-cluster-strip[hidden] { display: none; }", STYLES_CSS)
        task_filter_payload = APP_JS.split("function labelingTaskFilterPayload()", 1)[1].split("\n}", 1)[0]
        self.assertIn('cluster: state.caseLabeling.cluster || ""', task_filter_payload)
        # Case and Summary keep the same two-row model-free filter contract.
        self.assertIn(
            "grid-template-columns: repeat(5, minmax(0, 1fr));",
            STYLES_CSS,
        )
        self.assertIn('id="caseLabelingGtPicker"', INDEX_HTML)
        self.assertIn('id="caseLabelingDiscussionPicker"', INDEX_HTML)
        self.assertIn('id="openCaseLabelingIssueQueryButton"', INDEX_HTML)
        self.assertIn('id="openLabelSummaryIssueQueryButton"', INDEX_HTML)
        self.assertIn('id="labelSummaryExportGt"', INDEX_HTML)
        self.assertIn("function exportLabelingGtUpdate", APP_JS)
        self.assertIn('class="multi-filter" id="caseLabelingStatusPicker"', INDEX_HTML)
        self.assertIn('class="multi-filter" id="caseLabelingGtPicker"', INDEX_HTML)
        self.assertIn('class="multi-filter" id="labelSummaryStatusPicker"', INDEX_HTML)
        self.assertIn("function renderLabelSummaryMultiPicker", LABELING_SUMMARY_JS)
        self.assertIn('currentRunReviewStatusMarkup(item, { compact: true })', APP_JS)
        self.assertIn('const prefixMarkup = compact', APP_JS)
        self.assertIn('id="caseLabelingExportGt"', INDEX_HTML)
        self.assertIn('id="caseLabelingReset"', INDEX_HTML)
        filters_form = INDEX_HTML.split('id="caseLabelingFilterForm"', 1)[1].split("</form>", 1)[0]
        self.assertEqual(filters_form.count("<label"), 9)
        self.assertNotIn('id="caseLabelingExportGt"', filters_form)
        self.assertIn(
            '<div class="gallery-heading-actions"><button class="button button-quiet" id="caseLabelingExportGt" type="button">',
            INDEX_HTML,
        )
        self.assertIn(
            '<button class="button button-primary" id="caseLabelingCreateTask" type="button">',
            INDEX_HTML,
        )
        # M8c #24: the standalone page reuses the experiment card surface.
        self.assertIn(".intent-experiment-create, .intent-experiment-history {", STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .intent-experiment-create,', STYLES_CSS)
        self.assertIn('id="labelingTaskCancel"', INDEX_HTML)
        # Writers see labeling/summary; assignment creation remains admin-only.
        self.assertIn("const caseLabelingNavGroup = $(\"#caseLabelingNavGroup\");", APP_JS)
        self.assertIn("caseLabelingNavGroup.hidden = !canLabelCases", APP_JS)
        self.assertIn("caseLabelingNavGroup.hidden = !hasDashboardWriteRole()", APP_JS)
        # Exactly one paste path per form: Review evidence, Markdown comment
        # composer, and the Case-labeling screenshot zone.
        self.assertIn('// Single form-level paste handler', APP_JS)
        self.assertEqual(APP_JS.count('addEventListener("paste"'), 3)
        self.assertIn('textarea.addEventListener("paste"', APP_JS)
        self.assertIn("event.stopPropagation()", APP_JS)
        # Shared anchored dropdowns: prefer down, flip by free space.
        self.assertIn("function positionAnchoredPanel", APP_JS)
        self.assertIn("function openAnchoredPanel", APP_JS)
        self.assertIn("function populateUiSelect", APP_JS)
        self.assertIn("function bindUiSelect", APP_JS)
        self.assertNotIn("function bindReviewStatusPicker", APP_JS)
        self.assertIn('id="expectedOutputInput"', APP_JS)
        self.assertIn("function syncExpectedOutputFromTags", APP_JS)
        self.assertIn("function expectedOutputSelectionState", APP_JS)
        self.assertIn('class="review-expected-output-heading"', APP_JS)
        self.assertIn('class="expected-output-rule"', APP_JS)
        self.assertIn("Tags 指向多个期望输出，请先消除冲突", APP_JS)
        self.assertIn('class="ui-select-inference-marker"', APP_JS)
        self.assertIn(".ui-select-option.is-inferred", STYLES_CSS)
        self.assertIn(".expected-output-picker .ui-select-summary", STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .ui-select-inference-marker', STYLES_CSS)
        self.assertIn("option.dataset.inferred =", APP_JS)
        self.assertIn('option.value === inference.value ? "true" : "false"', APP_JS)
        self.assertIn('expectedOutputInput.dataset.selectionSource = "manual"', APP_JS)
        self.assertIn('conflictKind === "selection"', APP_JS)
        self.assertIn("改回自动推断项或调整 Tags", APP_JS)
        self.assertIn("select.disabled = false", APP_JS)
        self.assertNotIn("select.disabled = true", APP_JS)
        self.assertIn('uiText("状态：选择冲突", "Status: Selection conflict")', APP_JS)
        self.assertIn(".review-expected-output-heading", STYLES_CSS)
        self.assertIn(".review-expected-output-hint.is-conflict", STYLES_CSS)
        self.assertIn("font-size: 12px", STYLES_CSS)
        self.assertIn("text-overflow: ellipsis; white-space: nowrap", STYLES_CSS)
        self.assertIn(".expected-output-rule-popover", STYLES_CSS)
        self.assertIn('false_trigger: "误触发"', APP_JS)
        self.assertIn('ra: "正确触发"', APP_JS)
        self.assertIn('no_assist: "无需协助"', APP_JS)
        self.assertIn('expected_output: $("#expectedOutputInput")?.value || ""', APP_JS)
        self.assertNotIn('review_status: $("#reviewStatusInput").value', APP_JS)
        self.assertIn('id="exportTrailExpectedOutputButton"', INDEX_HTML)
        self.assertIn("导出 GT 更新表", INDEX_HTML)
        self.assertNotIn("trail-export-button", INDEX_HTML)
        self.assertNotIn(".trail-export-button", STYLES_CSS)
        self.assertIn("判错复核", INDEX_HTML)
        self.assertIn('id="reviewStatusFilter"', INDEX_HTML)
        self.assertIn('reviewStatus: getMultiFilterValues($("#reviewStatusFilter"))', APP_JS)
        self.assertIn('params.set("review_status", reviewStatus)', APP_JS)
        self.assertIn('review_status: joinFilterList(getMultiFilterValues($("#reviewStatusFilter")))', APP_JS)
        self.assertIn('id="expectedOutputPicker"', APP_JS)
        self.assertIn('bindUiSelect($("#expectedOutputPicker")', APP_JS)
        self.assertIn('pending: uiText("待开始", "Pending")', APP_JS)
        self.assertIn('reviewed: t("status.matches_gt")', APP_JS)
        self.assertIn('downloadReviewAnalysis("trail_xlsx")', APP_JS)
        self.assertIn("function renderAnalysisComparisonFilter", APP_JS)
        self.assertIn("function bindAnalysisComparisonPicker", APP_JS)
        self.assertIn('id="modelRunPicker"', INDEX_HTML)
        self.assertIn('id="analysisComparisonFilter"', INDEX_HTML)
        self.assertIn('class="multi-filter" id="analysisComparisonFilter"', INDEX_HTML)
        self.assertIn("MediaKindPicker", APP_JS)
        self.assertIn("Prefer down", APP_JS)
        # Fixed panels must use pixel width — % min-width becomes viewport width.
        self.assertIn("min-width: 0 !important", STYLES_CSS)
        self.assertIn("panel.style.minWidth = widthPx", APP_JS)
        self.assertIn('id="gatewayProviderPicker"', INDEX_HTML)
        self.assertIn("function bindGatewayProviderPicker", APP_JS)
        self.assertIn("function closeGatewayProviderPicker", APP_JS)
        self.assertIn("gateway-provider-option", APP_JS)
        self.assertIn(".gateway-provider-picker-panel", STYLES_CSS)
        self.assertIn("function bindSelectedReviewTagControls", APP_JS)
        self.assertIn("const section = container.dataset.selectedTagsSection", APP_JS)
        self.assertIn("REVIEW_DRAFT_STORAGE_PREFIX", APP_JS)
        self.assertIn("persistReviewDraft", APP_JS)
        self.assertIn("beforeunload", APP_JS)
        self.assertIn("if (runId) return bound;", APP_JS)
        self.assertIn("legacy unbound annotation", APP_JS)
        self.assertIn("clearReviewDraft(issueId, payload.model_run_id, payload.work_split_id, payload.author)", APP_JS)
        self.assertIn("comparison-side-label", APP_JS)
        self.assertIn("state.reviewComparisonStatus = \"all\";", APP_JS)
        self.assertIn("const displayPrediction = prediction || (comparisonStatus === \"none\" ? \"NONE\" : \"\")", APP_JS)
        self.assertIn("comparison-summary > .label-正确触发", STYLES_CSS)
        self.assertIn("height: 20px; box-sizing: border-box", STYLES_CSS)
        self.assertIn("min-height: 20px; line-height: 20px", STYLES_CSS)
        self.assertIn("max-width: 100%; min-height: 20px", STYLES_CSS)
        self.assertIn("flex: 0 1 auto; max-width: 100%", STYLES_CSS)
        self.assertIn("position: absolute; right: 4px; top: 50%", STYLES_CSS)
        self.assertIn("padding-right: 17px", STYLES_CSS)
        self.assertIn('data-tag-section="${escapeHtml(section)}"', APP_JS)
        self.assertIn('analysis-chip.tag-chip[data-tag-group="false_trigger"]', STYLES_CSS)
        self.assertIn("visibility: hidden", STYLES_CSS)
        self.assertIn('[data-tag-group="false_trigger"]', STYLES_CSS)
        self.assertIn('[data-tag-group="true_trigger"]', STYLES_CSS)
        self.assertIn('[data-tag-group="ra"]', STYLES_CSS)
        self.assertIn('.app-shell.sidebar-collapsed .app-sidebar', STYLES_CSS)
        self.assertIn('background: var(--raised);', STYLES_CSS)
        self.assertIn('[data-tag-group="no_assist"]', STYLES_CSS)
        self.assertIn("model_run_id: state.reviewEditRunId", APP_JS)
        self.assertIn("expected_previous_annotation_id", APP_JS)
        self.assertIn("history-run", APP_JS)
        self.assertIn("toFixed(3)", APP_JS)
        self.assertIn("is-compact", STYLES_CSS)
        self.assertIn('data-open-history="review"', APP_JS)
        self.assertIn('id="gtFilter"', INDEX_HTML)
        self.assertIn('data-placeholder="全部 GT"', INDEX_HTML)
        self.assertIn("data-multi-select-all", APP_JS)
        self.assertIn("data-multi-invert", APP_JS)
        self.assertIn("data-multi-clear", APP_JS)
        self.assertIn(
            'return comparisonStatusParam(getMultiFilterValues(root));',
            APP_JS,
        )
        self.assertIn(
            'An existing filter with no checked values is an explicit "全部结果"',
            APP_JS,
        )
        self.assertIn(
            'Zero checked values is the user\'s explicit "全部结果" choice.',
            APP_JS,
        )
        self.assertIn('if (runId) {\n      url.searchParams.set("comparison", comparisonStatus);', APP_JS)
        self.assertNotIn('if (runId && comparisonStatus !== "all")', APP_JS)
        # loadRuns() and loadCases() overlap on first paint.  Until the native
        # select owns real options, its temporary empty value must not erase a
        # run supplied by the deep link.
        self.assertIn('const runFilter = $("#modelRunFilter");', APP_JS)
        self.assertIn('const runOptionsReady = Boolean(', APP_JS)
        self.assertIn('[...runFilter.options].some((option) => option.value)', APP_JS)
        self.assertIn('if (runOptionsReady)', APP_JS)
        self.assertIn('state.selectedRunId = runFilter.value;', APP_JS)
        self.assertIn("class=\"multi-filter\"", INDEX_HTML)
        self.assertIn(".analysis-pie-groups.dual", STYLES_CSS)
        self.assertIn(".analysis-pie-legend-line", STYLES_CSS)
        self.assertIn(".analysis-pie-group:has(.is-hover) .analysis-pie-slice:not(.is-hover)", STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .analysis-pie-slice.is-hover', STYLES_CSS)
        self.assertIn('html[data-color-theme="light"] .analysis-pie-tooltip', STYLES_CSS)
        self.assertIn("function paintAnalysisFromCache", APP_JS)
        self.assertIn("function enterAnalysisPage", APP_JS)
        self.assertIn("function buildAnalysisQueryParams", APP_JS)
        self.assertIn("@keyframes analysis-pie-enter", STYLES_CSS)
        self.assertIn("analysis-pie-svg is-enter", APP_JS)
        self.assertIn("html.ra-ui-ready .app-frame", STYLES_CSS)
        self.assertIn('html[data-sidebar-pref="collapsed"] .app-frame', STYLES_CSS)
        self.assertIn("dataset.sidebarPref", INDEX_HTML)
        self.assertIn("function markUiReady", APP_JS)
        self.assertIn("function bindMobileFilterDrawers", APP_JS)
        self.assertIn("data-mobile-filter-toggle", INDEX_HTML)
        self.assertIn("data-mobile-filter-panel", INDEX_HTML)
        self.assertIn('id="mobileSidebarBackdrop"', INDEX_HTML)
        self.assertIn("mobileSidebarOpen", APP_JS)
        self.assertIn("isMobileSidebarViewport", APP_JS)
        self.assertIn("sidebar-mobile-open", APP_JS)
        self.assertIn("mobile-sidebar-backdrop", STYLES_CSS)
        self.assertIn("margin-left: 0;", STYLES_CSS)
        self.assertIn(".review-tag-groups { grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 6px; }", STYLES_CSS)
        self.assertIn(".run-source-tab:not(.active) > span:nth-child(2)", STYLES_CSS)
        self.assertIn(".run-source-tab.active {", STYLES_CSS)
        self.assertIn('title="Model result file"', INDEX_HTML)
        self.assertIn('class="ui-lang-zh">模型结果文件</strong>', INDEX_HTML)
        self.assertIn(".mobile-filter-bar", STYLES_CSS)
        # Phone topbar: title row separate from dataset picker so h1 never stacks vertically.
        self.assertIn('"brand actions"', STYLES_CSS)
        self.assertIn('"baselines baselines"', STYLES_CSS)
        self.assertIn('"metrics metrics"', STYLES_CSS)
        # Metrics use equal grid cells (not clipped horizontal scroll).
        self.assertIn("Equal 4 columns", STYLES_CSS)
        self.assertIn("grid-template-columns: repeat(4, minmax(0, 1fr))", STYLES_CSS)
        # Narrow desktop also wraps metrics; cells are centered.
        self.assertIn("max-width: 1200px", STYLES_CSS)
        self.assertIn("align-items: center; justify-content: center", STYLES_CSS)
        self.assertIn("text-align: center", STYLES_CSS)
        self.assertIn("env(safe-area-inset-top", STYLES_CSS)
        self.assertIn("#dce6f2", STYLES_CSS)
        self.assertIn(".multi-filter-trigger", STYLES_CSS)
        self.assertIn(".multi-filter-option {", STYLES_CSS)
        self.assertIn("select option { color: #eef4fa; background: #111a27; font-weight: 560; }", STYLES_CSS)
        self.assertIn(
            ".multi-filter-option span { min-width: 0; overflow: hidden; color: #f2f6fb; text-overflow: ellipsis; white-space: nowrap; }",
            STYLES_CSS,
        )
        self.assertIn(".tag-option-check span", STYLES_CSS)
        self.assertIn(".multi-filter-option:has(input:checked)", STYLES_CSS)
        self.assertIn(".multi-filter.is-disabled { pointer-events: none; }", STYLES_CSS)
        self.assertIn("color: #ffffff", STYLES_CSS)
        self.assertIn(".multi-filter-action", STYLES_CSS)
        self.assertIn('id="resetReviewAnalysisButton"', INDEX_HTML)
        self.assertIn('class="ui-lang-zh">重置</span>', INDEX_HTML)
        self.assertIn("grid-template-columns: repeat(2, minmax(0, 1fr))", STYLES_CSS)

    def test_detail_media_reuses_frame_timeline_outside_modal(self) -> None:
        self.assertIn("function mediaTimelineMarkup", APP_JS)
        self.assertIn('data-detail-media-frame', APP_JS)
        self.assertIn('mediaTimelineMarkup(activeFrames, index, "detail-media-frame")', APP_JS)
        self.assertIn('mediaTimelineButtonsMarkup(frames, state.media.index, "media-frame")', APP_JS)
        self.assertIn(".detail-media-timeline", STYLES_CSS)
        self.assertIn('aria-label="Issue 媒体" aria-keyshortcuts="0"', APP_JS)
        self.assertIn('} else if (key === "0") {', APP_JS)
        self.assertIn('querySelector("[data-video-t0]")', APP_JS)
        self.assertIn('$("#mediaVideoStage")?.querySelector("[data-video-t0]")?.click();', APP_JS)
        self.assertIn('player.querySelector("[data-video-t0]").addEventListener("click", seekToT0)', APP_JS)
        self.assertIn('video.addEventListener("loadedmetadata", seekToT0, { once: true })', APP_JS)
        self.assertIn("function videoT0PlayerPosition(configuredDuration, decodedDuration = 0)", APP_JS)
        self.assertIn("0 视频回 t0 / 图片复位", INDEX_HTML)
        self.assertIn("const t0Index = heroFrameIndex(frames);", APP_JS)
        self.assertIn("#reviewPane .review-dropdown[open]", APP_JS)

    def test_issue_detail_exposes_optional_ra_recording_and_event_links(self) -> None:
        self.assertIn("external_links", APP_JS)
        self.assertIn("RA 录屏 ↗", APP_JS)
        self.assertIn("RA Event ↗", APP_JS)
        self.assertIn("屏蔽 RA ↗", APP_JS)
        self.assertIn("externalLinks.disable_ra_simulation_url", APP_JS)
        self.assertIn('font: 11px "SFMono-Regular", Consolas, monospace', STYLES_CSS)
        self.assertIn(".detail-title { min-width: 0; display: flex; align-items: center; flex-wrap: nowrap; gap: 5px 7px; }", STYLES_CSS)
        self.assertIn(".detail-external-links { display: inline-flex; align-items: center; flex-wrap: nowrap; gap: 5px 7px; white-space: nowrap; }", STYLES_CSS)
        self.assertIn(".detail-external-links { width: 100%; flex-wrap: wrap; white-space: normal; }", (STATIC_DIR / "css/mobile.css").read_text(encoding="utf-8"))
        self.assertIn("function openRaEventDialog(caseData)", APP_JS)
        self.assertIn('data-open-ra-event', APP_JS)
        self.assertIn('data-open-ra-event aria-keyshortcuts=\\"T\\"', APP_JS)
        self.assertIn('detail-external-shortcut', APP_JS)
        self.assertIn('if (key === "t" && raEventDialog?.open)', APP_JS)
        self.assertIn('raEventButton.click();', APP_JS)
        self.assertIn('data-shortcut-search="t"', INDEX_HTML)
        self.assertIn("detailExternalLinks", APP_JS)
        self.assertIn('"/api/cases/" + encodeURIComponent(issueId) + "/trail-metadata"', APP_JS)
        self.assertIn("scheduleTrailDetailMetadata(issueId, requestSeq)", APP_JS)
        self.assertIn("TRAIL_DETAIL_DELAY_MS = 350", APP_JS)
        self.assertIn("state.trailMetadataController?.abort()", APP_JS)
        self.assertIn("applyTrailDetailMetadata(result, issueId, requestSeq)", APP_JS)
        self.assertIn("externalLinks.ares_trip_id", APP_JS)
        self.assertIn("externalLinks.ares_timestamp_ms", APP_JS)
        self.assertIn("dashboard_should_exclude", APP_JS)
        self.assertIn("hasCurrentRunReview", APP_JS)
        self.assertIn("!hasCurrentRunReview && !hasLocalDraft && !state.reviewFormDirty", APP_JS)
        self.assertNotIn("reviewExcludeTrailHint", APP_JS)
        self.assertNotIn("Trail info marks this Issue for exclusion", APP_JS)
        self.assertIn('id="raEventDialog"', INDEX_HTML)
        self.assertIn('id="raEventTableBody"', INDEX_HTML)
        self.assertIn("t ± seconds", INDEX_HTML)
        self.assertIn("function reviewCaseT0TimestampMs(caseData)", APP_JS)
        self.assertIn("function formatRaEventRelativeTime(value, t0TimestampMs)", APP_JS)
        self.assertIn("ra-event-relative-time", APP_JS)
        self.assertIn("t0TimestampMs: reviewCaseT0TimestampMs(caseData)", APP_JS)
        self.assertIn(".ra-event-table td:nth-child(5)", STYLES_CSS)
        self.assertIn("ra-event-table", STYLES_CSS)

    def test_issue_detail_keeps_media_first_and_avoids_loading_flash(self) -> None:
        preferred_start = APP_JS.index("function preferredMediaKind(caseData)")
        bev_offset = APP_JS.index("if (caseData?.assets?.frames?.length)", preferred_start)
        video_offset = APP_JS.index("if (caseData?.assets?.video?.url)", preferred_start)
        self.assertLess(video_offset, bev_offset)
        self.assertIn('preload="metadata"', APP_JS)
        self.assertIn("function releaseBevVideoPlayer(root)", APP_JS)
        self.assertIn("function hydrateDetailMediaControls(caseData)", APP_JS)
        self.assertNotIn('posterUrl: frames[heroFrameIndex(frames)]?.url || ""', APP_JS)
        self.assertNotIn('posterUrl: bev[heroFrameIndex(bev)]?.url || ""', APP_JS)
        self.assertIn('poster="${escapeHtml(posterUrl)}"', APP_JS)
        self.assertIn('?include_media=false', APP_JS)
        self.assertIn('/api/cases/${encodeURIComponent(issueId)}/media', APP_JS)
        self.assertIn("async function loadDeferredCaseMedia", APP_JS)
        self.assertIn("function hydrateDetailMedia(caseData)", APP_JS)
        self.assertIn("hydrateDetailMedia(state.selectedCase)", APP_JS)
        self.assertIn("function releaseReviewSubmitLock(submitButton)", APP_JS)
        self.assertIn("function reviewSaveNavigationContext(issueId)", APP_JS)
        self.assertIn("async function reconcileReviewQueueAfterSave(context)", APP_JS)
        self.assertIn("async function refreshReviewAfterSave(context)", APP_JS)
        self.assertIn('await loadCases({ keepSelection: true, page: context.page })', APP_JS)
        self.assertIn('context.hadNext ? "已保存，已跳到下一个筛选结果。"', APP_JS)
        self.assertIn("Review 已保存，但筛选队列刷新失败；请刷新页面继续。", APP_JS)
        self.assertIn("state.reviewQueueStale = true", APP_JS)
        self.assertIn("await refreshReviewAfterSave(task.navigationContext)", APP_JS)
        self.assertIn("await refreshReviewAfterSave(navigationContext)", APP_JS)
        self.assertIn("const screenshotItems = [...state.pendingReviewImages];", APP_JS)
        self.assertIn("const screenshotFiles = screenshotItems.map((item) => item.file);", APP_JS)
        self.assertIn("enqueueBackgroundReviewUpload(task);", APP_JS)
        self.assertIn("state.backgroundReviewUploads", APP_JS)
        self.assertIn("restoreFailedReviewUploadImages(issueId)", APP_JS)
        self.assertIn("restoreFailedReviewUploadImages(caseData.issue_id)", APP_JS)
        self.assertIn("function activeReviewUploadForIssue", APP_JS)
        self.assertIn('class="review-upload-progress" role="status" aria-live="polite"', APP_JS)
        self.assertIn("正在后台保存", APP_JS)
        self.assertIn("已进入后台保存，可继续切换 Issue", APP_JS)
        self.assertIn("已保存 Review 和 ${task.files.length} 张截图", APP_JS)
        self.assertIn("releaseReviewUploadPreviews(task)", APP_JS)
        self.assertIn(".review-upload-progress {", STYLES_CSS)
        self.assertIn(".pending-screenshot.is-uploading::after", STYLES_CSS)
        self.assertIn("state.caseMediaController?.abort()", APP_JS)
        self.assertIn("prefetchAdjacentCaseCores(issueId)", APP_JS)
        self.assertIn("CASE_DETAIL_PREFETCH_TTL_MS = 15000", APP_JS)
        self.assertIn("data.preview_thumbnail_url = safeSameOriginAssetUrl", APP_JS)
        self.assertNotIn("video.poster_url = state.selectedCase.preview_thumbnail_url", APP_JS)
        self.assertIn('class="detail-media-preview"', APP_JS)
        self.assertIn(".hero-media-button .detail-media-image { position: relative; z-index: 1; }", STYLES_CSS)
        self.assertIn('media_status === "pending"', APP_JS)
        self.assertIn('const videoRequest = request("video")', APP_JS)
        self.assertIn('const imagesRequest = request("images")', APP_JS)
        self.assertIn("const hadDetail = Boolean(state.selectedCase)", APP_JS)
        self.assertIn("}, 140);", APP_JS)
        self.assertIn("function enqueueBackgroundReviewUpload(task)", APP_JS)
        self.assertIn("state.reviewUploadTail", APP_JS)
        self.assertIn("annotations-with-attachments", APP_JS)
        self.assertIn("后台上传失败", APP_JS)

    def test_gallery_refresh_reuses_loaded_thumbnails_without_transitions(self) -> None:
        self.assertIn("function caseGallerySignature(items)", APP_JS)
        self.assertIn("function reuseGalleryThumbnails(list, previousThumbnails)", APP_JS)
        self.assertIn("previous.image.naturalWidth <= 0", APP_JS)
        self.assertNotIn("transition: border-color 150ms ease-out, background 150ms ease-out", STYLES_CSS)

    def test_media_switch_preloads_and_decodes_before_replacing_the_view(self) -> None:
        self.assertIn("function preloadDetailImage(caseData, kind, index, root, onReady)", APP_JS)
        self.assertIn("image.decode", APP_JS)
        self.assertIn('root.setAttribute("aria-busy", "true")', APP_JS)
        self.assertIn("preloadDetailImage(caseData, kind, nextIndex, root", APP_JS)
        self.assertIn("function preloadMediaDialogImage(url, onReady)", APP_JS)
        self.assertIn('previewImage.dataset.mediaUrl = targetUrl', APP_JS)
        self.assertIn("function applyDetailImageFrame(root, caseData, kind, index, loadedImage = null)", APP_JS)
        self.assertIn("image.before(nextImage)", APP_JS)
        self.assertIn('nextImage.style.visibility = "visible"', APP_JS)
        self.assertIn('image.style.zIndex = "1"', APP_JS)
        self.assertIn("window.requestAnimationFrame(() => window.requestAnimationFrame(commit))", APP_JS)
        self.assertIn('root.querySelectorAll("#detailMediaPreviousButton, #detailMediaNextButton")', APP_JS)
        self.assertNotIn('root.querySelectorAll("button, select")', APP_JS)
        self.assertIn('class="detail-media-image"', APP_JS)
        self.assertIn(".hero-media-button img.detail-media-image", STYLES_CSS)
        self.assertNotIn(".detail-media-image { opacity: 0", STYLES_CSS)
        self.assertNotIn(".issue-thumbnail img.is-loaded", STYLES_CSS)
        self.assertNotIn(".issue-card:hover .issue-thumbnail img", STYLES_CSS)

    def test_detail_queue_index_is_editable_for_jump(self) -> None:
        self.assertIn('id="detailQueueIndexInput"', APP_JS)
        self.assertIn("function jumpToQueueIndex", APP_JS)
        self.assertIn("function bindDetailQueueIndexJump", APP_JS)
        self.assertIn(".detail-queue-index-input", STYLES_CSS)
        self.assertIn("manual-triage-560", APP_ENTRY_JS)

    def test_desktop_layout_panels_are_mouse_and_keyboard_resizable(self) -> None:
        self.assertIn('id="sidebarResizer" role="separator"', INDEX_HTML)
        self.assertIn('id="reviewPaneResizer" role="separator"', INDEX_HTML)
        self.assertIn('id="caseLabelingPaneResizer" role="separator"', INDEX_HTML)
        self.assertIn('aria-orientation="vertical"', INDEX_HTML)
        self.assertIn('"layout-resize.js"', APP_ENTRY_JS)
        self.assertIn("function bindLayoutResizers", APP_JS)
        self.assertIn('separator.addEventListener("pointerdown"', APP_JS)
        self.assertIn('separator.addEventListener("keydown"', APP_JS)
        self.assertIn('separator.addEventListener("dblclick"', APP_JS)
        self.assertIn('storageKey: "ra-triage-sidebar-width"', APP_JS)
        self.assertIn('storageKey: "ra-triage-review-pane-width"', APP_JS)
        self.assertIn('caseLabelingPane: {', APP_JS)
        self.assertIn('element: "#caseLabelingPaneResizer"', APP_JS)
        self.assertIn("--app-sidebar-width", STYLES_CSS)
        self.assertIn("--review-pane-width", STYLES_CSS)

    def test_desktop_review_video_preserves_16_by_9_and_allows_page_growth(self) -> None:
        self.assertIn('data-detail-media-kind="${escapeHtml(kind)}"', APP_JS)
        self.assertIn('"detail-pane-video"', APP_JS)
        self.assertIn('root?.dataset.detailMediaKind === "video"', APP_JS)
        self.assertIn("minmax(304px, var(--review-pane-width, 350px))", STYLES_CSS)
        self.assertIn(".review-tag-groups { min-width: 0; max-width: 100%; }", STYLES_CSS)
        self.assertIn(".review-section-heading .review-heading-actions { min-width: 0; flex-wrap: wrap; }", STYLES_CSS)
        self.assertIn(".review-detail-workspace > .review-pane { min-height: calc(100dvh - 75px); }", STYLES_CSS)
        self.assertIn(".detail-pane.detail-pane-video {\n    height: auto; min-height: 0;", STYLES_CSS)
        self.assertIn('.detail-pane.detail-pane-video > .detail-hero-media[data-detail-media-kind="video"]', STYLES_CSS)
        self.assertIn('.detail-hero-media[data-detail-media-kind="video"] .hero-media-video', STYLES_CSS)
        self.assertIn("height: auto; min-height: 0; aspect-ratio: 16 / 9", STYLES_CSS)
        self.assertIn("min-height: 0; flex: 0 0 auto", STYLES_CSS)
        self.assertIn("object-fit: contain", STYLES_CSS)
        self.assertIn("html.ra-ui-ready .app-sidebar { transition: width 200ms ease-out; }", STYLES_CSS)
        self.assertNotIn("clamp(320px, 24cqw, 380px)", STYLES_CSS)
        self.assertNotIn("clamp(300px, 27cqw, 320px)", STYLES_CSS)
        mobile_css = (STATIC_DIR / "css/mobile.css").read_text(encoding="utf-8")
        self.assertIn(".hero-media-button, .hero-media-placeholder { min-height: 0; aspect-ratio: 16 / 9; }", mobile_css)
